.TH "md_MAINTAINERS" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_MAINTAINERS \- 🛡️ Maintainers 
.PP

.SH "Primary Maintainer"
.PP
Amber‑Sophia Schröck 
.br
 ambersophia.schroeck@mail.de 
.br
 Pronouns: dey/deren/dem/dem 
.br
 Role: Project founder, architect, and sole maintainer

.PP
\fBSystemEx\fP is developed and maintained by a single intersex author\&. 
.br
 All architectural decisions, module designs, and long‑term planning are handled by the maintainer\&.

.PP
Contributions, constructive feedback, and technical collaboration are welcome\&. 
