.TH "SystemEx.Hash.AdlerHash" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Hash.AdlerHash \- Implements the Adler hash algorithm\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemEx\&.Hash\&.IHash\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdlerHash\fP (\fBEndian\fP endian)"
.br
.RI "Craate a new instance\&. "
.ti -1c
.RI "\fBHash32\fP \fBCompute\fP (FixedVector< byte > input, uint seed)"
.br
.RI "Computes the Adler hash of the given input\&. "
.ti -1c
.RI "\fBHash64\fP \fBComputeLong\fP (FixedVector< byte > input, ulong seed)"
.br
.RI "Computes the Adler hash of the given input\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implements the Adler hash algorithm\&. 

The Adler hash algorithm is a checksum algorithm which was invented by Mark Adler in 1995\&. It is a modification of the Fletcher checksum, which was invented by John G\&. Fletcher in 1982\&. 
.PP
Definition at line \fB33\fP of file \fBAdlerHash\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Hash\&.AdlerHash\&.AdlerHash (\fBEndian\fP endian)"

.PP
Craate a new instance\&. 
.PP
\fBParameters\fP
.RS 4
\fIendian\fP The suing endian for creating a hash
.RE
.PP

.PP
Definition at line \fB42\fP of file \fBAdlerHash\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBHash32\fP SystemEx\&.Hash\&.AdlerHash\&.Compute (FixedVector< byte > input, uint seed)"

.PP
Computes the Adler hash of the given input\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP The input data to hash\&.
.br
\fIseed\fP The seed value for the hash computation\&.
.RE
.PP
\fBReturns\fP
.RS 4
The computed Adler hash as a \fBHash32\fP object\&.
.RE
.PP

.PP
Implements \fBSystemEx\&.Hash\&.IHash\fP\&.
.PP
Definition at line \fB51\fP of file \fBAdlerHash\&.cs\fP\&.
.SS "\fBHash64\fP SystemEx\&.Hash\&.AdlerHash\&.ComputeLong (FixedVector< byte > input, ulong seed)"

.PP
Computes the Adler hash of the given input\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP The input data to hash\&.
.br
\fIseed\fP The seed value for the hash computation\&.
.RE
.PP
\fBReturns\fP
.RS 4
The computed Adler hash as a \fBHash64\fP object\&.
.RE
.PP

.PP
Implements \fBSystemEx\&.Hash\&.IHash\fP\&.
.PP
Definition at line \fB70\fP of file \fBAdlerHash\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
