.TH "SystemEx.Algorithms.Compute.IClassifier< T >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Algorithms.Compute.IClassifier< T > \- Represents a simple classifier that maps an input value to a \fBTriple\fP decision (True, False, Nin)\&. 
.br
 Used for lightweight rule‑based or threshold‑based classification\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTriple\fP \fBClassify\fP (T input)"
.br
.RI "Classifies the given input and returns a three‑state decision\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a simple classifier that maps an input value to a \fBTriple\fP decision (True, False, Nin)\&. 
.br
 Used for lightweight rule‑based or threshold‑based classification\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The input type to classify\&.
.RE
.PP

.PP
Definition at line \fB33\fP of file \fBIClassifier\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTriple\fP SystemEx\&.Algorithms\&.Compute\&.IClassifier< T >\&.Classify (T input)"

.PP
Classifies the given input and returns a three‑state decision\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
