.TH "SystemEx.Drawing.ColorCMY" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Drawing.ColorCMY \- A color in the CMY (Cyan–Magenta–Yellow) color space using floating‑point components\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorCMY\fP (float c, float m, float y)"
.br
.RI "Initializes a new instance of the \fBColorCMY\fP class with the specified component values\&. "
.ti -1c
.RI "\fBColorCMY\fP (float[] x)"
.br
.RI "The default constructor initializes the color to black (C=0, M=0, Y=0)\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBC\fP\fR [get, set]\fP"
.br
.RI "The cyan component of the color, in the range 0–1\&. "
.ti -1c
.RI "float \fBM\fP\fR [get, set]\fP"
.br
.RI "The magenta component of the color, in the range 0–1\&. "
.ti -1c
.RI "float \fBY\fP\fR [get, set]\fP"
.br
.RI "The yellow component of the color, in the range 0–1\&. "
.in -1c
.SH "Detailed Description"
.PP 
A color in the CMY (Cyan–Magenta–Yellow) color space using floating‑point components\&. 
.PP
Definition at line \fB23\fP of file \fBColorCMY\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Drawing\&.ColorCMY\&.ColorCMY (float[] x)"

.PP
The default constructor initializes the color to black (C=0, M=0, Y=0)\&. 
.PP
Definition at line \fB42\fP of file \fBColorCMY\&.cs\fP\&.
.SS "SystemEx\&.Drawing\&.ColorCMY\&.ColorCMY (float c, float m, float y)"

.PP
Initializes a new instance of the \fBColorCMY\fP class with the specified component values\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP The cyan component (0–1)\&.
.br
\fIm\fP The magenta component (0–1)\&.
.br
\fIy\fP The yellow component (0–1)\&.
.RE
.PP

.PP
Definition at line \fB53\fP of file \fBColorCMY\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "float SystemEx\&.Drawing\&.ColorCMY\&.C\fR [get]\fP, \fR [set]\fP"

.PP
The cyan component of the color, in the range 0–1\&. 
.PP
Definition at line \fB30\fP of file \fBColorCMY\&.cs\fP\&.
.SS "float SystemEx\&.Drawing\&.ColorCMY\&.M\fR [get]\fP, \fR [set]\fP"

.PP
The magenta component of the color, in the range 0–1\&. 
.PP
Definition at line \fB34\fP of file \fBColorCMY\&.cs\fP\&.
.SS "float SystemEx\&.Drawing\&.ColorCMY\&.Y\fR [get]\fP, \fR [set]\fP"

.PP
The yellow component of the color, in the range 0–1\&. 
.PP
Definition at line \fB38\fP of file \fBColorCMY\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
