.TH "SystemEx.Base" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Base
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBNumberRangeStepper\fP"
.br
.RI "Provides a cursor-based stepper over a normalized numeric range\&. The stepper moves from Start to End in fixed increments and exposes forward/backward stepping, reset, and enumeration\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
