.TH "SystemEx.Drawing.ColorXYZ" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Drawing.ColorXYZ \- Represents a color in the CIE XYZ color space using floating‑point components\&. Provides basic construction, comparison, and string formatting utilities\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IEquatable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorXYZ\fP (float x, float y, float z)"
.br
.RI "Initializes a new XYZ color with the specified component values\&. "
.ti -1c
.RI "bool \fBEquals\fP (\fBColorXYZ\fP other)"
.br
.RI "Determines whether this instance is equal to another XYZ color\&. "
.ti -1c
.RI "override bool \fBEquals\fP (object? obj)"
.br
.RI "Determines whether this instance is equal to another object\&. "
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.RI "Returns a hash code based on the X, Y, and Z components\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a string representation of the XYZ color\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBX\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the X component of the XYZ color\&. "
.ti -1c
.RI "float \fBY\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the Y component of the XYZ color\&. "
.ti -1c
.RI "float \fBZ\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the Z component of the XYZ color\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a color in the CIE XYZ color space using floating‑point components\&. Provides basic construction, comparison, and string formatting utilities\&. 
.PP
Definition at line \fB24\fP of file \fBColorXYZ\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Drawing\&.ColorXYZ\&.ColorXYZ (float x, float y, float z)"

.PP
Initializes a new XYZ color with the specified component values\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP The X component\&.
.br
\fIy\fP The Y component\&.
.br
\fIz\fP The Z component\&.
.RE
.PP

.PP
Definition at line \fB50\fP of file \fBColorXYZ\&.cs\fP\&.
.PP
Referenced by \fBEquals()\fP, and \fBEquals()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SystemEx\&.Drawing\&.ColorXYZ\&.Equals (\fBColorXYZ\fP other)"

.PP
Determines whether this instance is equal to another XYZ color\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP The color to compare with\&.
.RE
.PP
\fBReturns\fP
.RS 4
\fRtrue\fP if the components match; otherwise \fRfalse\fP\&. 
.RE
.PP

.PP
Definition at line \fB63\fP of file \fBColorXYZ\&.cs\fP\&.
.PP
Referenced by \fBEquals()\fP\&.
.SS "override bool SystemEx\&.Drawing\&.ColorXYZ\&.Equals (object? obj)"

.PP
Determines whether this instance is equal to another object\&. 
.PP
Definition at line \fB72\fP of file \fBColorXYZ\&.cs\fP\&.
.SS "override int SystemEx\&.Drawing\&.ColorXYZ\&.GetHashCode ()"

.PP
Returns a hash code based on the X, Y, and Z components\&. 
.PP
Definition at line \fB79\fP of file \fBColorXYZ\&.cs\fP\&.
.SS "override string SystemEx\&.Drawing\&.ColorXYZ\&.ToString ()"

.PP
Returns a string representation of the XYZ color\&. 
.PP
Definition at line \fB86\fP of file \fBColorXYZ\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "float SystemEx\&.Drawing\&.ColorXYZ\&.X\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the X component of the XYZ color\&. 
.PP
Definition at line \fB32\fP of file \fBColorXYZ\&.cs\fP\&.
.SS "float SystemEx\&.Drawing\&.ColorXYZ\&.Y\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the Y component of the XYZ color\&. 
.PP
Definition at line \fB37\fP of file \fBColorXYZ\&.cs\fP\&.
.SS "float SystemEx\&.Drawing\&.ColorXYZ\&.Z\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the Z component of the XYZ color\&. 
.PP
Definition at line \fB42\fP of file \fBColorXYZ\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
