.TH "SystemEx.Numeric.IFloat" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Numeric.IFloat
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystemEx\&.Numeric\&.IFloat< TBias >\fP\&.
.SH "Detailed Description"
.PP 
Definition at line \fB21\fP of file \fBIFloat\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
