.TH "SystemEx.IO.Provider.IIsByteSeriablize" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.IO.Provider.IIsByteSeriablize \- Represents a type that can be serialized to and from byte arrays\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystemEx\&.Drawing\&.ColorR10G10B10A2\fP\&.
.SH "Detailed Description"
.PP 
Represents a type that can be serialized to and from byte arrays\&. 
.PP
Definition at line \fB28\fP of file \fBIHasByteSchema\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
