.TH "SystemEx.Collections.Generic.Queue" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Collections.Generic.Queue
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBUniqueDeque< T >\fP"
.br
.RI "Represents a deque that only accepts unique elements\&. Attempts to insert a value already contained in the queue will fail\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
