.TH "SystemEx.Collections.Generic.IReadOnlyContainer< T >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Collections.Generic.IReadOnlyContainer< T > \- Defines the minimal read‑only functionality required for a generic container used by the \fBSystemEx\fP collection framework\&. Implementations provide indexed access and structural inspection without allowing modification of stored elements\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystemEx\&.Collections\&.Generic\&.IContainer< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Optional< T > \fBElementAt\fP (long index)"
.br
.RI "Returns the element at the specified index\&. "
.ti -1c
.RI "Type \fBGetElementType\fP ()"
.br
.RI "Returns the runtime type of the stored elements\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Optional< T > \fBBack\fP\fR [get]\fP"
.br
.RI "Gets the Last element of the container\&. "
.ti -1c
.RI "long \fBCount\fP\fR [get]\fP"
.br
.RI "Gets the number of elements currently stored in the container\&. "
.ti -1c
.RI "Optional< T > \fBCurrent\fP\fR [get]\fP"
.br
.RI "Gets the element at the current logical position\&. The meaning of the current position is implementation‑defined\&. "
.ti -1c
.RI "Optional< T > \fBFront\fP\fR [get]\fP"
.br
.RI "Gets the first element of the container\&. "
.ti -1c
.RI "bool \fBIsEmpty\fP\fR [get]\fP"
.br
.RI "Gets a value indicating whether the container contains no elements\&. "
.ti -1c
.RI "bool \fBIsFull\fP\fR [get]\fP"
.br
.RI "Indicates whether the container is full\&. "
.ti -1c
.RI "long \fBLength\fP\fR [get]\fP"
.br
.RI "Gets the total capacity of the container, including unused slots\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the minimal read‑only functionality required for a generic container used by the \fBSystemEx\fP collection framework\&. Implementations provide indexed access and structural inspection without allowing modification of stored elements\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The element type stored in the container\&.
.RE
.PP

.PP
Definition at line \fB30\fP of file \fBIReadOnlyContainer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Optional< T > SystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\&.ElementAt (long index)"

.PP
Returns the element at the specified index\&. 
.PP
\fBParameters\fP
.RS 4
\fIindex\fP The index of the element\&.
.RE
.PP
\fBReturns\fP
.RS 4
The element at the specified index\&.
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.FixedSparsed< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.FixedVector< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Sparsed< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Vector< T >\fP\&.
.SS "Type SystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\&.GetElementType ()"

.PP
Returns the runtime type of the stored elements\&. 
.PP
\fBReturns\fP
.RS 4
The element type\&.
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.FixedSparsed< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.FixedVector< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Sparsed< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Vector< T >\fP\&.
.SH "Property Documentation"
.PP 
.SS "Optional<T> SystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\&.Back\fR [get]\fP"

.PP
Gets the Last element of the container\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.FixedSparsed< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.FixedVector< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Sparsed< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Vector< T >\fP\&.
.PP
Definition at line \fB40\fP of file \fBIReadOnlyContainer\&.cs\fP\&.
.SS "long SystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\&.Count\fR [get]\fP"

.PP
Gets the number of elements currently stored in the container\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.FixedSparsed< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.FixedVector< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Sparsed< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Vector< T >\fP\&.
.PP
Definition at line \fB61\fP of file \fBIReadOnlyContainer\&.cs\fP\&.
.SS "Optional<T> SystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\&.Current\fR [get]\fP"

.PP
Gets the element at the current logical position\&. The meaning of the current position is implementation‑defined\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.FixedSparsed< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.FixedVector< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Sparsed< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Vector< T >\fP\&.
.PP
Definition at line \fB56\fP of file \fBIReadOnlyContainer\&.cs\fP\&.
.SS "Optional<T> SystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\&.Front\fR [get]\fP"

.PP
Gets the first element of the container\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.FixedSparsed< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.FixedVector< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Sparsed< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Vector< T >\fP\&.
.PP
Definition at line \fB35\fP of file \fBIReadOnlyContainer\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\&.IsEmpty\fR [get]\fP"

.PP
Gets a value indicating whether the container contains no elements\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.FixedSparsed< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.FixedVector< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Sparsed< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Vector< T >\fP\&.
.PP
Definition at line \fB50\fP of file \fBIReadOnlyContainer\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\&.IsFull\fR [get]\fP"

.PP
Indicates whether the container is full\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.FixedSparsed< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.FixedVector< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Sparsed< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Vector< T >\fP\&.
.PP
Definition at line \fB45\fP of file \fBIReadOnlyContainer\&.cs\fP\&.
.SS "long SystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\&.Length\fR [get]\fP"

.PP
Gets the total capacity of the container, including unused slots\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.FixedSparsed< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.FixedVector< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Sparsed< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Vector< T >\fP\&.
.PP
Definition at line \fB66\fP of file \fBIReadOnlyContainer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
