.TH "SystemEx.Utils.MissingStructLayoutSequentialException" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Utils.MissingStructLayoutSequentialException \- Exception thrown when a struct used for unmanaged interop does not specify StructLayoutAttribute with LayoutKind\&.Sequential\&. 
.br
 Required for deterministic field ordering in native interop, binary serialization, and memory‑mapped structures\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMissingStructLayoutSequentialException\fP (Type type)"
.br
.RI "Creates a new exception indicating that the specified struct type must be declared with System\&.Runtime\&.InteropServices\&.StructLayout(LayoutKind\&.Sequential)\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Type \fBStructType\fP\fR [get]\fP"
.br
.RI "Gets the struct type that caused the exception\&. "
.in -1c
.SH "Detailed Description"
.PP 
Exception thrown when a struct used for unmanaged interop does not specify StructLayoutAttribute with LayoutKind\&.Sequential\&. 
.br
 Required for deterministic field ordering in native interop, binary serialization, and memory‑mapped structures\&. 
.PP
Definition at line \fB31\fP of file \fBLayout\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Utils\&.MissingStructLayoutSequentialException\&.MissingStructLayoutSequentialException (Type type)"

.PP
Creates a new exception indicating that the specified struct type must be declared with System\&.Runtime\&.InteropServices\&.StructLayout(LayoutKind\&.Sequential)\&. 
.PP
Definition at line \fB43\fP of file \fBLayout\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Type SystemEx\&.Utils\&.MissingStructLayoutSequentialException\&.StructType\fR [get]\fP"

.PP
Gets the struct type that caused the exception\&. 
.PP
Definition at line \fB35\fP of file \fBLayout\&.cs\fP\&.
.PP
Referenced by \fBMissingStructLayoutSequentialException()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
