.TH "SystemEx.Collections.Generic.IDeque< T >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Collections.Generic.IDeque< T > \- Defines the generic interface for a double-ended queue (deque)\&. A deque allows insertion and removal of elements at both the front and the back\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemEx\&.Collections\&.Generic\&.IDeque\fP\&.
.PP
Inherited by \fBSystemEx\&.Collections\&.Generic\&.Deque< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Queue\&.UniqueDeque< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBPopBack\fP (ref Optional< T > value)"
.br
.RI "Removes the element at the back of the deque\&. "
.ti -1c
.RI "bool \fBPushFront\fP (T value)"
.br
.RI "Inserts an element at the front of the deque\&. "
.in -1c

Public Member Functions inherited from \fBSystemEx\&.Collections\&.Generic\&.IQueue\fP
.in +1c
.ti -1c
.RI "void \fBClear\fP ()"
.br
.RI "Removes all elements from the queue\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "T \fBEnd\fP\fR [get]\fP"
.br
.RI "Gets the element at the back of the deque\&. "
.ti -1c
.RI "T \fBFront\fP\fR [get]\fP"
.br
.RI "Gets the element at the front of the deque\&. "
.in -1c

Properties inherited from \fBSystemEx\&.Collections\&.Generic\&.IQueue\fP
.in +1c
.ti -1c
.RI "bool \fBIsEmpty\fP\fR [get]\fP"
.br
.RI "Gets a value indicating whether the queue contains no elements\&. "
.ti -1c
.RI "bool \fBIsFull\fP\fR [get]\fP"
.br
.RI "Gets a value indicating whether the queue has reached its maximum capacity\&. "
.ti -1c
.RI "int \fBSize\fP\fR [get]\fP"
.br
.RI "Gets the number of elements currently stored in the queue\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the generic interface for a double-ended queue (deque)\&. A deque allows insertion and removal of elements at both the front and the back\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The type of elements stored in the deque\&.
.RE
.PP

.PP
Definition at line \fB34\fP of file \fBIDeque\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool \fBSystemEx\&.Collections\&.Generic\&.IDeque\fP< T >\&.PopBack (ref Optional< T > value)"

.PP
Removes the element at the back of the deque\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP When this method returns, contains the removed element if the operation succeeded; otherwise remains unchanged\&. 
.RE
.PP
\fBReturns\fP
.RS 4
\fRtrue\fP if an element was removed; otherwise \fRfalse\fP\&. 
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.Deque< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Queue\&.UniqueDeque< T >\fP\&.
.SS "bool \fBSystemEx\&.Collections\&.Generic\&.IDeque\fP< T >\&.PushFront (T value)"

.PP
Inserts an element at the front of the deque\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The element to insert at the front\&.
.RE
.PP
\fBReturns\fP
.RS 4
\fRtrue\fP if the element was successfully inserted; otherwise \fRfalse\fP \&. 
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.Deque< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Queue\&.UniqueDeque< T >\fP\&.
.SH "Property Documentation"
.PP 
.SS "T \fBSystemEx\&.Collections\&.Generic\&.IDeque\fP< T >\&.End\fR [get]\fP"

.PP
Gets the element at the back of the deque\&. Accessing this property does not modify the deque\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.Deque< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Queue\&.UniqueDeque< T >\fP\&.
.PP
Definition at line \fB49\fP of file \fBIDeque\&.cs\fP\&.
.SS "T \fBSystemEx\&.Collections\&.Generic\&.IDeque\fP< T >\&.Front\fR [get]\fP"

.PP
Gets the element at the front of the deque\&. Accessing this property does not modify the deque\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.Deque< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Queue\&.UniqueDeque< T >\fP\&.
.PP
Definition at line \fB41\fP of file \fBIDeque\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
