.TH "SystemEx.Rand.Engine" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Rand.Engine
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIRandomEngine\fP"
.br
.RI "Defines the contract for a deterministic 32-bit random number generator engine\&. Implementations provide a reproducible sequence of unsigned 32-bit values based on an initial seed\&. "
.ti -1c
.RI "class \fBIsaac32Engine\fP"
.br
.RI "Represents the ISAAC 32-bit random number generator\&. "
.ti -1c
.RI "struct \fBIsaac32EngineSeed\fP"
.br
.RI "Represents the seed container used by the \fBIsaac32Engine\fP\&. Stores the three 32-bit seed values required for initializing the ISAAC random number generator\&. "
.ti -1c
.RI "class \fBMTwisterEngine\fP"
.br
.ti -1c
.RI "struct \fBMTwisterEngineSeed\fP"
.br
.RI "Represents the seed container used by the \fBMTwisterEngine\fP\&. The seed consists of five 32-bit values: the primary user-provided seed and four additional system-derived values to increase initialization entropy\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
