.TH "SystemEx.Empty" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Empty \- Represents an empty class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly Empty \fBNone\fP = new Empty()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents an empty class\&. 
.PP
Definition at line \fB21\fP of file \fBEmpty\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string SystemEx\&.Empty\&.ToString ()"

.PP
Definition at line \fB27\fP of file \fBEmpty\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly Empty SystemEx\&.Empty\&.None = new Empty()\fR [static]\fP"

.PP
Definition at line \fB23\fP of file \fBEmpty\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
