.TH "SystemEx.Collections.Generic.CluserIterrator< TElemet >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Collections.Generic.CluserIterrator< TElemet >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemEx\&.Collections\&.Generic\&.Iterrator< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCluserIterrator\fP (\fBICluster\fP< TElemet > cluster, long index, long end)"
.br
.ti -1c
.RI "void \fBForward\fP ()"
.br
.RI "Advances the iterator by one position\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Optional< \fBICluster\fP< TElemet > > \fBCurrent\fP\fR [get]\fP"
.br
.RI "Gets the element at the current iterator position\&. Returns an \fBOptional<T>\fP that may be empty if the iterator is out of range\&. "
.ti -1c
.RI "bool \fBHaveNext\fP\fR [get]\fP"
.br
.ti -1c
.RI "long \fBIndex\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the current index of the iterator\&. "
.ti -1c
.RI "bool \fBIsEnd\fP\fR [get]\fP"
.br
.RI "Gets a value indicating whether the iterator has reached the end of the sequence\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB43\fP of file \fBCluster\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "SystemEx\&.Collections\&.Generic\&.CluserIterrator< TElemet >\&.CluserIterrator (\fBICluster\fP< TElemet > cluster, long index, long end)"

.PP
Definition at line \fB56\fP of file \fBCluster\&.cs\fP\&.
.SS "void SystemEx\&.Collections\&.Generic\&.CluserIterrator< TElemet >\&.Forward ()"

.PP
Advances the iterator by one position\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.Iterrator< T >\fP\&.
.PP
Definition at line \fB63\fP of file \fBCluster\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Optional<\fBICluster\fP<TElemet> > SystemEx\&.Collections\&.Generic\&.CluserIterrator< TElemet >\&.Current\fR [get]\fP"

.PP
Gets the element at the current iterator position\&. Returns an \fBOptional<T>\fP that may be empty if the iterator is out of range\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.Iterrator< T >\fP\&.
.PP
Definition at line \fB54\fP of file \fBCluster\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.CluserIterrator< TElemet >\&.HaveNext\fR [get]\fP"

.PP
Definition at line \fB50\fP of file \fBCluster\&.cs\fP\&.
.SS "long SystemEx\&.Collections\&.Generic\&.CluserIterrator< TElemet >\&.Index\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the current index of the iterator\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.Iterrator< T >\fP\&.
.PP
Definition at line \fB52\fP of file \fBCluster\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.CluserIterrator< TElemet >\&.IsEnd\fR [get]\fP"

.PP
Gets a value indicating whether the iterator has reached the end of the sequence\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.Iterrator< T >\fP\&.
.PP
Definition at line \fB48\fP of file \fBCluster\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
