.TH "SystemEx.Device.Intertropt" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Device.Intertropt
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIDeviceSharedBackend\fP"
.br
.RI "Defines the low‑level backend interface used by \fRDeviceSharedBuffer\fP and related shared‑memory abstractions\&. 
.br
 A backend represents a hardware‑specific buffer implementation such as RAM, OpenCL, Vulkan, CUDA, or any custom device memory\&. 
.br
 Each backend is responsible for creating, writing, reading, and closing its own hardware buffer handle\&. "
.ti -1c
.RI "class \fBRamSharedBackend\fP"
.br
.RI "RAM‑based backend for shared device buffers\&. "
.ti -1c
.RI "struct \fBUnmanagedObject\fP"
.br
.RI "Represents a pinned unmanaged memory block used by \fBSystemEx\fP backends\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
