.TH "SystemEx.IO.Provider.IByteFormatSchema" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.IO.Provider.IByteFormatSchema \- A schema defines total size, header size, endianness and fixed field offsets\&. Implementations must be deterministic and contain no dynamic or computed layout\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystemEx\&.Drawing\&.ColorR10G10B10FormatSchema\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBEndian\fP \fBEndian\fP\fR [get]\fP"
.br
.RI "Gets the endianness used for all multi‑byte fields\&. "
.ti -1c
.RI "long \fBHeaderSize\fP\fR [get]\fP"
.br
.RI "Gets the size of the header portion in bytes\&. "
.ti -1c
.RI "Map< string, long > \fBOffsets\fP\fR [get]\fP"
.br
.RI "Gets a read‑only mapping of field names to their byte offsets\&. Offsets are relative to the start of the packed structure\&. "
.ti -1c
.RI "long \fBTotalSize\fP\fR [get]\fP"
.br
.RI "Gets the total number of bytes required to represent in its packed binary form\&. "
.in -1c
.SH "Detailed Description"
.PP 
A schema defines total size, header size, endianness and fixed field offsets\&. Implementations must be deterministic and contain no dynamic or computed layout\&. 
.PP
Definition at line \fB29\fP of file \fBIByteSerialize\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBEndian\fP SystemEx\&.IO\&.Provider\&.IByteFormatSchema\&.Endian\fR [get]\fP"

.PP
Gets the endianness used for all multi‑byte fields\&. 
.PP
Implemented in \fBSystemEx\&.Drawing\&.ColorR10G10B10FormatSchema\fP\&.
.PP
Definition at line \fB44\fP of file \fBIByteSerialize\&.cs\fP\&.
.SS "long SystemEx\&.IO\&.Provider\&.IByteFormatSchema\&.HeaderSize\fR [get]\fP"

.PP
Gets the size of the header portion in bytes\&. 
.PP
Implemented in \fBSystemEx\&.Drawing\&.ColorR10G10B10FormatSchema\fP\&.
.PP
Definition at line \fB39\fP of file \fBIByteSerialize\&.cs\fP\&.
.SS "Map<string, long> SystemEx\&.IO\&.Provider\&.IByteFormatSchema\&.Offsets\fR [get]\fP"

.PP
Gets a read‑only mapping of field names to their byte offsets\&. Offsets are relative to the start of the packed structure\&. 
.PP
Implemented in \fBSystemEx\&.Drawing\&.ColorR10G10B10FormatSchema\fP\&.
.PP
Definition at line \fB50\fP of file \fBIByteSerialize\&.cs\fP\&.
.SS "long SystemEx\&.IO\&.Provider\&.IByteFormatSchema\&.TotalSize\fR [get]\fP"

.PP
Gets the total number of bytes required to represent in its packed binary form\&. 
.PP
Implemented in \fBSystemEx\&.Drawing\&.ColorR10G10B10FormatSchema\fP\&.
.PP
Definition at line \fB34\fP of file \fBIByteSerialize\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
