.TH "SystemEx.Runtime.ModulePreloader" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Runtime.ModulePreloader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModulePreloader\fP (string path)"
.br
.ti -1c
.RI "\fBModulePreloader\fP (string path, Platform architecture)"
.br
.ti -1c
.RI "\fBModulePreloader\fP (string path, string systemPath, Platform architecture)"
.br
.ti -1c
.RI "\fBResult\fP \fBPreload\fP ()"
.br
.RI "Preloads all native modules from the specified directory and architecture subfolder\&. "
.ti -1c
.RI "void \fBUnload\fP (\fBModule\fP module)"
.br
.ti -1c
.RI "void \fBUnload\fP (string name)"
.br
.ti -1c
.RI "void \fBUnloadAll\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBIsNativeModule\fP (string file)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IReadOnlyList< \fBModule\fP > \fBModules\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBPath\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBModulePreloader\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Runtime\&.ModulePreloader\&.ModulePreloader (string path)"

.PP
Definition at line \fB31\fP of file \fBModulePreloader\&.cs\fP\&.
.SS "SystemEx\&.Runtime\&.ModulePreloader\&.ModulePreloader (string path, Platform architecture)"

.PP
Definition at line \fB36\fP of file \fBModulePreloader\&.cs\fP\&.
.SS "SystemEx\&.Runtime\&.ModulePreloader\&.ModulePreloader (string path, string systemPath, Platform architecture)"

.PP
Definition at line \fB43\fP of file \fBModulePreloader\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual bool SystemEx\&.Runtime\&.ModulePreloader\&.IsNativeModule (string file)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Definition at line \fB146\fP of file \fBModulePreloader\&.cs\fP\&.
.SS "\fBResult\fP SystemEx\&.Runtime\&.ModulePreloader\&.Preload ()"

.PP
Preloads all native modules from the specified directory and architecture subfolder\&. 
.PP
Definition at line \fB55\fP of file \fBModulePreloader\&.cs\fP\&.
.SS "void SystemEx\&.Runtime\&.ModulePreloader\&.Unload (\fBModule\fP module)"

.PP
Definition at line \fB104\fP of file \fBModulePreloader\&.cs\fP\&.
.SS "void SystemEx\&.Runtime\&.ModulePreloader\&.Unload (string name)"

.PP
Definition at line \fB115\fP of file \fBModulePreloader\&.cs\fP\&.
.SS "void SystemEx\&.Runtime\&.ModulePreloader\&.UnloadAll ()"

.PP
Definition at line \fB95\fP of file \fBModulePreloader\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "IReadOnlyList<\fBModule\fP> SystemEx\&.Runtime\&.ModulePreloader\&.Modules\fR [get]\fP"

.PP
Definition at line \fB29\fP of file \fBModulePreloader\&.cs\fP\&.
.SS "string SystemEx\&.Runtime\&.ModulePreloader\&.Path\fR [get]\fP"

.PP
Definition at line \fB27\fP of file \fBModulePreloader\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
