.TH "SystemEx.Rand.TimeBasedSeed" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Rand.TimeBasedSeed \- Provides a time‑based seed implementation using DateTime as the update source\&. The seed consists of multiple 32‑bit values derived from the current timestamp, system tick count, and optionally a GUID hash\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemEx\&.Rand\&.ISeed< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint[] \fBGetSeed\fP ()"
.br
.RI "Returns the underlying seed values as an array of 32‑bit unsigned integers\&. "
.ti -1c
.RI "\fBTimeBasedSeed\fP (int length=4)"
.br
.RI "Initializes a new \fBTimeBasedSeed\fP with the specified length\&. The seed is immediately populated using DateTime\&.UtcNow\&. "
.ti -1c
.RI "void \fBUpdate\fP (DateTime value)"
.br
.RI "Updates the seed using the specified DateTime value\&. The timestamp is split into two 32‑bit components, followed by the current system tick count\&. If the seed contains more than three values, an additional GUID‑based value is generated\&. "
.in -1c

Public Member Functions inherited from \fBSystemEx\&.Rand\&.ISeed< T >\fP
.in +1c
.ti -1c
.RI "void \fBUpdate\fP (T value)"
.br
.RI "Updates the internal seed state using the specified value\&. The exact behavior depends on the implementation and may include mutation, recomputation, or partial replacement of seed components\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBLength\fP\fR [get]\fP"
.br
.RI "Gets the number of 32‑bit values contained in the seed\&. "
.ti -1c
.RI "uint \fBthis[int index]\fP\fR [get, set]\fP"
.br
.RI "Provides indexed access to individual seed values\&. Both reading and writing are supported, allowing engines or mixing operations to modify specific seed components directly\&. "
.in -1c

Properties inherited from \fBSystemEx\&.Rand\&.ISeed\fP
.in +1c
.ti -1c
.RI "uint \fBthis[int i]\fP\fR [get, set]\fP"
.br
.RI "Provides indexed access to individual seed values\&. Both reading and writing are supported, allowing engines or mixing operations to modify specific seed components directly\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides a time‑based seed implementation using DateTime as the update source\&. The seed consists of multiple 32‑bit values derived from the current timestamp, system tick count, and optionally a GUID hash\&. 
.PP
Definition at line \fB26\fP of file \fBTimeBasedSeed\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Rand\&.TimeBasedSeed\&.TimeBasedSeed (int length = \fR4\fP)"

.PP
Initializes a new \fBTimeBasedSeed\fP with the specified length\&. The seed is immediately populated using DateTime\&.UtcNow\&. 
.PP
\fBParameters\fP
.RS 4
\fIlength\fP The desired number of seed values\&. A minimum of three values is enforced\&. 
.RE
.PP

.PP
Definition at line \fB49\fP of file \fBTimeBasedSeed\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "uint[] SystemEx\&.Rand\&.TimeBasedSeed\&.GetSeed ()"

.PP
Returns the underlying seed values as an array of 32‑bit unsigned integers\&. 
.PP
\fBReturns\fP
.RS 4
A uint array containing the current seed values\&. 
.RE
.PP

.PP
Implements \fBSystemEx\&.Rand\&.ISeed\fP\&.
.PP
Definition at line \fB59\fP of file \fBTimeBasedSeed\&.cs\fP\&.
.SS "void SystemEx\&.Rand\&.TimeBasedSeed\&.Update (DateTime value)"

.PP
Updates the seed using the specified DateTime value\&. The timestamp is split into two 32‑bit components, followed by the current system tick count\&. If the seed contains more than three values, an additional GUID‑based value is generated\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The DateTime instance used to refresh the seed\&. 
.RE
.PP

.PP
Definition at line \fB69\fP of file \fBTimeBasedSeed\&.cs\fP\&.
.PP
Referenced by \fBTimeBasedSeed()\fP\&.
.SH "Property Documentation"
.PP 
.SS "int SystemEx\&.Rand\&.TimeBasedSeed\&.Length\fR [get]\fP"

.PP
Gets the number of 32‑bit values contained in the seed\&. 
.PP
Implements \fBSystemEx\&.Rand\&.ISeed\fP\&.
.PP
Definition at line \fB31\fP of file \fBTimeBasedSeed\&.cs\fP\&.
.SS "uint SystemEx\&.Rand\&.TimeBasedSeed\&.this[int index]\fR [get]\fP, \fR [set]\fP"

.PP
Provides indexed access to individual seed values\&. Both reading and writing are supported, allowing engines or mixing operations to modify specific seed components directly\&. 
.PP
\fBParameters\fP
.RS 4
\fIindex\fP The zero‑based index of the seed value\&.
.RE
.PP

.PP
Definition at line \fB38\fP of file \fBTimeBasedSeed\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
