.TH "SystemEx.Hash.FletcherHash" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Hash.FletcherHash \- Implements the Fletcher hash algorithm\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemEx\&.Hash\&.IHash\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHash32\fP \fBCompute\fP (FixedVector< byte > input, uint seed)"
.br
.RI "Computes the Fletcher hash of the given input\&. "
.ti -1c
.RI "\fBHash64\fP \fBComputeLong\fP (FixedVector< byte > input, ulong seed)"
.br
.RI "Computes the Fletcher hash of the given input\&. "
.ti -1c
.RI "\fBFletcherHash\fP (\fBEndian\fP endian)"
.br
.RI "Craate a new instance\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implements the Fletcher hash algorithm\&. 
.PP
Definition at line \fB29\fP of file \fBFletcherHash\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Hash\&.FletcherHash\&.FletcherHash (\fBEndian\fP endian)"

.PP
Craate a new instance\&. 
.PP
\fBParameters\fP
.RS 4
\fIendian\fP The suing endian for creating a hash
.RE
.PP

.PP
Definition at line \fB35\fP of file \fBFletcherHash\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBHash32\fP SystemEx\&.Hash\&.FletcherHash\&.Compute (FixedVector< byte > input, uint seed)"

.PP
Computes the Fletcher hash of the given input\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP The input data to hash\&.
.br
\fIseed\fP The seed value for the hash computation\&.
.RE
.PP
\fBReturns\fP
.RS 4
The computed Fletcher hash as a \fBHash32\fP object\&.
.RE
.PP

.PP
Implements \fBSystemEx\&.Hash\&.IHash\fP\&.
.PP
Definition at line \fB44\fP of file \fBFletcherHash\&.cs\fP\&.
.PP
Referenced by \fBComputeLong()\fP\&.
.SS "\fBHash64\fP SystemEx\&.Hash\&.FletcherHash\&.ComputeLong (FixedVector< byte > input, ulong seed)"

.PP
Computes the Fletcher hash of the given input\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP The input data to hash\&.
.br
\fIseed\fP The seed value for the hash computation\&.
.RE
.PP
\fBReturns\fP
.RS 4
The computed Fletcher hash as a \fBHash64\fP object\&.
.RE
.PP

.PP
Implements \fBSystemEx\&.Hash\&.IHash\fP\&.
.PP
Definition at line \fB70\fP of file \fBFletcherHash\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
