.TH "SystemEx.Numeric.IFP8< TSelf >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Numeric.IFP8< TSelf > \- Defines an 8‑bit floating‑point format based on \fBIFloat<TSelf, TBias>\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemEx\&.Numeric\&.IFP8\fP, and \fBSystemEx\&.Numeric\&.IFloat< TSelf, TBias >\fP\&.
.PP
Inherited by \fBSystemEx\&.Numeric\&.FloatE4M3\fP, \fBSystemEx\&.Numeric\&.FloatE5M2\fP, \fBSystemEx\&.Numeric\&.FloatUE4M3\fP, and \fBSystemEx\&.Numeric\&.FloatUE5M2\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static TSelf \fBFromComponent\fP (\fBFast_Byte\fP sign, \fBFast_Byte\fP mantissa, \fBFast_Byte\fP expotent)"
.br
.in -1c

Static Public Member Functions inherited from \fBSystemEx\&.Numeric\&.IFloat< TSelf, TBias >\fP
.in +1c
.ti -1c
.RI "static TSelf \fBAbs\fP (TSelf value)"
.br
.RI "Returns the absolute value of the given floating‑point number\&. "
.ti -1c
.RI "static TSelf \fBAdd\fP (TSelf a, TSelf b)"
.br
.RI "Adds two floating‑point values\&. "
.ti -1c
.RI "static TSelf \fBCeil\fP (TSelf value)"
.br
.RI "Returns the smallest integer greater than or equal to the value\&. "
.ti -1c
.RI "static TSelf \fBClamp\fP (TSelf x, TSelf min, TSelf max)"
.br
.RI "Clamps the value to the inclusive range [min, max]\&. "
.ti -1c
.RI "static TSelf \fBDiv\fP (TSelf a, TSelf b)"
.br
.RI "Divides one floating‑point value by another\&. "
.ti -1c
.RI "static TSelf \fBFloor\fP (TSelf value)"
.br
.RI "Returns the largest integer less than or equal to the value\&. "
.ti -1c
.RI "static bool \fBIsFinite\fP (TSelf value)"
.br
.RI "Determines whether the value is finite (not NaN or infinity)\&. "
.ti -1c
.RI "static bool \fBIsInfinity\fP (TSelf value)"
.br
.RI "Determines whether the value is positive or negative infinity\&. "
.ti -1c
.RI "static bool \fBIsInteger\fP (TSelf value)"
.br
.RI "Determines whether the value represents an integer (mantissa zero)\&. "
.ti -1c
.RI "static bool \fBIsNaN\fP (TSelf value)"
.br
.RI "Determines whether the value is a NaN (not‑a‑number)\&. "
.ti -1c
.RI "static bool \fBIsNegative\fP (TSelf value)"
.br
.RI "Determines whether the value is negative\&. "
.ti -1c
.RI "static bool \fBIsNormal\fP (TSelf value)"
.br
.RI "Determines whether the value is a normalized floating‑point number\&. "
.ti -1c
.RI "static bool \fBIsSubnormal\fP (TSelf value)"
.br
.RI "Determines whether the value is subnormal (exponent field zero but mantissa non‑zero)\&. "
.ti -1c
.RI "static bool \fBIsZero\fP (TSelf value)"
.br
.RI "Determines whether the value is zero (positive or negative)\&. "
.ti -1c
.RI "static TSelf \fBMax\fP (TSelf a, TSelf b)"
.br
.RI "Returns the larger of two floating‑point values\&. "
.ti -1c
.RI "static TSelf \fBMin\fP (TSelf a, TSelf b)"
.br
.RI "Returns the smaller of two floating‑point values\&. "
.ti -1c
.RI "static TSelf \fBMul\fP (TSelf a, TSelf b)"
.br
.RI "Multiplies two floating‑point values\&. "
.ti -1c
.RI "static TSelf \fBNegate\fP (TSelf value)"
.br
.RI "Returns the negation of the given floating‑point number\&. "
.ti -1c
.RI "static bool \fBoperator!=\fP (TSelf a, TSelf b)"
.br
.RI "Determines whether two floating‑point values are not equal\&. "
.ti -1c
.RI "static bool \fBoperator<\fP (TSelf a, TSelf b)"
.br
.RI "Determines whether \fIa\fP  is strictly less than \fIb\fP \&. "
.ti -1c
.RI "static bool \fBoperator<=\fP (TSelf a, TSelf b)"
.br
.RI "Determines whether \fIa\fP  is less than or equal to \fIb\fP \&. "
.ti -1c
.RI "static bool \fBoperator==\fP (TSelf a, TSelf b)"
.br
.RI "Determines whether two floating‑point values are equal\&. "
.ti -1c
.RI "static bool \fBoperator>\fP (TSelf a, TSelf b)"
.br
.RI "Determines whether \fIa\fP  is strictly greater than \fIb\fP \&. "
.ti -1c
.RI "static bool \fBoperator>=\fP (TSelf a, TSelf b)"
.br
.RI "Determines whether \fIa\fP  is greater than or equal to \fIb\fP \&. "
.ti -1c
.RI "static TSelf \fBSignum\fP (TSelf value)"
.br
.RI "Returns the sign of the value: −1, 0, or +1\&. "
.ti -1c
.RI "static TSelf \fBTrunc\fP (TSelf value)"
.br
.RI "Truncates the fractional part of the value\&. "
.in -1c

Static Public Member Functions inherited from \fBSystemEx\&.IByteSerializable< TSelf >\fP
.in +1c
.ti -1c
.RI "static TSelf \fBFromBytes\fP (byte[] bytes, long offset, \fBEndian\fP endian)"
.br
.RI "Creates an instance of \fITSelf\fP  from a byte array\&. The method reads the encoded representation starting at the specified \fIoffset\fP  using the given \fIendian\fP  order\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static bool \fBIsMXSupport\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBSystemEx\&.Numeric\&.IFloat< TBias >\fP
.in +1c
.ti -1c
.RI "TBias \fBExponent\fP\fR [get]\fP"
.br
.RI "Gets the exponent field as stored in the encoded representation\&. "
.ti -1c
.RI "TBias \fBExponentBias\fP\fR [get]\fP"
.br
.RI "Exponent bias applied to the exponent field\&. Defines the offset used when converting between encoded exponent and real exponent\&. "
.ti -1c
.RI "TBias \fBExponentBits\fP\fR [get]\fP"
.br
.RI "Number of bits used for the exponent field\&. "
.ti -1c
.RI "TBias \fBHiddenBit\fP\fR [get]\fP"
.br
.RI "Gets the hidden bit (implicit leading mantissa bit)\&. For IEEE‑like formats this is typically \fR1\fP for normalized numbers and \fR0\fP for subnormals\&. "
.ti -1c
.RI "TBias \fBMantissa\fP\fR [get]\fP"
.br
.RI "Gets the mantissa (fraction) field as stored in the encoded representation\&. "
.ti -1c
.RI "TBias \fBMantissaBits\fP\fR [get]\fP"
.br
.RI "Number of bits used for the mantissa (fraction) field\&. "
.ti -1c
.RI "bool \fBSign\fP\fR [get]\fP"
.br
.RI "Gets the sign bit\&. \fRtrue\fP indicates a negative value\&. "
.ti -1c
.RI "TBias \fBSignBits\fP\fR [get]\fP"
.br
.RI "Number of bits used for the sign field\&. "
.ti -1c
.RI "TBias \fBToBase\fP\fR [get]\fP"
.br
.RI "Gets the underlying raw storage type used for bit extraction\&. Implementations typically return \fRushort\fP or \fRuint\fP depending on the float width\&. "
.ti -1c
.RI "TBias \fBTotalBits\fP\fR [get]\fP"
.br
.RI "Total number of bits in the floating‑point representation\&. "
.in -1c

Properties inherited from \fBSystemEx\&.Numeric\&.IFloat< TSelf, TBias >\fP
.in +1c
.ti -1c
.RI "static TSelf \fBE\fP\fR [get]\fP"
.br
.RI "Represents Euler’s number \fRe\fP\&. "
.ti -1c
.RI "static TSelf \fBEpsilon\fP\fR [get]\fP"
.br
.RI "Represents the smallest positive increment representable by the format\&. "
.ti -1c
.RI "static TSelf \fBMaxValue\fP\fR [get]\fP"
.br
.RI "Largest representable positive value\&. "
.ti -1c
.RI "static TSelf \fBMinValue\fP\fR [get]\fP"
.br
.RI "Smallest representable negative value\&. "
.ti -1c
.RI "static TSelf \fBNaN\fP\fR [get]\fP"
.br
.RI "Represents a quiet NaN value\&. "
.ti -1c
.RI "static TSelf \fBNaN2\fP\fR [get]\fP"
.br
.RI "Represents an alternative NaN encoding (implementation‑specific)\&. "
.ti -1c
.RI "static TSelf \fBNegativeInfinity\fP\fR [get]\fP"
.br
.RI "Represents negative infinity\&. "
.ti -1c
.RI "static TSelf \fBNegativeOne\fP\fR [get]\fP"
.br
.RI "Represents the floating‑point value negative one\&. "
.ti -1c
.RI "static TSelf \fBNegativeZero\fP\fR [get]\fP"
.br
.RI "Represents negative zero (sign bit set, exponent and mantissa zero)\&. "
.ti -1c
.RI "static TSelf \fBOne\fP\fR [get]\fP"
.br
.RI "Represents the floating‑point value one\&. "
.ti -1c
.RI "static TSelf \fBPi\fP\fR [get]\fP"
.br
.RI "Represents π\&. "
.ti -1c
.RI "static TSelf \fBPositiveInfinity\fP\fR [get]\fP"
.br
.RI "Represents positive infinity\&. "
.ti -1c
.RI "static TSelf \fBTau\fP\fR [get]\fP"
.br
.RI "Represents τ = 2π\&. "
.ti -1c
.RI "static TSelf \fBZero\fP\fR [get]\fP"
.br
.RI "Represents the floating‑point value zero\&. "
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBSystemEx\&.IComparableEx< T >\fP
.in +1c
.ti -1c
.RI "\fBCompareResult\fP \fBCompareTo\fP (T a)"
.br
.RI "Compares this instance with the specified value and returns a \fBCompareResult\fP describing the relationship between them\&. "
.in -1c

Public Member Functions inherited from \fBSystemEx\&.Hash\&.IHashable< T >\fP
.in +1c
.ti -1c
.RI "FixedVector< byte > \fBToBytes\fP ()"
.br
.RI "Converts this instance into a deterministic byte array\&. The returned data is used as input for hashing algorithms\&. "
.in -1c

Public Member Functions inherited from \fBSystemEx\&.IByteSerializable< TSelf >\fP
.in +1c
.ti -1c
.RI "byte[] \fBToBytes\fP (\fBEndian\fP endian)"
.br
.RI "Encodes the current instance into a newly allocated byte array using the specified \fIendian\fP  order\&. "
.ti -1c
.RI "void \fBToBytes\fP (ref byte[] destination, long offset, \fBEndian\fP endian)"
.br
.RI "Writes the binary representation of the current instance into an existing \fIdestination\fP  buffer at the specified \fIoffset\fP \&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines an 8‑bit floating‑point format based on \fBIFloat<TSelf, TBias>\fP\&. 

\fBIFP8<TSelf>\fP is intended for extremely compact numeric representations such as FP8 variants used in machine learning or embedded systems\&. The exact bit layout (sign, exponent, mantissa) is determined by the \fBIFloat<TSelf, TBias>\fP implementation\&. 
.PP
\fBType Constraints\fP
.TP
\fITSelf\fP : \fIstruct\fP
.TP
\fITSelf\fP : \fI\fBIFP8\fP<TSelf>\fP
.PP
Definition at line \fB32\fP of file \fBIFP8\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool \fBSystemEx\&.Numeric\&.IFP8\fP< TSelf >\&.IsMXSupport\fR [static]\fP, \fR [get]\fP, \fR [abstract]\fP"

.PP
Implemented in \fBSystemEx\&.Numeric\&.FloatUE4M3\fP, and \fBSystemEx\&.Numeric\&.FloatUE5M2\fP\&.
.PP
Definition at line \fB34\fP of file \fBIFP8\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
