.TH "SystemEx.Drawing.ColorR10G10B10A2" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Drawing.ColorR10G10B10A2 \- Represents a 10‑bit per channel RGB color (R10G10B10A2), stored internally as normalized floating‑point values (0–1)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IEquatable, and \fBSystemEx\&.IO\&.Provider\&.IIsByteSeriablize\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorR10G10B10A2\fP (float r, float g, float b)"
.br
.RI "Creates a new R10G10B10A2 color from normalized float values (0–1)\&. "
.ti -1c
.RI "\fBColorR10G10B10A2\fP (float r, float g, float b, float a)"
.br
.RI "Initializes a new R10G10B10A2 color from normalized float values (0–1)\&. "
.ti -1c
.RI "\fBColorR10G10B10A2\fP (ushort r10, ushort g10, ushort b10, ushort a10)"
.br
.RI "Initializes a new R10G10B10A2 color from 10‑bit UNORM components (0–1023)\&. "
.ti -1c
.RI "bool \fBEquals\fP (\fBColorR10G10B10A2\fP other)"
.br
.RI "Determines whether this instance is equal to another R10G10B10A2 color\&. "
.ti -1c
.RI "override bool \fBEquals\fP (object? obj)"
.br
.RI "Determines whether this instance is equal to another object\&. "
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.RI "Returns a hash code based on the R, G, and B components\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a string representation of the R10G10B10A2 color\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const float \fBCOLORINV\fP = 1f / 1023f"
.br
.RI "Gets the inverse of the color component range\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBA\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the alpha component\&. "
.ti -1c
.RI "float \fBB\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the blue component\&. "
.ti -1c
.RI "float \fBG\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the green component\&. "
.ti -1c
.RI "float \fBR\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the red component\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a 10‑bit per channel RGB color (R10G10B10A2), stored internally as normalized floating‑point values (0–1)\&. 
.PP
Definition at line \fB146\fP of file \fBColorR10G10B10\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Drawing\&.ColorR10G10B10A2\&.ColorR10G10B10A2 (float r, float g, float b)"

.PP
Creates a new R10G10B10A2 color from normalized float values (0–1)\&. 
.PP
\fBParameters\fP
.RS 4
\fIr\fP The red component (0–1)\&.
.br
\fIg\fP The green component (0–1)\&.
.br
\fIb\fP The blue component (0–1)\&.
.RE
.PP

.PP
Definition at line \fB175\fP of file \fBColorR10G10B10\&.cs\fP\&.
.PP
Referenced by \fBEquals()\fP, and \fBEquals()\fP\&.
.SS "SystemEx\&.Drawing\&.ColorR10G10B10A2\&.ColorR10G10B10A2 (float r, float g, float b, float a)"

.PP
Initializes a new R10G10B10A2 color from normalized float values (0–1)\&. 
.PP
Definition at line \fB179\fP of file \fBColorR10G10B10\&.cs\fP\&.
.SS "SystemEx\&.Drawing\&.ColorR10G10B10A2\&.ColorR10G10B10A2 (ushort r10, ushort g10, ushort b10, ushort a10)"

.PP
Initializes a new R10G10B10A2 color from 10‑bit UNORM components (0–1023)\&. 
.PP
\fBParameters\fP
.RS 4
\fIr10\fP The red component (0–1023)\&.
.br
\fIg10\fP The green component (0–1023)\&.
.br
\fIb10\fP The blue component (0–1023)\&.
.br
\fIa10\fP The alpha component (0–3)\&.
.RE
.PP

.PP
Definition at line \fB193\fP of file \fBColorR10G10B10\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SystemEx\&.Drawing\&.ColorR10G10B10A2\&.Equals (\fBColorR10G10B10A2\fP other)"

.PP
Determines whether this instance is equal to another R10G10B10A2 color\&. 
.PP
Definition at line \fB204\fP of file \fBColorR10G10B10\&.cs\fP\&.
.PP
Referenced by \fBEquals()\fP\&.
.SS "override bool SystemEx\&.Drawing\&.ColorR10G10B10A2\&.Equals (object? obj)"

.PP
Determines whether this instance is equal to another object\&. 
.PP
Definition at line \fB215\fP of file \fBColorR10G10B10\&.cs\fP\&.
.SS "override int SystemEx\&.Drawing\&.ColorR10G10B10A2\&.GetHashCode ()"

.PP
Returns a hash code based on the R, G, and B components\&. 
.PP
Definition at line \fB225\fP of file \fBColorR10G10B10\&.cs\fP\&.
.SS "override string SystemEx\&.Drawing\&.ColorR10G10B10A2\&.ToString ()"

.PP
Returns a string representation of the R10G10B10A2 color\&. 
.PP
Definition at line \fB232\fP of file \fBColorR10G10B10\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const float SystemEx\&.Drawing\&.ColorR10G10B10A2\&.COLORINV = 1f / 1023f\fR [static]\fP"

.PP
Gets the inverse of the color component range\&. 
.PP
Definition at line \fB155\fP of file \fBColorR10G10B10\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "float SystemEx\&.Drawing\&.ColorR10G10B10A2\&.A\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the alpha component\&. 
.PP
Definition at line \fB167\fP of file \fBColorR10G10B10\&.cs\fP\&.
.PP
Referenced by \fBColorR10G10B10A2()\fP, and \fBColorR10G10B10A2()\fP\&.
.SS "float SystemEx\&.Drawing\&.ColorR10G10B10A2\&.B\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the blue component\&. 
.PP
Definition at line \fB165\fP of file \fBColorR10G10B10\&.cs\fP\&.
.PP
Referenced by \fBColorR10G10B10A2()\fP, and \fBColorR10G10B10A2()\fP\&.
.SS "float SystemEx\&.Drawing\&.ColorR10G10B10A2\&.G\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the green component\&. 
.PP
Definition at line \fB162\fP of file \fBColorR10G10B10\&.cs\fP\&.
.PP
Referenced by \fBColorR10G10B10A2()\fP, and \fBColorR10G10B10A2()\fP\&.
.SS "float SystemEx\&.Drawing\&.ColorR10G10B10A2\&.R\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the red component\&. 
.PP
Definition at line \fB159\fP of file \fBColorR10G10B10\&.cs\fP\&.
.PP
Referenced by \fBColorR10G10B10A2()\fP, and \fBColorR10G10B10A2()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
