.TH "SystemEx.Runtime.Backend.Loader" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Runtime.Backend.Loader
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIPreloaderBackend\fP"
.br
.ti -1c
.RI "interface \fBIPreloaderBackendConfig\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
