.TH "SystemEx.Drawing.PurpelColors" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Drawing.PurpelColors \- Purpel Color Group\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBBlueViolet\fP\fR [get]\fP"
.br
.RI "BlueViolet #8A2BE2\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBDarkMagenta\fP\fR [get]\fP"
.br
.RI "DarkMagenta #8B008B\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBDarkOrchid\fP\fR [get]\fP"
.br
.RI "DarkOrchid #9932CC\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBDarkSlateBlue\fP\fR [get]\fP"
.br
.RI "DarkSlateBlue #483D8B\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBDarkViolet\fP\fR [get]\fP"
.br
.RI "DarkViolet #9400D3\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBFuchsia\fP\fR [get]\fP"
.br
.RI "Fuchsia #FF00FF\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBIndigo\fP\fR [get]\fP"
.br
.RI "Indigo #4B0082\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBLavender\fP\fR [get]\fP"
.br
.RI "Lavender #E6E6FA\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBMagenta\fP\fR [get]\fP"
.br
.RI "Magenta #FF00FF\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBMediumOrchid\fP\fR [get]\fP"
.br
.RI "MediumOrchid #BA55D3\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBMediumPurple\fP\fR [get]\fP"
.br
.RI "MediumPurple #9370DB\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBMediumSlateBlue\fP\fR [get]\fP"
.br
.RI "MediumSlateBlue #7B68EE\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBOrchid\fP\fR [get]\fP"
.br
.RI "Orchid #DA70D6\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBPlum\fP\fR [get]\fP"
.br
.RI "Plum #DDA0DD\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBPurple\fP\fR [get]\fP"
.br
.RI "Purple #800080\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBRebeccaPurple\fP\fR [get]\fP"
.br
.RI "RebeccaPurple #663399\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBSlateBlue\fP\fR [get]\fP"
.br
.RI "SlateBlue #6A5ACD\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBThistle\fP\fR [get]\fP"
.br
.RI "Thistle #D8BFD8\&. "
.ti -1c
.RI "static \fBColorR8G8B8\fP \fBViolet\fP\fR [get]\fP"
.br
.RI "Violet #EE82EE\&. "
.in -1c
.SH "Detailed Description"
.PP 
Purpel Color Group\&. 
.PP
Definition at line \fB120\fP of file \fBColors\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.BlueViolet\fR [static]\fP, \fR [get]\fP"

.PP
BlueViolet #8A2BE2\&. 
.PP
Definition at line \fB142\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.DarkMagenta\fR [static]\fP, \fR [get]\fP"

.PP
DarkMagenta #8B008B\&. 
.PP
Definition at line \fB144\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.DarkOrchid\fR [static]\fP, \fR [get]\fP"

.PP
DarkOrchid #9932CC\&. 
.PP
Definition at line \fB138\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.DarkSlateBlue\fR [static]\fP, \fR [get]\fP"

.PP
DarkSlateBlue #483D8B\&. 
.PP
Definition at line \fB154\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.DarkViolet\fR [static]\fP, \fR [get]\fP"

.PP
DarkViolet #9400D3\&. 
.PP
Definition at line \fB140\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.Fuchsia\fR [static]\fP, \fR [get]\fP"

.PP
Fuchsia #FF00FF\&. 
.PP
Definition at line \fB132\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.Indigo\fR [static]\fP, \fR [get]\fP"

.PP
Indigo #4B0082\&. 
.PP
Definition at line \fB158\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.Lavender\fR [static]\fP, \fR [get]\fP"

.PP
Lavender #E6E6FA\&. 
.PP
Definition at line \fB122\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.Magenta\fR [static]\fP, \fR [get]\fP"

.PP
Magenta #FF00FF\&. 
.PP
Definition at line \fB134\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.MediumOrchid\fR [static]\fP, \fR [get]\fP"

.PP
MediumOrchid #BA55D3\&. 
.PP
Definition at line \fB136\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.MediumPurple\fR [static]\fP, \fR [get]\fP"

.PP
MediumPurple #9370DB\&. 
.PP
Definition at line \fB148\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.MediumSlateBlue\fR [static]\fP, \fR [get]\fP"

.PP
MediumSlateBlue #7B68EE\&. 
.PP
Definition at line \fB150\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.Orchid\fR [static]\fP, \fR [get]\fP"

.PP
Orchid #DA70D6\&. 
.PP
Definition at line \fB128\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.Plum\fR [static]\fP, \fR [get]\fP"

.PP
Plum #DDA0DD\&. 
.PP
Definition at line \fB126\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.Purple\fR [static]\fP, \fR [get]\fP"

.PP
Purple #800080\&. 
.PP
Definition at line \fB146\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.RebeccaPurple\fR [static]\fP, \fR [get]\fP"

.PP
RebeccaPurple #663399\&. 
.PP
Definition at line \fB156\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.SlateBlue\fR [static]\fP, \fR [get]\fP"

.PP
SlateBlue #6A5ACD\&. 
.PP
Definition at line \fB152\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.Thistle\fR [static]\fP, \fR [get]\fP"

.PP
Thistle #D8BFD8\&. 
.PP
Definition at line \fB124\fP of file \fBColors\&.cs\fP\&.
.SS "\fBColorR8G8B8\fP SystemEx\&.Drawing\&.PurpelColors\&.Violet\fR [static]\fP, \fR [get]\fP"

.PP
Violet #EE82EE\&. 
.PP
Definition at line \fB130\fP of file \fBColors\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
