.TH "SystemEx.Collections.Generic.StackLayer" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Collections.Generic.StackLayer \- Represents a logical sub‑stack inside a shared stack buffer\&. A layer defines its own independent boundaries and a current pointer, allowing multiple virtual stacks to coexist within the same array\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStackLayer\fP (int end, int start, int c)"
.br
.RI "Creates a new stack layer with the specified boundaries and current pointer\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCurrent\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the current index of the layer's top element\&. "
.ti -1c
.RI "bool \fBEnable\fP\fR [get, set]\fP"
.br
.RI "Indicates whether this layer is active and allowed to perform push/pop operations\&. "
.ti -1c
.RI "int \fBEndMarker\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the lower boundary (inclusive) of the layer\&. This is the point where the layer becomes full\&. "
.ti -1c
.RI "int \fBStartMarker\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the upper boundary (exclusive) of the layer\&. This is the point where the layer becomes empty\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a logical sub‑stack inside a shared stack buffer\&. A layer defines its own independent boundaries and a current pointer, allowing multiple virtual stacks to coexist within the same array\&. 
.PP
Definition at line \fB26\fP of file \fBStack\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Collections\&.Generic\&.StackLayer\&.StackLayer (int end, int start, int c)"

.PP
Creates a new stack layer with the specified boundaries and current pointer\&. 
.PP
\fBParameters\fP
.RS 4
\fIend\fP The lower boundary of the layer\&.
.br
\fIstart\fP The upper boundary of the layer\&.
.br
\fIc\fP The initial current pointer\&.
.RE
.PP

.PP
Definition at line \fB55\fP of file \fBStack\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int SystemEx\&.Collections\&.Generic\&.StackLayer\&.Current\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the current index of the layer's top element\&. 
.PP
Definition at line \fB42\fP of file \fBStack\&.cs\fP\&.
.PP
Referenced by \fBStackLayer()\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.StackLayer\&.Enable\fR [get]\fP, \fR [set]\fP"

.PP
Indicates whether this layer is active and allowed to perform push/pop operations\&. 
.PP
Definition at line \fB47\fP of file \fBStack\&.cs\fP\&.
.PP
Referenced by \fBStackLayer()\fP\&.
.SS "int SystemEx\&.Collections\&.Generic\&.StackLayer\&.EndMarker\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the lower boundary (inclusive) of the layer\&. This is the point where the layer becomes full\&. 
.PP
Definition at line \fB31\fP of file \fBStack\&.cs\fP\&.
.PP
Referenced by \fBStackLayer()\fP\&.
.SS "int SystemEx\&.Collections\&.Generic\&.StackLayer\&.StartMarker\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the upper boundary (exclusive) of the layer\&. This is the point where the layer becomes empty\&. 
.PP
Definition at line \fB37\fP of file \fBStack\&.cs\fP\&.
.PP
Referenced by \fBStackLayer()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
