.TH "SystemEx.NoCopyable" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.NoCopyable \- \fBBase\fP class that strictly forbids any form of copying\&. Pedantisch safe: no cloning, no copy constructor, no MemberwiseClone\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystemEx\&.Threading\&.Barrier\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBClone\fP ()"
.br
.RI "Pedantisch safe: cloning is forbidden\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "new object \fBMemberwiseClone\fP ()"
.br
.RI "Pedantisch safe: MemberwiseClone is blocked\&. "
.ti -1c
.RI "\fBNoCopyable\fP ()"
.br
.RI "Protected default constructor\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBBase\fP class that strictly forbids any form of copying\&. Pedantisch safe: no cloning, no copy constructor, no MemberwiseClone\&. 
.PP
Definition at line \fB27\fP of file \fBNoCopyable\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.NoCopyable\&.NoCopyable ()\fR [protected]\fP"

.PP
Protected default constructor\&. 
.PP
Definition at line \fB39\fP of file \fBNoCopyable\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "object SystemEx\&.NoCopyable\&.Clone ()"

.PP
Pedantisch safe: cloning is forbidden\&. 
.PP
Definition at line \fB45\fP of file \fBNoCopyable\&.cs\fP\&.
.SS "new object SystemEx\&.NoCopyable\&.MemberwiseClone ()\fR [protected]\fP"

.PP
Pedantisch safe: MemberwiseClone is blocked\&. 
.PP
Definition at line \fB51\fP of file \fBNoCopyable\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
