.TH "SystemEx.Drawing.ColorR10G10B10FormatSchema" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Drawing.ColorR10G10B10FormatSchema \- A Scbema is used to serialize and deserialize a \fBColorR10G10B10A2\fP color to and from a binary representation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemEx\&.IO\&.Provider\&.IByteFormatSchema\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorR10G10B10FormatSchema\fP (\fBEndian\fP endian)"
.br
.RI "Initializes a new instance of the \fBColorR10G10B10FormatSchema\fP class with the specified endianness\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBEndian\fP \fBEndian\fP\fR [get]\fP"
.br
.RI "The endianness used for all multi‑byte fields\&. This is specified when creating the schema\&. "
.ti -1c
.RI "long \fBHeaderSize\fP\fR [get]\fP"
.br
.RI "The size of the header portion in bytes\&. For \fBColorR10G10B10A2\fP, there is no header, so this is 0\&. "
.ti -1c
.RI "Map< string, long > \fBOffsets\fP\fR [get]\fP"
.br
.RI "A read‑only mapping of field names to their byte offsets\&. For \fBColorR10G10B10A2\fP, there is only one field named "DEFAULT" at offset 0\&. "
.ti -1c
.RI "long \fBTotalSize\fP\fR [get]\fP"
.br
.RI "The total number of bytes required to represent a \fBColorR10G10B10A2\fP color in its packed binary form\&. "
.in -1c
.SH "Detailed Description"
.PP 
A Scbema is used to serialize and deserialize a \fBColorR10G10B10A2\fP color to and from a binary representation\&. 
.PP
Definition at line \fB26\fP of file \fBColorR10G10B10\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Drawing\&.ColorR10G10B10FormatSchema\&.ColorR10G10B10FormatSchema (\fBEndian\fP endian)"

.PP
Initializes a new instance of the \fBColorR10G10B10FormatSchema\fP class with the specified endianness\&. 
.PP
\fBParameters\fP
.RS 4
\fIendian\fP 
.RE
.PP

.PP
Definition at line \fB52\fP of file \fBColorR10G10B10\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBEndian\fP SystemEx\&.Drawing\&.ColorR10G10B10FormatSchema\&.Endian\fR [get]\fP"

.PP
The endianness used for all multi‑byte fields\&. This is specified when creating the schema\&. 
.PP
Implements \fBSystemEx\&.IO\&.Provider\&.IByteFormatSchema\fP\&.
.PP
Definition at line \fB39\fP of file \fBColorR10G10B10\&.cs\fP\&.
.PP
Referenced by \fBColorR10G10B10FormatSchema()\fP\&.
.SS "long SystemEx\&.Drawing\&.ColorR10G10B10FormatSchema\&.HeaderSize\fR [get]\fP"

.PP
The size of the header portion in bytes\&. For \fBColorR10G10B10A2\fP, there is no header, so this is 0\&. 
.PP
Implements \fBSystemEx\&.IO\&.Provider\&.IByteFormatSchema\fP\&.
.PP
Definition at line \fB35\fP of file \fBColorR10G10B10\&.cs\fP\&.
.SS "Map<string, long> SystemEx\&.Drawing\&.ColorR10G10B10FormatSchema\&.Offsets\fR [get]\fP"

.PP
A read‑only mapping of field names to their byte offsets\&. For \fBColorR10G10B10A2\fP, there is only one field named "DEFAULT" at offset 0\&. 
.PP
Implements \fBSystemEx\&.IO\&.Provider\&.IByteFormatSchema\fP\&.
.PP
Definition at line \fB45\fP of file \fBColorR10G10B10\&.cs\fP\&.
.PP
Referenced by \fBColorR10G10B10FormatSchema()\fP\&.
.SS "long SystemEx\&.Drawing\&.ColorR10G10B10FormatSchema\&.TotalSize\fR [get]\fP"

.PP
The total number of bytes required to represent a \fBColorR10G10B10A2\fP color in its packed binary form\&. 
.PP
Implements \fBSystemEx\&.IO\&.Provider\&.IByteFormatSchema\fP\&.
.PP
Definition at line \fB31\fP of file \fBColorR10G10B10\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
