.TH "SystemEx.Hash.Hash64" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Hash.Hash64 \- Represents a 64‑bit hash value produced by a \fBSystemEx\fP hashing algorithm\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHash64\fP (ulong value)"
.br
.RI "Creates a new 64‑bit hash wrapper\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly ulong \fBValue\fP"
.br
.RI "The raw 64‑bit hash value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a 64‑bit hash value produced by a \fBSystemEx\fP hashing algorithm\&. 

The struct is immutable and stores the raw 64‑bit result exactly as returned by the underlying hasher\&. No normalization or reinterpretation is performed\&. 
.PP
Definition at line \fB56\fP of file \fBIHash\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Hash\&.Hash64\&.Hash64 (ulong value)"

.PP
Creates a new 64‑bit hash wrapper\&. 
.PP
Definition at line \fB65\fP of file \fBIHash\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string SystemEx\&.Hash\&.Hash64\&.ToString ()"

.PP

.PP
Definition at line \fB68\fP of file \fBIHash\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly ulong SystemEx\&.Hash\&.Hash64\&.Value"

.PP
The raw 64‑bit hash value\&. 
.PP
Definition at line \fB60\fP of file \fBIHash\&.cs\fP\&.
.PP
Referenced by \fBHash64()\fP, \fBSystemEx\&.Hash\&.HashFactory\&.Hash64< T >()\fP, and \fBToString()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
