.TH "SystemEx.Base.NumberRangeStepper" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Base.NumberRangeStepper \- Provides a cursor-based stepper over a normalized numeric range\&. The stepper moves from Start to End in fixed increments and exposes forward/backward stepping, reset, and enumeration\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemEx\&.IRange< T >\fP, IEquatable, and IEnumerable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBContains\fP (long x)"
.br
.RI "Determines whether the specified value lies within the range\&. Works for both ascending and descending ranges\&. "
.ti -1c
.RI "bool \fBEquals\fP (\fBNumberRangeStepper\fP other)"
.br
.ti -1c
.RI "IEnumerator IEnumerable\&. \fBGetEnumerator\fP ()"
.br
.ti -1c
.RI "IEnumerator< long > IEnumerable< long >\&. \fBGetEnumerator\fP ()"
.br
.ti -1c
.RI "IEnumerator< long > \fBGetEnumerator\fP ()"
.br
.RI "Enumerates all values from From to To in increments of 1\&. "
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.ti -1c
.RI "IRange< long > \fBGetRange\fP (long tstart, long tend)"
.br
.RI "Creates a new range using optional override values for start and end\&. "
.ti -1c
.RI "IRange< long >? \fBIntersect\fP (IRange< long > other)"
.br
.RI "Computes the intersection of this range with another range\&. "
.ti -1c
.RI "bool \fBIsAdjacent\fP (IRange< long > other)"
.br
.RI "Determines whether this range touches another range at exactly one boundary\&. "
.ti -1c
.RI "\fBNumberRangeStepper\fP \fBNormalize\fP ()"
.br
.RI "Returns a normalized version of the range where From ≤ To\&. "
.ti -1c
.RI "\fBNumberRangeStepper\fP ()"
.br
.RI "Creates a new numeric range trom T\&.Zero to T\&.One\&. "
.ti -1c
.RI "\fBNumberRangeStepper\fP (long start, long end, long step=1)"
.br
.RI "Creates a new numeric range with the specified start and end values\&. "
.ti -1c
.RI "bool \fBOverlaps\fP (IRange< long > other)"
.br
.RI "Determines whether this range overlaps with another range\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a string representation of the range\&. "
.ti -1c
.RI "IRange< long >? \fBUnion\fP (IRange< long > other)"
.br
.RI "Computes the union of this range with another range if they overlap or are adjacent\&. Otherwise returns null\&. "
.in -1c

Public Member Functions inherited from \fBSystemEx\&.IRange< T >\fP
.in +1c
.ti -1c
.RI "bool \fBContains\fP (T x)"
.br
.RI "Determines whether the specified value lies within the range\&. "
.ti -1c
.RI "IRange< T > \fBGetRange\fP (T? tstart, T? tend)"
.br
.RI "Creates a new range using optional override values for start and end\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NumberRangeIterator< long > \fBBegin\fP\fR [get]\fP"
.br
.RI "Returns an iterator positioned at the start of the range\&. "
.ti -1c
.RI "NumberRangeIterator< long > \fBEnd\fP\fR [get]\fP"
.br
.RI "Returns an iterator positioned past the end of the range\&. "
.ti -1c
.RI "long \fBFrom\fP\fR [get, set]\fP"
.br
.RI "From value of the range\&. "
.ti -1c
.RI "bool \fBIsSame\fP\fR [get]\fP"
.br
.RI "Indicates whether the range represents a single value (From == To)\&. "
.ti -1c
.RI "bool \fBIsValid\fP\fR [get]\fP"
.br
.RI "Indicates whether the range is valid (From ≤ To)\&. "
.ti -1c
.RI "long \fBLength\fP\fR [get]\fP"
.br
.RI "Gets the length of the range (To - From)\&. "
.ti -1c
.RI "long \fBStep\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "long \fBTo\fP\fR [get, set]\fP"
.br
.RI "End value of the range\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides a cursor-based stepper over a normalized numeric range\&. The stepper moves from Start to End in fixed increments and exposes forward/backward stepping, reset, and enumeration\&. 
.PP
Definition at line \fB29\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Base\&.NumberRangeStepper\&.NumberRangeStepper ()"

.PP
Creates a new numeric range trom T\&.Zero to T\&.One\&. 
.PP
Definition at line \fB42\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.PP
Referenced by \fBGetRange()\fP, \fBIntersect()\fP, \fBNormalize()\fP, and \fBUnion()\fP\&.
.SS "SystemEx\&.Base\&.NumberRangeStepper\&.NumberRangeStepper (long start, long end, long step = \fR1\fP)"

.PP
Creates a new numeric range with the specified start and end values\&. 
.PP
\fBParameters\fP
.RS 4
\fIstart\fP From value\&.
.br
\fIend\fP To value\&.
.br
\fIstep\fP The next step
.RE
.PP

.PP
Definition at line \fB53\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SystemEx\&.Base\&.NumberRangeStepper\&.Contains (long x)"

.PP
Determines whether the specified value lies within the range\&. Works for both ascending and descending ranges\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Value to test\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the value is inside the range\&.
.RE
.PP

.PP
Definition at line \fB95\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SS "bool SystemEx\&.Base\&.NumberRangeStepper\&.Equals (\fBNumberRangeStepper\fP other)"

.PP
Definition at line \fB199\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SS "IEnumerator IEnumerable\&. SystemEx\&.Base\&.NumberRangeStepper\&.GetEnumerator ()"

.PP
Definition at line \fB207\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SS "IEnumerator< long > IEnumerable< long >\&. SystemEx\&.Base\&.NumberRangeStepper\&.GetEnumerator ()"

.PP
Definition at line \fB203\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SS "IEnumerator< long > SystemEx\&.Base\&.NumberRangeStepper\&.GetEnumerator ()"

.PP
Enumerates all values from From to To in increments of 1\&. 
.PP
\fBReturns\fP
.RS 4
Sequence of values in the range\&.
.RE
.PP

.PP
Definition at line \fB120\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SS "override int SystemEx\&.Base\&.NumberRangeStepper\&.GetHashCode ()"

.PP

.PP
Definition at line \fB86\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SS "IRange< long > SystemEx\&.Base\&.NumberRangeStepper\&.GetRange (long tstart, long tend)"

.PP
Creates a new range using optional override values for start and end\&. 
.PP
\fBParameters\fP
.RS 4
\fItstart\fP Optional new start value\&.
.br
\fItend\fP Optional new end value\&.
.RE
.PP
\fBReturns\fP
.RS 4
A new range with substituted boundaries\&.
.RE
.PP

.PP
Definition at line \fB112\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SS "IRange< long >? SystemEx\&.Base\&.NumberRangeStepper\&.Intersect (IRange< long > other)"

.PP
Computes the intersection of this range with another range\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP Range to intersect with\&.
.RE
.PP
\fBReturns\fP
.RS 4
A new range representing the intersection, or null if no overlap exists\&. 
.RE
.PP

.PP
Implements \fBSystemEx\&.IRange< T >\fP\&.
.PP
Definition at line \fB145\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SS "bool SystemEx\&.Base\&.NumberRangeStepper\&.IsAdjacent (IRange< long > other)"

.PP
Determines whether this range touches another range at exactly one boundary\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP Range to test\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the ranges are adjacent\&.
.RE
.PP

.PP
Implements \fBSystemEx\&.IRange< T >\fP\&.
.PP
Definition at line \fB161\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.PP
Referenced by \fBUnion()\fP\&.
.SS "\fBNumberRangeStepper\fP SystemEx\&.Base\&.NumberRangeStepper\&.Normalize ()"

.PP
Returns a normalized version of the range where From ≤ To\&. 
.PP
\fBReturns\fP
.RS 4
A normalized range\&.
.RE
.PP

.PP
Definition at line \fB101\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SS "bool SystemEx\&.Base\&.NumberRangeStepper\&.Overlaps (IRange< long > other)"

.PP
Determines whether this range overlaps with another range\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP Range to test\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the ranges overlap\&.
.RE
.PP

.PP
Implements \fBSystemEx\&.IRange< T >\fP\&.
.PP
Definition at line \fB129\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.PP
Referenced by \fBIntersect()\fP, and \fBUnion()\fP\&.
.SS "override string SystemEx\&.Base\&.NumberRangeStepper\&.ToString ()"

.PP
Returns a string representation of the range\&. 
.PP
Definition at line \fB193\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SS "IRange< long >? SystemEx\&.Base\&.NumberRangeStepper\&.Union (IRange< long > other)"

.PP
Computes the union of this range with another range if they overlap or are adjacent\&. Otherwise returns null\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP Range to merge with\&.
.RE
.PP
\fBReturns\fP
.RS 4
The merged range, or null if no merge is possible\&.
.RE
.PP

.PP
Implements \fBSystemEx\&.IRange< T >\fP\&.
.PP
Definition at line \fB178\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "NumberRangeIterator<long> SystemEx\&.Base\&.NumberRangeStepper\&.Begin\fR [get]\fP"

.PP
Returns an iterator positioned at the start of the range\&. 
.PP
Implements \fBSystemEx\&.IRange< T >\fP\&.
.PP
Definition at line \fB79\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SS "NumberRangeIterator<long> SystemEx\&.Base\&.NumberRangeStepper\&.End\fR [get]\fP"

.PP
Returns an iterator positioned past the end of the range\&. 
.PP
Implements \fBSystemEx\&.IRange< T >\fP\&.
.PP
Definition at line \fB83\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SS "long SystemEx\&.Base\&.NumberRangeStepper\&.From\fR [get]\fP, \fR [set]\fP"

.PP
From value of the range\&. 
.PP
Implements \fBSystemEx\&.IRange< T >\fP\&.
.PP
Definition at line \fB32\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.PP
Referenced by \fBNormalize()\fP, and \fBOverlaps()\fP\&.
.SS "bool SystemEx\&.Base\&.NumberRangeStepper\&.IsSame\fR [get]\fP"

.PP
Indicates whether the range represents a single value (From == To)\&. 
.PP
Implements \fBSystemEx\&.IRange< T >\fP\&.
.PP
Definition at line \fB75\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SS "bool SystemEx\&.Base\&.NumberRangeStepper\&.IsValid\fR [get]\fP"

.PP
Indicates whether the range is valid (From ≤ To)\&. 
.PP
Implements \fBSystemEx\&.IRange< T >\fP\&.
.PP
Definition at line \fB71\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.PP
Referenced by \fBIsAdjacent()\fP, \fBOverlaps()\fP, and \fBToString()\fP\&.
.SS "long SystemEx\&.Base\&.NumberRangeStepper\&.Length\fR [get]\fP"

.PP
Gets the length of the range (To - From)\&. 
.PP
Definition at line \fB67\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SS "long SystemEx\&.Base\&.NumberRangeStepper\&.Step\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB36\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.SS "long SystemEx\&.Base\&.NumberRangeStepper\&.To\fR [get]\fP, \fR [set]\fP"

.PP
End value of the range\&. 
.PP
Implements \fBSystemEx\&.IRange< T >\fP\&.
.PP
Definition at line \fB34\fP of file \fBNumberRangeStepper\&.cs\fP\&.
.PP
Referenced by \fBNormalize()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
