.TH "SystemEx.Collections.Generic.Sparsed< T >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Collections.Generic.Sparsed< T > \- A sparse container that stores elements in dynamic slots without enforcing contiguous or linear placement\&. Slots may be empty, and operations do not shift or compact elements\&. Designed for scenarios where random-access sparse storage is required with dynamic resizing\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemEx\&.Collections\&.Generic\&.IContainer< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.IAutoGrowe\fP, IEnumerable, IEquatable, \fBSystemEx\&.Collections\&.Generic\&.ITraverse< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.ISwappable< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClear\fP ()"
.br
.RI "Clears all elements while preserving the container size\&. "
.ti -1c
.RI "Optional< T > \fBElementAt\fP (long index)"
.br
.RI "Returns the element at the specified index\&. Throws if the index is out of range\&. "
.ti -1c
.RI "override bool \fBEquals\fP (object? obj)"
.br
.ti -1c
.RI "bool \fBEquals\fP (\fBSparsed\fP< T > other)"
.br
.ti -1c
.RI "bool \fBErase\fP ()"
.br
.RI "Removes the element at the current index\&. "
.ti -1c
.RI "bool \fBErase\fP (long index)"
.br
.RI "Removes the element at the specified index\&. "
.ti -1c
.RI "bool \fBErase\fP (T entry, bool all=false)"
.br
.ti -1c
.RI "Type \fBGetElementType\fP ()"
.br
.RI "Returns the underlying element type\&. "
.ti -1c
.RI "IEnumerator IEnumerable\&. \fBGetEnumerator\fP ()"
.br
.ti -1c
.RI "IEnumerator< T > \fBGetEnumerator\fP ()"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.ti -1c
.RI "bool \fBGrow\fP ()"
.br
.RI "Attempts to increase the collection's capacity according to \fBGrowSize\fP\&. Returns \fRtrue\fP if the growth succeeded\&. "
.ti -1c
.RI "bool \fBInsert\fP (long index, T entry)"
.br
.RI "Inserts an element into the container\&. This method attempts to place the element at the specified index\&. If the slot is empty, the element is stored there and the internal cursor (m_index) is updated to that position\&. "
.ti -1c
.RI "bool \fBInsert\fP (long start, long end, T entry)"
.br
.RI "Inserts the same element into all slots within the specified range\&. "
.ti -1c
.RI "Optional< T > \fBPop\fP ()"
.br
.RI "Removes the element at the current index and moves the cursor to the nearest occupied slot to the left\&. "
.ti -1c
.RI "bool \fBPush\fP (T entry)"
.br
.RI "Inserts an element near the current index if possible, otherwise selects any free slot\&. This operation does not shift elements and may overwrite sparse regions\&. "
.ti -1c
.RI "bool \fBReplace\fP (long index, T entry)"
.br
.RI "Replaces the element at the specified index without modifying the container's current cursor position (m_index)\&. "
.ti -1c
.RI "\fBSparsed\fP (long N, int growSize=4)"
.br
.RI "Initializes a new sparse container with the specified number of slots\&. "
.ti -1c
.RI "void \fBSwap\fP (long i, long j)"
.br
.ti -1c
.RI "void \fBTraverse\fP (\fBTraversMode\fP mode, long startIndex, long endIndex, Action< Optional< T > > func)"
.br
.in -1c

Public Member Functions inherited from \fBSystemEx\&.Collections\&.Generic\&.ITraverse< T >\fP
.in +1c
.ti -1c
.RI "void \fBTraverse\fP (\fBTraversMode\fP mode, long startIndex, long endIndex, Action< T > func)"
.br
.RI "Traverses a range of elements using the specified traversal mode\&. "
.in -1c

Public Member Functions inherited from \fBSystemEx\&.Collections\&.Generic\&.ISwappable< T >\fP
.in +1c
.ti -1c
.RI "void \fBSwap\fP (T i, T j)"
.br
.RI "Swaps the elements located at the given positions\&. Implementations must ensure that both indices are valid and that the operation is performed atomically with respect to the container's state\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBoperator!=\fP (\fBSparsed\fP< T > a, \fBSparsed\fP< T > b)"
.br
.ti -1c
.RI "static bool \fBoperator==\fP (\fBSparsed\fP< T > a, \fBSparsed\fP< T > b)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBAutoGrow\fP\fR [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether the collection should automatically grow when full\&. "
.ti -1c
.RI "Optional< T > \fBBack\fP\fR [get]\fP"
.br
.RI "Gets the element stored at the last slot (index Length - 1)\&. "
.ti -1c
.RI "long \fBCount\fP\fR [get]\fP"
.br
.RI "Gets the number of occupied slots\&. "
.ti -1c
.RI "Optional< T > \fBCurrent\fP\fR [get]\fP"
.br
.RI "Gets the element at the current index\&. Throws if the container is empty\&. "
.ti -1c
.RI "T \fBFirst\fP\fR [get]\fP"
.br
.RI "Gets the first occupied element in the container\&. Throws if the container is empty\&. "
.ti -1c
.RI "Optional< T > \fBFront\fP\fR [get]\fP"
.br
.RI "Gets the element stored at the first slot (index 0)\&. "
.ti -1c
.RI "long \fBGrowSize\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the number of elements by which the collection grows when additional capacity is needed\&. "
.ti -1c
.RI "bool \fBIsEmpty\fP\fR [get]\fP"
.br
.RI "Indicates whether no slots are occupied\&. "
.ti -1c
.RI "bool \fBIsFull\fP\fR [get]\fP"
.br
.RI "Indicates whether all slots are occupied\&. "
.ti -1c
.RI "T \fBLast\fP\fR [get]\fP"
.br
.RI "Gets the last occupied element in the container\&. Throws if the container is empty\&. "
.ti -1c
.RI "long \fBLength\fP\fR [get]\fP"
.br
.RI "Gets the total number of slots in the container\&. "
.in -1c
.SH "Detailed Description"
.PP 
A sparse container that stores elements in dynamic slots without enforcing contiguous or linear placement\&. Slots may be empty, and operations do not shift or compact elements\&. Designed for scenarios where random-access sparse storage is required with dynamic resizing\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The element type stored in the container\&.
.RE
.PP

.PP
Definition at line \fB31\fP of file \fBSparsed\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Clear ()"

.PP
Clears all elements while preserving the container size\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IContainer< T >\fP\&.
.PP
Definition at line \fB144\fP of file \fBSparsed\&.cs\fP\&.
.SS "Optional< T > SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.ElementAt (long index)"

.PP
Returns the element at the specified index\&. Throws if the index is out of range\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\fP\&.
.PP
Definition at line \fB153\fP of file \fBSparsed\&.cs\fP\&.
.PP
Referenced by \fBEquals()\fP\&.
.SS "override bool SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Equals (object? obj)"

.PP

.PP
Definition at line \fB430\fP of file \fBSparsed\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Equals (\fBSparsed\fP< T > other)"

.PP

.PP
Definition at line \fB411\fP of file \fBSparsed\&.cs\fP\&.
.PP
Referenced by \fBEquals()\fP, \fBErase()\fP, and \fBoperator==()\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Erase ()"

.PP
Removes the element at the current index\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IContainer< T >\fP\&.
.PP
Definition at line \fB162\fP of file \fBSparsed\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Erase (long index)"

.PP
Removes the element at the specified index\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IContainer< T >\fP\&.
.PP
Definition at line \fB196\fP of file \fBSparsed\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Erase (T entry, bool all = \fRfalse\fP)"

.PP
\fBParameters\fP
.RS 4
\fIentry\fP 
.br
\fIall\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB176\fP of file \fBSparsed\&.cs\fP\&.
.SS "Type SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.GetElementType ()"

.PP
Returns the underlying element type\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\fP\&.
.PP
Definition at line \fB210\fP of file \fBSparsed\&.cs\fP\&.
.SS "IEnumerator IEnumerable\&. SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.GetEnumerator ()"

.PP

.PP
Definition at line \fB478\fP of file \fBSparsed\&.cs\fP\&.
.SS "IEnumerator< T > SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.GetEnumerator ()"

.PP

.PP
Definition at line \fB470\fP of file \fBSparsed\&.cs\fP\&.
.PP
Referenced by \fBGetEnumerator()\fP\&.
.SS "override int SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.GetHashCode ()"

.PP

.PP
Definition at line \fB435\fP of file \fBSparsed\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Grow ()"

.PP
Attempts to increase the collection's capacity according to \fBGrowSize\fP\&. Returns \fRtrue\fP if the growth succeeded\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IAutoGrowe\fP\&.
.PP
Definition at line \fB393\fP of file \fBSparsed\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Insert (long index, T entry)"

.PP
Inserts an element into the container\&. This method attempts to place the element at the specified index\&. If the slot is empty, the element is stored there and the internal cursor (m_index) is updated to that position\&. If the target slot is already occupied, the method falls back to inserting the element into any available free slot (determined by getFreeSlot)\&. In this case, the cursor is updated to the free slot that actually received the new element\&.

.PP
This operation always moves the cursor to the slot where the element was successfully inserted\&. If no free slot exists, the insertion fails\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IContainer< T >\fP\&.
.PP
Definition at line \fB228\fP of file \fBSparsed\&.cs\fP\&.
.PP
Referenced by \fBInsert()\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Insert (long start, long end, T entry)"

.PP
Inserts the same element into all slots within the specified range\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IContainer< T >\fP\&.
.PP
Definition at line \fB265\fP of file \fBSparsed\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.operator!= (\fBSparsed\fP< T > a, \fBSparsed\fP< T > b)\fR [static]\fP"

.PP

.PP
Definition at line \fB490\fP of file \fBSparsed\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.operator== (\fBSparsed\fP< T > a, \fBSparsed\fP< T > b)\fR [static]\fP"

.PP

.PP
Definition at line \fB485\fP of file \fBSparsed\&.cs\fP\&.
.SS "Optional< T > SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Pop ()"

.PP
Removes the element at the current index and moves the cursor to the nearest occupied slot to the left\&. 
.PP
Definition at line \fB303\fP of file \fBSparsed\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Push (T entry)"

.PP
Inserts an element near the current index if possible, otherwise selects any free slot\&. This operation does not shift elements and may overwrite sparse regions\&. 
.PP
Definition at line \fB281\fP of file \fBSparsed\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Replace (long index, T entry)"

.PP
Replaces the element at the specified index without modifying the container's current cursor position (m_index)\&. Unlike \fBInsert(long, T)\fP, this operation does not represent a structural insertion\&. It simply overwrites the existing slot regardless of whether it was previously occupied\&. Because no new logical position is introduced, the cursor remains unchanged\&.

.PP
Use \fBInsert(long, T)\fP when you want to place a new element into an empty slot \fIand\fP move the cursor to that newly occupied position\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IContainer< T >\fP\&.
.PP
Definition at line \fB333\fP of file \fBSparsed\&.cs\fP\&.
.SS "SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Sparsed (long N, int growSize = \fR4\fP)"

.PP
Initializes a new sparse container with the specified number of slots\&. 
.PP
Definition at line \fB133\fP of file \fBSparsed\&.cs\fP\&.
.PP
Referenced by \fBEquals()\fP, \fBEquals()\fP, \fBoperator!=()\fP, and \fBoperator==()\fP\&.
.SS "void SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Swap (long i, long j)"

.PP

.PP
Definition at line \fB439\fP of file \fBSparsed\&.cs\fP\&.
.SS "void SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Traverse (\fBTraversMode\fP mode, long startIndex, long endIndex, Action< Optional< T > > func)"

.PP

.PP
Definition at line \fB452\fP of file \fBSparsed\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.AutoGrow\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets a value indicating whether the collection should automatically grow when full\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IAutoGrowe\fP\&.
.PP
Definition at line \fB127\fP of file \fBSparsed\&.cs\fP\&.
.PP
Referenced by \fBGrow()\fP, \fBInsert()\fP, and \fBReplace()\fP\&.
.SS "Optional<T> SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Back\fR [get]\fP"

.PP
Gets the element stored at the last slot (index Length - 1)\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\fP\&.
.PP
Definition at line \fB66\fP of file \fBSparsed\&.cs\fP\&.
.SS "long SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Count\fR [get]\fP"

.PP
Gets the number of occupied slots\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\fP\&.
.PP
Definition at line \fB106\fP of file \fBSparsed\&.cs\fP\&.
.SS "Optional<T> SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Current\fR [get]\fP"

.PP
Gets the element at the current index\&. Throws if the container is empty\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\fP\&.
.PP
Definition at line \fB101\fP of file \fBSparsed\&.cs\fP\&.
.SS "T SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.First\fR [get]\fP"

.PP
Gets the first occupied element in the container\&. Throws if the container is empty\&. 
.PP
Definition at line \fB48\fP of file \fBSparsed\&.cs\fP\&.
.SS "Optional<T> SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Front\fR [get]\fP"

.PP
Gets the element stored at the first slot (index 0)\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\fP\&.
.PP
Definition at line \fB42\fP of file \fBSparsed\&.cs\fP\&.
.SS "long SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.GrowSize\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the number of elements by which the collection grows when additional capacity is needed\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IAutoGrowe\fP\&.
.PP
Definition at line \fB116\fP of file \fBSparsed\&.cs\fP\&.
.PP
Referenced by \fBGrow()\fP, \fBInsert()\fP, \fBInsert()\fP, and \fBReplace()\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.IsEmpty\fR [get]\fP"

.PP
Indicates whether no slots are occupied\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\fP\&.
.PP
Definition at line \fB95\fP of file \fBSparsed\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.IsFull\fR [get]\fP"

.PP
Indicates whether all slots are occupied\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\fP\&.
.PP
Definition at line \fB90\fP of file \fBSparsed\&.cs\fP\&.
.PP
Referenced by \fBPush()\fP\&.
.SS "T SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Last\fR [get]\fP"

.PP
Gets the last occupied element in the container\&. Throws if the container is empty\&. 
.PP
Definition at line \fB71\fP of file \fBSparsed\&.cs\fP\&.
.SS "long SystemEx\&.Collections\&.Generic\&.Sparsed< T >\&.Length\fR [get]\fP"

.PP
Gets the total number of slots in the container\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.IReadOnlyContainer< T >\fP\&.
.PP
Definition at line \fB111\fP of file \fBSparsed\&.cs\fP\&.
.PP
Referenced by \fBClear()\fP, \fBElementAt()\fP, \fBEquals()\fP, \fBErase()\fP, \fBErase()\fP, \fBGetEnumerator()\fP, \fBGrow()\fP, \fBInsert()\fP, \fBPush()\fP, \fBReplace()\fP, and \fBSwap()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
