.TH "SystemEx.Collections.Generic.IQueue" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Collections.Generic.IQueue \- Defines the non-generic base interface for queue-like containers\&. Provides size information, capacity checks, and a method to clear the queue\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystemEx\&.Collections\&.Generic\&.IDeque\fP, and \fBSystemEx\&.Collections\&.Generic\&.IQueue< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClear\fP ()"
.br
.RI "Removes all elements from the queue\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsEmpty\fP\fR [get]\fP"
.br
.RI "Gets a value indicating whether the queue contains no elements\&. "
.ti -1c
.RI "bool \fBIsFull\fP\fR [get]\fP"
.br
.RI "Gets a value indicating whether the queue has reached its maximum capacity\&. "
.ti -1c
.RI "int \fBSize\fP\fR [get]\fP"
.br
.RI "Gets the number of elements currently stored in the queue\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the non-generic base interface for queue-like containers\&. Provides size information, capacity checks, and a method to clear the queue\&. 
.PP
Definition at line \fB26\fP of file \fBIQueue\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SystemEx\&.Collections\&.Generic\&.IQueue\&.Clear ()"

.PP
Removes all elements from the queue\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.BinQueue< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Deque< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Queue< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Queue\&.UniqueDeque< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.UniqueQueue< T >\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool SystemEx\&.Collections\&.Generic\&.IQueue\&.IsEmpty\fR [get]\fP"

.PP
Gets a value indicating whether the queue contains no elements\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.BinQueue< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Deque< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Queue< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Queue\&.UniqueDeque< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.UniqueQueue< T >\fP\&.
.PP
Definition at line \fB35\fP of file \fBIQueue\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.IQueue\&.IsFull\fR [get]\fP"

.PP
Gets a value indicating whether the queue has reached its maximum capacity\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.BinQueue< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Deque< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Queue< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Queue\&.UniqueDeque< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.UniqueQueue< T >\fP\&.
.PP
Definition at line \fB40\fP of file \fBIQueue\&.cs\fP\&.
.SS "int SystemEx\&.Collections\&.Generic\&.IQueue\&.Size\fR [get]\fP"

.PP
Gets the number of elements currently stored in the queue\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.BinQueue< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Deque< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Queue< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.Queue\&.UniqueDeque< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.UniqueQueue< T >\fP\&.
.PP
Definition at line \fB30\fP of file \fBIQueue\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
