.TH "SystemEx.Algorithms.Compute.ISimilarity< T >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Algorithms.Compute.ISimilarity< T > \- Represents a similarity evaluator that determines whether two values are similar, dissimilar, or indeterminate using a \fBTriple\fP decision\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTriple\fP \fBIsSimilar\fP (T a, T b)"
.br
.RI "Evaluates the similarity between two values\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a similarity evaluator that determines whether two values are similar, dissimilar, or indeterminate using a \fBTriple\fP decision\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The type of values being compared\&.
.RE
.PP

.PP
Definition at line \fB48\fP of file \fBIClassifier\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTriple\fP SystemEx\&.Algorithms\&.Compute\&.ISimilarity< T >\&.IsSimilar (T a, T b)"

.PP
Evaluates the similarity between two values\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
