.TH "SystemEx.Numeric.Quatd" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Numeric.Quatd \- Represents a doubleing‑point quaternion used for 3D rotations\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IComparable, \fBSystemEx\&.IComparableEx< T >\fP, IComparable, IEquatable, and \fBSystemEx\&.Hash\&.IHashable< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBCompareTo\fP (object? obj)"
.br
.RI "Compares this quaternion to another object\&. "
.ti -1c
.RI "\fBCompareResult\fP \fBCompareTo\fP (\fBQuatd\fP a)"
.br
.RI "Compares two quaternions using the configured \fBCompareMode\fP\&. "
.ti -1c
.RI "int IComparable< \fBQuatd\fP >\&. \fBCompareTo\fP (\fBQuatd\fP other)"
.br
.ti -1c
.RI "override bool \fBEquals\fP (object? obj)"
.br
.RI "Determines whether this instance is equal to another object\&. "
.ti -1c
.RI "bool \fBEquals\fP (\fBQuatd\fP other)"
.br
.ti -1c
.RI "double \fBGet\fP (int index)"
.br
.RI "Gets a component by index \&. "
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.RI "Computes a hash code for this vector\&. "
.ti -1c
.RI "double \fBGetRotationAngle\fP ()"
.br
.RI "Returns the rotation angle represented by this quaternion\&. "
.ti -1c
.RI "\fBVec3d\fP \fBGetRotationAxis\fP ()"
.br
.RI "Computes the normalized rotation axis of this quaternion\&. "
.ti -1c
.RI "\fBQuatd\fP ()"
.br
.RI "Initializes the identity quaternion (1,0,0,0)\&. "
.ti -1c
.RI "\fBQuatd\fP (\fBAxisAngle\fP< \fBVec3d\fP, double > axisAngle)"
.br
.RI "Initializes a quaternion from an axis‑angle representation\&. "
.ti -1c
.RI "\fBQuatd\fP (double fs, double fx, double fy, double fz)"
.br
.RI "Initializes a quaternion from explicit components\&. "
.ti -1c
.RI "\fBQuatd\fP (double[] pfs)"
.br
.RI "Initializes a quaternion from a double array\&. "
.ti -1c
.RI "\fBQuatd\fP (Quatd other)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "\fBQuatd\fP (\fBVec3d\fP angles)"
.br
.RI "Initializes a quaternion from Euler angles (XYZ order)\&. "
.ti -1c
.RI "FixedVector< byte > \fBToBytes\fP ()"
.br
.RI "Converts the vector into a deterministic byte sequence\&. "
.in -1c

Public Member Functions inherited from \fBSystemEx\&.IComparableEx< T >\fP
.in +1c
.ti -1c
.RI "\fBCompareResult\fP \fBCompareTo\fP (T a)"
.br
.RI "Compares this instance with the specified value and returns a \fBCompareResult\fP describing the relationship between them\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBQuatd\fP \fBConjugate\fP (\fBQuatd\fP v)"
.br
.RI "Computes the quaternion conjugate\&. "
.ti -1c
.RI "static double \fBDotProduct\fP (\fBQuatd\fP a, \fBQuatd\fP b)"
.br
.RI "Computes the DotProduct product of two quaternions\&. "
.ti -1c
.RI "static \fBQuatd\fP \fBExponent\fP (\fBQuatd\fP v)"
.br
.RI "Computes the quaternion exponential\&. "
.ti -1c
.RI "static \fBQuatd\fP \fBFromAxis\fP (\fBAxisAngle\fP< \fBVec3d\fP, double > axisAngle)"
.br
.RI "Creates a quaternion from an axis‑angle representation\&. "
.ti -1c
.RI "static \fBQuatd\fP \fBInvert\fP (\fBQuatd\fP q)"
.br
.RI "Computes the inverse of a quaternion\&. "
.ti -1c
.RI "static bool \fBIsIdentity\fP (\fBQuatd\fP v)"
.br
.RI "Determines whether a quaternion is the identity rotation\&. "
.ti -1c
.RI "static double \fBLenght\fP (\fBQuatd\fP v)"
.br
.RI "Computes the squared length of the quaternion\&. "
.ti -1c
.RI "static double \fBLenghtSqrt\fP (\fBQuatd\fP v)"
.br
.RI "Computes the Euclidean length of the quaternion\&. "
.ti -1c
.RI "static \fBQuatd\fP \fBLogarithm\fP (\fBQuatd\fP v)"
.br
.RI "Computes the quaternion logarithm\&. "
.ti -1c
.RI "static \fBQuatd\fP \fBNormalize\fP (\fBQuatd\fP v)"
.br
.RI "Normalizes a quaternion to unit length\&. "
.ti -1c
.RI "static \fBQuatd\fP \fBoperator*\fP (double a, \fBQuatd\fP b)"
.br
.RI "Multiplicate a double with a quaternion\&. "
.ti -1c
.RI "static \fBQuatd\fP \fBoperator*\fP (\fBQuatd\fP a, double b)"
.br
.RI "Multiplicate a quaternion with a double\&. "
.ti -1c
.RI "static \fBQuatd\fP \fBoperator*\fP (\fBQuatd\fP a, \fBQuatd\fP b)"
.br
.RI "Multiplies two \fBQuatd\fP component‑wise\&. "
.ti -1c
.RI "static \fBQuatd\fP \fBoperator+\fP (\fBQuatd\fP a, \fBQuatd\fP b)"
.br
.RI "Adds two \fBQuatd\fP component‑wise\&. "
.ti -1c
.RI "static \fBQuatd\fP \fBoperator\-\fP (\fBQuatd\fP a)"
.br
.RI "Invert\&. "
.ti -1c
.RI "static \fBQuatd\fP \fBoperator\-\fP (\fBQuatd\fP a, \fBQuatd\fP b)"
.br
.RI "Subtracts two \fBQuatd\fP component‑wise\&. "
.ti -1c
.RI "static \fBQuatd\fP \fBoperator/\fP (\fBQuatd\fP a, double b)"
.br
.RI "Divides both components of the \fBQuatd\fP by a double\&. "
.ti -1c
.RI "static \fBQuatd\fP \fBoperator/\fP (\fBQuatd\fP a, \fBQuatd\fP b)"
.br
.RI "Divides two \fBQuatd\fP component‑wise\&. "
.ti -1c
.RI "static \fBQuatd\fP \fBPower\fP (\fBQuatd\fP v, double Exp)"
.br
.RI "Raises a quaternion to a scalar power\&. "
.ti -1c
.RI "static \fBQuatd\fP \fBSlerp\fP (\fBQuatd\fP q0, \fBQuatd\fP q1, double t)"
.br
.RI "Performs spherical linear interpolation between two quaternions\&. "
.ti -1c
.RI "static \fBAxisAngle\fP< \fBVec3d\fP, double > \fBToAxisAngle\fP (\fBQuatd\fP q)"
.br
.RI "Converts a quaternion into an axis‑angle representation\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "AxisAngle< \fBVec3d\fP, double > \fBAxisAngle\fP\fR [get]\fP"
.br
.RI "Gets the axis‑angle representation of this quaternion\&. "
.ti -1c
.RI "\fBCompareType\fP \fBCompareMode\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the comparison mode used by \fBCompareTo(Quatd)\fP\&. "
.ti -1c
.RI "double \fBS\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the scalar component (w) of the quaternion\&. "
.ti -1c
.RI "\fBVec3d\fP \fBV\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the vector component (x,y,z) of the quaternion\&. "
.ti -1c
.RI "double \fBX\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the X component of the quaternion's vector part\&. "
.ti -1c
.RI "double \fBY\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the Y component of the quaternion's vector part\&. "
.ti -1c
.RI "double \fBZ\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the Z component of the quaternion's vector part\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a doubleing‑point quaternion used for 3D rotations\&. 

\fBQuatd\fP stores a scalar component \fRw\fP and a vector component \fR(x,y,z)\fP in a sequential memory layout, making it suitable for native interop, compute kernels, and deterministic hashing\&. 

.PP
The struct is annotated with \fBHashAlgorithmAttribute\fP to enable attribute‑driven hashing via HashFactory\&. 
.br
 \fBBernsteinHash\fP is used because it is fast, byte‑linear, and ideal for small fixed‑size numeric types\&. 

.PP
\fBQuatd\fP implements multiple comparison and hashing interfaces: 
.PD 0
.IP "\(bu" 2
IComparable and IComparable<T> for ordering 
.IP "\(bu" 2
IEquatable<T> for equality checks 
.IP "\(bu" 2
\fBIHashable<T>\fP for deterministic byte‑level hashing 
.PP

.PP
Definition at line \fB57\fP of file \fBQuatd\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Numeric\&.Quatd\&.Quatd ()"

.PP
Initializes the identity quaternion (1,0,0,0)\&. 
.PP
Definition at line \fB111\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBCompareTo()\fP, \fBCompareTo()\fP, \fBConjugate()\fP, \fBDotProduct()\fP, \fBEquals()\fP, \fBEquals()\fP, \fBExponent()\fP, \fBFromAxis()\fP, \fBInvert()\fP, \fBIsIdentity()\fP, \fBLenght()\fP, \fBLenghtSqrt()\fP, \fBLogarithm()\fP, \fBNormalize()\fP, \fBoperator*()\fP, \fBoperator*()\fP, \fBoperator*()\fP, \fBoperator+()\fP, \fBoperator\-()\fP, \fBoperator\-()\fP, \fBoperator/()\fP, \fBoperator/()\fP, \fBPower()\fP, \fBQuatd()\fP, \fBSlerp()\fP, and \fBToAxisAngle()\fP\&.
.SS "SystemEx\&.Numeric\&.Quatd\&.Quatd (\fBVec3d\fP angles)"

.PP
Initializes a quaternion from Euler angles (XYZ order)\&. 
.PP
Definition at line \fB119\fP of file \fBQuatd\&.cs\fP\&.
.SS "SystemEx\&.Numeric\&.Quatd\&.Quatd (double fs, double fx, double fy, double fz)"

.PP
Initializes a quaternion from explicit components\&. 
.PP
Definition at line \fB141\fP of file \fBQuatd\&.cs\fP\&.
.SS "SystemEx\&.Numeric\&.Quatd\&.Quatd (double[] pfs)"

.PP
Initializes a quaternion from a double array\&. 
.PP
Definition at line \fB150\fP of file \fBQuatd\&.cs\fP\&.
.SS "SystemEx\&.Numeric\&.Quatd\&.Quatd (\fBAxisAngle\fP< \fBVec3d\fP, double > axisAngle)"

.PP
Initializes a quaternion from an axis‑angle representation\&. 
.PP
Definition at line \fB159\fP of file \fBQuatd\&.cs\fP\&.
.SS "SystemEx\&.Numeric\&.Quatd\&.Quatd (Quatd other)"

.PP
Copy constructor\&. 
.PP
Definition at line \fB169\fP of file \fBQuatd\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int SystemEx\&.Numeric\&.Quatd\&.CompareTo (object? obj)"

.PP
Compares this quaternion to another object\&. 
.PP
Definition at line \fB515\fP of file \fBQuatd\&.cs\fP\&.
.SS "\fBCompareResult\fP SystemEx\&.Numeric\&.Quatd\&.CompareTo (\fBQuatd\fP a)"

.PP
Compares two quaternions using the configured \fBCompareMode\fP\&. 
.PP
Definition at line \fB483\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBCompareTo()\fP\&.
.SS "int IComparable< \fBQuatd\fP >\&. SystemEx\&.Numeric\&.Quatd\&.CompareTo (\fBQuatd\fP other)"

.PP
Definition at line \fB508\fP of file \fBQuatd\&.cs\fP\&.
.SS "\fBQuatd\fP SystemEx\&.Numeric\&.Quatd\&.Conjugate (\fBQuatd\fP v)\fR [static]\fP"

.PP
Computes the quaternion conjugate\&. 
.PP
Definition at line \fB405\fP of file \fBQuatd\&.cs\fP\&.
.SS "double SystemEx\&.Numeric\&.Quatd\&.DotProduct (\fBQuatd\fP a, \fBQuatd\fP b)\fR [static]\fP"

.PP
Computes the DotProduct product of two quaternions\&. 
.PP
Definition at line \fB359\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBSlerp()\fP\&.
.SS "override bool SystemEx\&.Numeric\&.Quatd\&.Equals (object? obj)"

.PP
Determines whether this instance is equal to another object\&. The object is considered equal if it is a \fBQuatd\fP and compares equal using \fBEquals(Quatd)\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIobj\fP The object to compare with\&.
.RE
.PP
\fBReturns\fP
.RS 4
\fRtrue\fP if \fIobj\fP  is a \fBQuatd\fP and equal to this instance; otherwise \fRfalse\fP\&. 
.RE
.PP

.PP
Definition at line \fB573\fP of file \fBQuatd\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Quatd\&.Equals (\fBQuatd\fP other)"

.PP

.PP
Definition at line \fB523\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBEquals()\fP\&.
.SS "\fBQuatd\fP SystemEx\&.Numeric\&.Quatd\&.Exponent (\fBQuatd\fP v)\fR [static]\fP"

.PP
Computes the quaternion exponential\&. 
.PP
Definition at line \fB265\fP of file \fBQuatd\&.cs\fP\&.
.SS "\fBQuatd\fP SystemEx\&.Numeric\&.Quatd\&.FromAxis (\fBAxisAngle\fP< \fBVec3d\fP, double > axisAngle)\fR [static]\fP"

.PP
Creates a quaternion from an axis‑angle representation\&. 
.PP
Definition at line \fB221\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBQuatd()\fP\&.
.SS "double SystemEx\&.Numeric\&.Quatd\&.Get (int index)"

.PP
Gets a component by index \&. 
.PP
Definition at line \fB178\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBToBytes()\fP\&.
.SS "override int SystemEx\&.Numeric\&.Quatd\&.GetHashCode ()"

.PP
Computes a hash code for this vector\&. The primary hash is generated using HashFactory and the \fBHashAlgorithmAttribute\fP applied to this struct\&. 
.br
 If hashing fails (rare), a fallback XOR‑based hash is used\&. 
.PP
Definition at line \fB553\fP of file \fBQuatd\&.cs\fP\&.
.SS "double SystemEx\&.Numeric\&.Quatd\&.GetRotationAngle ()"

.PP
Returns the rotation angle represented by this quaternion\&. 
.PP
Definition at line \fB251\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBCompareTo()\fP, and \fBToAxisAngle()\fP\&.
.SS "\fBVec3d\fP SystemEx\&.Numeric\&.Quatd\&.GetRotationAxis ()"

.PP
Computes the normalized rotation axis of this quaternion\&. 
.PP
Definition at line \fB192\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBToAxisAngle()\fP\&.
.SS "\fBQuatd\fP SystemEx\&.Numeric\&.Quatd\&.Invert (\fBQuatd\fP q)\fR [static]\fP"

.PP
Computes the inverse of a quaternion\&. 
.PP
Definition at line \fB369\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBoperator/()\fP\&.
.SS "bool SystemEx\&.Numeric\&.Quatd\&.IsIdentity (\fBQuatd\fP v)\fR [static]\fP"

.PP
Determines whether a quaternion is the identity rotation\&. 
.PP
Definition at line \fB259\fP of file \fBQuatd\&.cs\fP\&.
.SS "double SystemEx\&.Numeric\&.Quatd\&.Lenght (\fBQuatd\fP v)\fR [static]\fP"

.PP
Computes the squared length of the quaternion\&. 
.PP
Definition at line \fB322\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBInvert()\fP\&.
.SS "double SystemEx\&.Numeric\&.Quatd\&.LenghtSqrt (\fBQuatd\fP v)\fR [static]\fP"

.PP
Computes the Euclidean length of the quaternion\&. 
.PP
Definition at line \fB311\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBNormalize()\fP\&.
.SS "\fBQuatd\fP SystemEx\&.Numeric\&.Quatd\&.Logarithm (\fBQuatd\fP v)\fR [static]\fP"

.PP
Computes the quaternion logarithm\&. 
.PP
Definition at line \fB288\fP of file \fBQuatd\&.cs\fP\&.
.SS "\fBQuatd\fP SystemEx\&.Numeric\&.Quatd\&.Normalize (\fBQuatd\fP v)\fR [static]\fP"

.PP
Normalizes a quaternion to unit length\&. 
.PP
Definition at line \fB382\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBFromAxis()\fP, and \fBPower()\fP\&.
.SS "\fBQuatd\fP SystemEx\&.Numeric\&.Quatd\&.operator* (double a, \fBQuatd\fP b)\fR [static]\fP"

.PP
Multiplicate a double with a quaternion\&. 
.PP
Definition at line \fB609\fP of file \fBQuatd\&.cs\fP\&.
.SS "\fBQuatd\fP SystemEx\&.Numeric\&.Quatd\&.operator* (\fBQuatd\fP a, double b)\fR [static]\fP"

.PP
Multiplicate a quaternion with a double\&. 
.PP
Definition at line \fB620\fP of file \fBQuatd\&.cs\fP\&.
.SS "\fBQuatd\fP SystemEx\&.Numeric\&.Quatd\&.operator* (\fBQuatd\fP a, \fBQuatd\fP b)\fR [static]\fP"

.PP
Multiplies two \fBQuatd\fP component‑wise\&. 
.PP
Definition at line \fB580\fP of file \fBQuatd\&.cs\fP\&.
.SS "\fBQuatd\fP SystemEx\&.Numeric\&.Quatd\&.operator+ (\fBQuatd\fP a, \fBQuatd\fP b)\fR [static]\fP"

.PP
Adds two \fBQuatd\fP component‑wise\&. 
.PP
Definition at line \fB631\fP of file \fBQuatd\&.cs\fP\&.
.SS "\fBQuatd\fP SystemEx\&.Numeric\&.Quatd\&.operator\- (\fBQuatd\fP a)\fR [static]\fP"

.PP
Invert\&. 
.PP
Definition at line \fB653\fP of file \fBQuatd\&.cs\fP\&.
.SS "\fBQuatd\fP SystemEx\&.Numeric\&.Quatd\&.operator\- (\fBQuatd\fP a, \fBQuatd\fP b)\fR [static]\fP"

.PP
Subtracts two \fBQuatd\fP component‑wise\&. 
.PP
Definition at line \fB642\fP of file \fBQuatd\&.cs\fP\&.
.SS "\fBQuatd\fP SystemEx\&.Numeric\&.Quatd\&.operator/ (\fBQuatd\fP a, double b)\fR [static]\fP"

.PP
Divides both components of the \fBQuatd\fP by a double\&. 
.PP
Definition at line \fB670\fP of file \fBQuatd\&.cs\fP\&.
.SS "\fBQuatd\fP SystemEx\&.Numeric\&.Quatd\&.operator/ (\fBQuatd\fP a, \fBQuatd\fP b)\fR [static]\fP"

.PP
Divides two \fBQuatd\fP component‑wise\&. 
.PP
Definition at line \fB664\fP of file \fBQuatd\&.cs\fP\&.
.SS "\fBQuatd\fP SystemEx\&.Numeric\&.Quatd\&.Power (\fBQuatd\fP v, double Exp)\fR [static]\fP"

.PP
Raises a quaternion to a scalar power\&. 
.PP
Definition at line \fB331\fP of file \fBQuatd\&.cs\fP\&.
.SS "\fBQuatd\fP SystemEx\&.Numeric\&.Quatd\&.Slerp (\fBQuatd\fP q0, \fBQuatd\fP q1, double t)\fR [static]\fP"

.PP
Performs spherical linear interpolation between two quaternions\&. 
.PP
Definition at line \fB418\fP of file \fBQuatd\&.cs\fP\&.
.SS "\fBAxisAngle\fP< \fBVec3d\fP, double > SystemEx\&.Numeric\&.Quatd\&.ToAxisAngle (\fBQuatd\fP q)\fR [static]\fP"

.PP
Converts a quaternion into an axis‑angle representation\&. 
.PP
Definition at line \fB210\fP of file \fBQuatd\&.cs\fP\&.
.SS "FixedVector< byte > SystemEx\&.Numeric\&.Quatd\&.ToBytes ()"

.PP
Converts the vector into a deterministic byte sequence\&. This method is used by HashFactory to compute attribute‑driven hashes\&. The byte layout is stable and platform‑safe, ensuring consistent hashing across devices and backends\&. 
.PP
Implements \fBSystemEx\&.Hash\&.IHashable< T >\fP\&.
.PP
Definition at line \fB535\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBToBytes()\fP\&.
.SH "Property Documentation"
.PP 
.SS "AxisAngle<\fBVec3d\fP, double> SystemEx\&.Numeric\&.Quatd\&.AxisAngle\fR [get]\fP"

.PP
Gets the axis‑angle representation of this quaternion\&. 
.PP
Definition at line \fB96\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBFromAxis()\fP, \fBQuatd()\fP, and \fBToAxisAngle()\fP\&.
.SS "\fBCompareType\fP SystemEx\&.Numeric\&.Quatd\&.CompareMode\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the comparison mode used by \fBCompareTo(Quatd)\fP\&. 
.PP
Definition at line \fB106\fP of file \fBQuatd\&.cs\fP\&.
.SS "double SystemEx\&.Numeric\&.Quatd\&.S\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the scalar component (w) of the quaternion\&. 
.PP
Definition at line \fB71\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBGet()\fP\&.
.SS "\fBVec3d\fP SystemEx\&.Numeric\&.Quatd\&.V\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the vector component (x,y,z) of the quaternion\&. 
.PP
Definition at line \fB76\fP of file \fBQuatd\&.cs\fP\&.
.SS "double SystemEx\&.Numeric\&.Quatd\&.X\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the X component of the quaternion's vector part\&. 
.PP
Definition at line \fB81\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBGet()\fP\&.
.SS "double SystemEx\&.Numeric\&.Quatd\&.Y\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the Y component of the quaternion's vector part\&. 
.PP
Definition at line \fB86\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBGet()\fP\&.
.SS "double SystemEx\&.Numeric\&.Quatd\&.Z\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the Z component of the quaternion's vector part\&. 
.PP
Definition at line \fB91\fP of file \fBQuatd\&.cs\fP\&.
.PP
Referenced by \fBGet()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
