.TH "SystemEx.Algorithms.Compute.ICVector" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Algorithms.Compute.ICVector \- Represents a read‑only computational vector with a fixed dimension\&. 
.br
 Provides indexed access to floating‑point components\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBDimension\fP\fR [get]\fP"
.br
.RI "Gets the number of dimensions of the vector\&. "
.ti -1c
.RI "float \fBthis[int index]\fP\fR [get]\fP"
.br
.RI "Gets the component value at the specified index\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a read‑only computational vector with a fixed dimension\&. 
.br
 Provides indexed access to floating‑point components\&. 
.PP
Definition at line \fB30\fP of file \fBICVector \&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int SystemEx\&.Algorithms\&.Compute\&.ICVector\&.Dimension\fR [get]\fP"

.PP
Gets the number of dimensions of the vector\&. 
.PP
Definition at line \fB35\fP of file \fBICVector \&.cs\fP\&.
.SS "float SystemEx\&.Algorithms\&.Compute\&.ICVector\&.this[int index]\fR [get]\fP"

.PP
Gets the component value at the specified index\&. 
.PP
Definition at line \fB40\fP of file \fBICVector \&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
