.TH "SystemEx.Device" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Device
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNativeRAMKernel< TD >\fP"
.br
.RI "Provides a base implementation for RAM‑based compute kernels that operate on \fBDeviceSharedBuffer<RamSharedBackend>\fP instances\&. 
.br
 This class handles module loading, buffer management, backend initialization, locking/unlocking of shared buffers, and asynchronous kernel execution\&. 
.br
 Derived classes only need to implement backend‑specific behavior such as buffer creation (\fBOnCreate\fP) and kernel invocation (\fBOnRun\fP)\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
