.TH "SystemEx.Collections.Generic.SubSlice< T, TContainer >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Collections.Generic.SubSlice< T, TContainer > \- SubSlice describes a mathematical range and ownership state\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "long \fBGetIndex\fP (int sub_index)"
.br
.RI "Get the real index\&. "
.ti -1c
.RI "\fBSubSlice\fP (long sliceStart, long sliceLen)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBHasOwner\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
SubSlice describes a mathematical range and ownership state\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Element type stored in the container\&.
.br
\fITContainer\fP Container type implementing \fBIVector<T>\fP\&. 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fITContainer\fP : \fIIVector<T>\fP
.PP
Definition at line \fB31\fP of file \fBVectorSlice\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "long SystemEx\&.Collections\&.Generic\&.SubSlice< T, TContainer >\&.GetIndex (int sub_index)"

.PP
Get the real index\&. 
.PP
Definition at line \fB54\fP of file \fBVectorSlice\&.cs\fP\&.
.PP
Referenced by \fBSystemEx\&.Collections\&.Generic\&.Slices< T, TContainer >\&.GetValue()\fP\&.
.SS "SystemEx\&.Collections\&.Generic\&.SubSlice< T, TContainer >\&.SubSlice (long sliceStart, long sliceLen)"

.PP
Definition at line \fB43\fP of file \fBVectorSlice\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool SystemEx\&.Collections\&.Generic\&.SubSlice< T, TContainer >\&.HasOwner\fR [get]\fP"

.PP
Definition at line \fB41\fP of file \fBVectorSlice\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
