.TH "SystemEx.Algorithms.Compute.ThresholdClassifier" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Algorithms.Compute.ThresholdClassifier \- Implements a threshold‑based classifier using two boundaries:  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemEx\&.Algorithms\&.Compute\&.IThreshold\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTriple\fP \fBEvaluate\fP (float value)"
.br
.RI "Evaluates the given value and returns a three‑state threshold decision\&. "
.ti -1c
.RI "\fBThresholdClassifier\fP (float trueThreshold, float falseThreshold)"
.br
.RI "Initializes a new threshold classifier with the specified true and false limits\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implements a threshold‑based classifier using two boundaries: 


.IP "\(bu" 2
Values above the true threshold → \fBtriple\&.True\fP 
.br

.IP "\(bu" 2
Values below the false threshold → \fBtriple\&.False\fP 
.br

.IP "\(bu" 2
Values in between → \fBtriple\&.Nin\fP 
.PP

.PP
Definition at line \fB32\fP of file \fBThresholdClassifier\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Algorithms\&.Compute\&.ThresholdClassifier\&.ThresholdClassifier (float trueThreshold, float falseThreshold)"

.PP
Initializes a new threshold classifier with the specified true and false limits\&. 
.PP
Definition at line \fB39\fP of file \fBThresholdClassifier\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTriple\fP SystemEx\&.Algorithms\&.Compute\&.ThresholdClassifier\&.Evaluate (float value)"

.PP
Evaluates the given value and returns a three‑state threshold decision\&. 
.PP
Implements \fBSystemEx\&.Algorithms\&.Compute\&.IThreshold\fP\&.
.PP
Definition at line \fB46\fP of file \fBThresholdClassifier\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
