.TH "SystemEx.NumberRangeIterator< T >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.NumberRangeIterator< T > \- Forward iterator over a normalized numeric range\&. Supports stepping by one unit and exposes the current value and end-of-range state\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemEx\&.Collections\&.Generic\&.Iterrator< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBForward\fP ()"
.br
.RI "Moves the iterator one step forward\&. "
.ti -1c
.RI "void \fBForward\fP (long i)"
.br
.RI "Moves the iterator N step forward\&. "
.ti -1c
.RI "\fBNumberRangeIterator\fP (Vector< T > range, long end)"
.br
.RI "Initializes a new iterator\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Optional< T > \fBCurrent\fP\fR [get]\fP"
.br
.RI "Gets the element at the current iterator position\&. "
.ti -1c
.RI "long \fBIndex\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the current index of the iterator\&. "
.ti -1c
.RI "bool \fBIsEnd\fP\fR [get]\fP"
.br
.RI "Indicates whether the iterator has reached the end boundary\&. "
.in -1c
.SH "Detailed Description"
.PP 
Forward iterator over a normalized numeric range\&. Supports stepping by one unit and exposes the current value and end-of-range state\&. 
.PP
Definition at line \fB27\fP of file \fBNumberRangeIterrator\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SystemEx\&.NumberRangeIterator< T >\&.Forward ()"

.PP
Moves the iterator one step forward\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.Iterrator< T >\fP\&.
.PP
Definition at line \fB58\fP of file \fBNumberRangeIterrator\&.cs\fP\&.
.PP
Referenced by \fBForward()\fP\&.
.SS "void SystemEx\&.NumberRangeIterator< T >\&.Forward (long i)"

.PP
Moves the iterator N step forward\&. 
.PP
Definition at line \fB66\fP of file \fBNumberRangeIterrator\&.cs\fP\&.
.SS "SystemEx\&.NumberRangeIterator< T >\&.NumberRangeIterator (Vector< T > range, long end)"

.PP
Initializes a new iterator\&. 
.PP
Definition at line \fB37\fP of file \fBNumberRangeIterrator\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Optional<T> SystemEx\&.NumberRangeIterator< T >\&.Current\fR [get]\fP"

.PP
Gets the element at the current iterator position\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.Iterrator< T >\fP\&.
.PP
Definition at line \fB46\fP of file \fBNumberRangeIterrator\&.cs\fP\&.
.SS "long SystemEx\&.NumberRangeIterator< T >\&.Index\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the current index of the iterator\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.Iterrator< T >\fP\&.
.PP
Definition at line \fB53\fP of file \fBNumberRangeIterrator\&.cs\fP\&.
.SS "bool SystemEx\&.NumberRangeIterator< T >\&.IsEnd\fR [get]\fP"

.PP
Indicates whether the iterator has reached the end boundary\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.Iterrator< T >\fP\&.
.PP
Definition at line \fB51\fP of file \fBNumberRangeIterrator\&.cs\fP\&.
.PP
Referenced by \fBForward()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
