.TH "SystemEx.Algorithms.Less< T >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Algorithms.Less< T > \- Provides a Tripleean comparison that determines whether A is strictly smaller than B\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemEx\&.Algorithms\&.ISimpleCompare< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTriple\fP \fBCompare\fP (Optional< T > a, Optional< T > b)"
.br
.RI "Returns \fRtrue\fPA is strictly smaller than B; otherwise \fRfalse\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides a Tripleean comparison that determines whether A is strictly smaller than B\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The type of values being compared\&. 
.RE
.PP

.PP
Definition at line \fB162\fP of file \fBComparer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTriple\fP SystemEx\&.Algorithms\&.Less< T >\&.Compare (Optional< T > a, Optional< T > b)"

.PP
Returns \fRtrue\fPA is strictly smaller than B; otherwise \fRfalse\fP\&. Comparison is only performed when both optionals contain valid, non-null values\&. If either optional is null, the comparison is undefined and this method returns \fRfalse\fP\&. 
.PP
Implements \fBSystemEx\&.Algorithms\&.ISimpleCompare< T >\fP\&.
.PP
Definition at line \fB171\fP of file \fBComparer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
