.TH "SystemEx.Algorithms" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Algorithms
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBinarySearcherProvider< T, TContainer >\fP"
.br
.RI "A specialized search provider implementing binary-search-based probing\&. "
.ti -1c
.RI "class \fBEqualTo< T >\fP"
.br
.RI "Provides a Tripleean comparison that determines whether A and B are equal\&. "
.ti -1c
.RI "struct \fBFibonacciSearcherProvider< T, TContainer >\fP"
.br
.RI "Provides a Fibonacci‑based search strategy for containers implementing \fBIContainer<T>\fP\&. "
.ti -1c
.RI "class \fBGreater< T >\fP"
.br
.RI "Provides a Tripleean comparison that determines whether A is strictly larger than B\&. "
.ti -1c
.RI "class \fBGreaterEqual< T >\fP"
.br
.RI "Provides a Tripleean comparison that determines whether A is larger than or equal to B\&. "
.ti -1c
.RI "interface \fBICompared< T >\fP"
.br
.RI "Defines a comparison interface for types that support custom ordering\&. Implementations return a \fBCompareResult\fP describing the relationship between two values\&. "
.ti -1c
.RI "interface \fBISearchProvider< T, TContainer >\fP"
.br
.ti -1c
.RI "interface \fBISimpleCompare< T >\fP"
.br
.ti -1c
.RI "class \fBKleeneEqual< T >\fP"
.br
.RI "Provides a three-valued equality comparison\&. Determines whether A is equal to B\&. "
.ti -1c
.RI "class \fBKleenEqualTo< T >\fP"
.br
.RI "Provides a three-valued comparison that determines whether A is equal to B\&. "
.ti -1c
.RI "class \fBKleenGreater< T >\fP"
.br
.RI "Provides a three-valued comparison that determines whether A is strictly greater than B\&. "
.ti -1c
.RI "class \fBKleenLess< T >\fP"
.br
.RI "Provides a three-valued comparison that determines whether A is strictly smaller than B\&. "
.ti -1c
.RI "class \fBLess< T >\fP"
.br
.RI "Provides a Tripleean comparison that determines whether A is strictly smaller than B\&. "
.ti -1c
.RI "class \fBLessEqual< T >\fP"
.br
.RI "Provides a Tripleean comparison that determines whether X is smaller than or equal to B\&. "
.ti -1c
.RI "struct \fBLinearSearchProvider< T, TContainer >\fP"
.br
.RI "A simple fallback search provider that performs a linear scan over the container and counts how many elements match the given condition\&. "
.ti -1c
.RI "class \fBNetStdCompare< T >\fP"
.br
.RI "Provides a three-valued comparison based on standard \&.NET ordering\&. Determines whether A is smaller, greater, or equal to B\&. "
.ti -1c
.RI "class \fBNotEqualTo< T >\fP"
.br
.RI "Provides a Tripleean comparison that determines whether A and B are not equal\&. "
.ti -1c
.RI "class \fBSimpleComparer< T >\fP"
.br
.RI "Provides a standard comparison implementation for values wrapped in \fBOptional<T>\fP where \fIT\fP  implements IComparable<T>\&. "
.ti -1c
.RI "class \fBSortActions\fP"
.br
.RI "Provides a set of sorting algorithms that operate on any container implementing \fBIVector<T>\fP\&. 
.br
 All algorithms use \fBISimpleCompare<T>\fP as their comparison strategy\&. "
.ti -1c
.RI "class \fBValueComparer< T >\fP"
.br
.RI "Provides a numeric comparison implementation for values wrapped in \fBOptional<T>\fP where \fIT\fP  implements INumber<T>\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
