.TH "SystemEx.Rand.Engine.IRandomEngine" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Rand.Engine.IRandomEngine \- Defines the contract for a deterministic 32-bit random number generator engine\&. Implementations provide a reproducible sequence of unsigned 32-bit values based on an initial seed\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystemEx\&.Rand\&.Engine\&.Isaac32Engine\fP, and \fBSystemEx\&.Rand\&.Engine\&.MTwisterEngine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint \fBNext\fP ()"
.br
.RI "Generates the next 32-bit unsigned integer in the random sequence\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBISeed\fP \fBStartSeed\fP\fR [get]\fP"
.br
.RI "Gets the seed object that was used to initialize this engine\&. The seed allows deterministic reproduction of the generated sequence\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the contract for a deterministic 32-bit random number generator engine\&. Implementations provide a reproducible sequence of unsigned 32-bit values based on an initial seed\&. 
.PP
Definition at line \fB24\fP of file \fBIRandomEngine\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "uint SystemEx\&.Rand\&.Engine\&.IRandomEngine\&.Next ()"

.PP
Generates the next 32-bit unsigned integer in the random sequence\&. 
.PP
\fBReturns\fP
.RS 4
The next 32-bit random value\&.
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Rand\&.Engine\&.Isaac32Engine\fP, and \fBSystemEx\&.Rand\&.Engine\&.MTwisterEngine\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBISeed\fP SystemEx\&.Rand\&.Engine\&.IRandomEngine\&.StartSeed\fR [get]\fP"

.PP
Gets the seed object that was used to initialize this engine\&. The seed allows deterministic reproduction of the generated sequence\&. 
.PP
Implemented in \fBSystemEx\&.Rand\&.Engine\&.Isaac32Engine\fP, and \fBSystemEx\&.Rand\&.Engine\&.MTwisterEngine\fP\&.
.PP
Definition at line \fB30\fP of file \fBIRandomEngine\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
