.TH "SystemEx.IRange< T >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.IRange< T > \- Defines the basic contract for a numeric range with a start and end value\&. Provides validation, containment checks, range slicing, merging, adjacency detection, and intersection logic\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystemEx\&.Base\&.NumberRangeStepper\fP, and \fBSystemEx\&.NumberRange\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBContains\fP (T x)"
.br
.RI "Determines whether the specified value lies within the range\&. "
.ti -1c
.RI "IRange< T > \fBGetRange\fP (T? tstart, T? tend)"
.br
.RI "Creates a new range using optional override values for start and end\&. "
.ti -1c
.RI "IRange< T >? \fBIntersect\fP (IRange< T > other)"
.br
.RI "Computes the intersection of this range with another range\&. "
.ti -1c
.RI "bool \fBIsAdjacent\fP (IRange< T > other)"
.br
.RI "Determines whether this range touches another range at exactly one boundary\&. "
.ti -1c
.RI "bool \fBOverlaps\fP (IRange< T > other)"
.br
.RI "Determines whether this range overlaps with another range\&. "
.ti -1c
.RI "IRange< T >? \fBUnion\fP (IRange< T > other)"
.br
.RI "Computes the union of this range with another range if they overlap or are adjacent\&. Otherwise returns null\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NumberRangeIterator< T > \fBBegin\fP\fR [get]\fP"
.br
.RI "Returns an iterator positioned at the start of the range\&. "
.ti -1c
.RI "NumberRangeIterator< T > \fBEnd\fP\fR [get]\fP"
.br
.RI "Returns an iterator positioned past the end of the range\&. "
.ti -1c
.RI "T \fBFrom\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the start value of the range\&. "
.ti -1c
.RI "bool \fBIsSame\fP\fR [get]\fP"
.br
.RI "Indicates whether the range represents a single value (Start == End)\&. "
.ti -1c
.RI "bool \fBIsValid\fP\fR [get]\fP"
.br
.RI "Indicates whether the range is valid (Start ≤ End)\&. "
.ti -1c
.RI "T \fBTo\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the end value of the range\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the basic contract for a numeric range with a start and end value\&. Provides validation, containment checks, range slicing, merging, adjacency detection, and intersection logic\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP \fBNumeric\fP type used for the range boundaries\&.
.RE
.PP

.PP
Definition at line \fB28\fP of file \fBIRange\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SystemEx\&.IRange< T >\&.Contains (T x)"

.PP
Determines whether the specified value lies within the range\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Value to test\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the value is inside the range\&.
.RE
.PP

.SS "IRange< T > SystemEx\&.IRange< T >\&.GetRange (T? tstart, T? tend)"

.PP
Creates a new range using optional override values for start and end\&. 
.PP
\fBParameters\fP
.RS 4
\fItstart\fP Optional new start value\&.
.br
\fItend\fP Optional new end value\&.
.RE
.PP
\fBReturns\fP
.RS 4
A new range with substituted boundaries\&.
.RE
.PP

.SS "IRange< T >? SystemEx\&.IRange< T >\&.Intersect (IRange< T > other)"

.PP
Computes the intersection of this range with another range\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP Range to intersect with\&.
.RE
.PP
\fBReturns\fP
.RS 4
A new range representing the intersection, or null if no overlap exists\&. 
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Base\&.NumberRangeStepper\fP, and \fBSystemEx\&.NumberRange\fP\&.
.SS "bool SystemEx\&.IRange< T >\&.IsAdjacent (IRange< T > other)"

.PP
Determines whether this range touches another range at exactly one boundary\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP Range to test\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the ranges are adjacent\&.
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Base\&.NumberRangeStepper\fP, and \fBSystemEx\&.NumberRange\fP\&.
.SS "bool SystemEx\&.IRange< T >\&.Overlaps (IRange< T > other)"

.PP
Determines whether this range overlaps with another range\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP Range to test\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the ranges overlap\&.
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Base\&.NumberRangeStepper\fP, and \fBSystemEx\&.NumberRange\fP\&.
.SS "IRange< T >? SystemEx\&.IRange< T >\&.Union (IRange< T > other)"

.PP
Computes the union of this range with another range if they overlap or are adjacent\&. Otherwise returns null\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP Range to merge with\&.
.RE
.PP
\fBReturns\fP
.RS 4
The merged range, or null if no merge is possible\&.
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Base\&.NumberRangeStepper\fP, and \fBSystemEx\&.NumberRange\fP\&.
.SH "Property Documentation"
.PP 
.SS "NumberRangeIterator<T> SystemEx\&.IRange< T >\&.Begin\fR [get]\fP"

.PP
Returns an iterator positioned at the start of the range\&. 
.PP
Implemented in \fBSystemEx\&.Base\&.NumberRangeStepper\fP, and \fBSystemEx\&.NumberRange\fP\&.
.PP
Definition at line \fB33\fP of file \fBIRange\&.cs\fP\&.
.SS "NumberRangeIterator<T> SystemEx\&.IRange< T >\&.End\fR [get]\fP"

.PP
Returns an iterator positioned past the end of the range\&. 
.PP
Implemented in \fBSystemEx\&.Base\&.NumberRangeStepper\fP, and \fBSystemEx\&.NumberRange\fP\&.
.PP
Definition at line \fB38\fP of file \fBIRange\&.cs\fP\&.
.SS "T SystemEx\&.IRange< T >\&.From\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the start value of the range\&. 
.PP
Implemented in \fBSystemEx\&.Base\&.NumberRangeStepper\fP, and \fBSystemEx\&.NumberRange\fP\&.
.PP
Definition at line \fB43\fP of file \fBIRange\&.cs\fP\&.
.PP
Referenced by \fBSystemEx\&.Base\&.NumberRangeStepper\&.Intersect()\fP, \fBSystemEx\&.NumberRange\&.Intersect()\fP, \fBSystemEx\&.Base\&.NumberRangeStepper\&.Union()\fP, and \fBSystemEx\&.NumberRange\&.Union()\fP\&.
.SS "bool SystemEx\&.IRange< T >\&.IsSame\fR [get]\fP"

.PP
Indicates whether the range represents a single value (Start == End)\&. 
.PP
Implemented in \fBSystemEx\&.Base\&.NumberRangeStepper\fP, and \fBSystemEx\&.NumberRange\fP\&.
.PP
Definition at line \fB58\fP of file \fBIRange\&.cs\fP\&.
.SS "bool SystemEx\&.IRange< T >\&.IsValid\fR [get]\fP"

.PP
Indicates whether the range is valid (Start ≤ End)\&. 
.PP
Implemented in \fBSystemEx\&.Base\&.NumberRangeStepper\fP, and \fBSystemEx\&.NumberRange\fP\&.
.PP
Definition at line \fB53\fP of file \fBIRange\&.cs\fP\&.
.PP
Referenced by \fBSystemEx\&.Base\&.NumberRangeStepper\&.IsAdjacent()\fP, \fBSystemEx\&.NumberRange\&.IsAdjacent()\fP, \fBSystemEx\&.Base\&.NumberRangeStepper\&.Overlaps()\fP, and \fBSystemEx\&.NumberRange\&.Overlaps()\fP\&.
.SS "T SystemEx\&.IRange< T >\&.To\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the end value of the range\&. 
.PP
Implemented in \fBSystemEx\&.Base\&.NumberRangeStepper\fP, and \fBSystemEx\&.NumberRange\fP\&.
.PP
Definition at line \fB48\fP of file \fBIRange\&.cs\fP\&.
.PP
Referenced by \fBSystemEx\&.Base\&.NumberRangeStepper\&.Intersect()\fP, \fBSystemEx\&.NumberRange\&.Intersect()\fP, \fBSystemEx\&.Base\&.NumberRangeStepper\&.Union()\fP, and \fBSystemEx\&.NumberRange\&.Union()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
