.TH "SystemEx.Collections.Generic.ICluster" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Collections.Generic.ICluster \- Represents a cluster node in a weighted graph structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystemEx\&.Collections\&.Generic\&.ICluster< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint \fBCostAt\fP (long index)"
.br
.RI "Get Cost of the element at position N\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBHaveChild\fP\fR [get]\fP"
.br
.RI "Have this node a Child\&. "
.ti -1c
.RI "bool \fBHaveParent\fP\fR [get]\fP"
.br
.RI "Have this Node a Parent\&. "
.ti -1c
.RI "long \fBSize\fP\fR [get]\fP"
.br
.RI "Number of direct children (outgoing edges) of this node\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a cluster node in a weighted graph structure\&. 
.PP
Definition at line \fB25\fP of file \fBICluster\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "uint SystemEx\&.Collections\&.Generic\&.ICluster\&.CostAt (long index)"

.PP
Get Cost of the element at position N\&. 
.PP
\fBParameters\fP
.RS 4
\fIindex\fP 
.RE
.PP
\fBReturns\fP
.RS 4
The costs the elment on position N
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.Cluster< T >\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool SystemEx\&.Collections\&.Generic\&.ICluster\&.HaveChild\fR [get]\fP"

.PP
Have this node a Child\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.Cluster< T >\fP\&.
.PP
Definition at line \fB34\fP of file \fBICluster\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.ICluster\&.HaveParent\fR [get]\fP"

.PP
Have this Node a Parent\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.Cluster< T >\fP\&.
.PP
Definition at line \fB38\fP of file \fBICluster\&.cs\fP\&.
.SS "long SystemEx\&.Collections\&.Generic\&.ICluster\&.Size\fR [get]\fP"

.PP
Number of direct children (outgoing edges) of this node\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.Cluster< T >\fP\&.
.PP
Definition at line \fB29\fP of file \fBICluster\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
