.TH "SystemEx.Logging" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Logging
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTraceLevel\fP { \fBOff\fP = 0, \fBError\fP = 1, \fBWarning\fP = 2, \fBInfo\fP = 3, \fBVerbose\fP = 4 }"
.br
.RI "Specifies what messages to output\&. "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSystemEx\&.Logging\&.TraceLevel\fP"

.PP
Specifies what messages to output\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIOff \fP
Output no tracing and debugging messages\&. 
.TP
\f(BIError \fP
Output error-handling messages\&. 
.TP
\f(BIWarning \fP
Output warnings and error-handling messages\&. 
.TP
\f(BIInfo \fP
Output informational messages, warnings, and error-handling messages\&. 
.TP
\f(BIVerbose \fP
Output all debugging and tracing messages\&. 
.PP
Definition at line \fB22\fP of file \fBTraceLevel\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
