.TH "SystemEx.Runtime" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Runtime
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFunction< TReturn, TDelegate >\fP"
.br
.RI "Represents a loaded native module (DLL, SO, or DYLIB)\&. 
.br
 A \fBModule\fP encapsulates the operating system handle of the loaded library and provides helper methods for resolving exported functions and unloading the module\&. "
.ti -1c
.RI "class \fBModule\fP"
.br
.RI "Represents a loaded native module (DLL, SO, or DYLIB)\&. 
.br
 A \fBModule\fP encapsulates the operating system handle of the loaded library and provides helper methods for resolving exported functions and unloading the module\&. "
.ti -1c
.RI "struct \fBModuleInfo\fP"
.br
.ti -1c
.RI "class \fBModulePreloader\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBHashType\fP { \fBBernstein\fP, \fBCRC32\fP, \fBSHA256\fP, \fBMURMUR3\fP, \fBNone\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum SystemEx\&.Runtime\&.HashType"

.PP
Definition at line \fB23\fP of file \fBModuleInfo\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
