.TH "SystemEx.Rand.GenericRand< TEngine >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Rand.GenericRand< TEngine > \- Provides a simple interface for generating random numbers using varibale Engines algorithm\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystemEx\&.Rand\&.Randx\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericRand\fP (TEngine engine)"
.br
.ti -1c
.RI "uint \fBNext\fP (uint min, uint max)"
.br
.RI "Generates the next random number in the specified range\&. "
.ti -1c
.RI "ulong \fBNext\fP (ulong min, ulong max)"
.br
.RI "Generates the next random number in the specified range\&. "
.ti -1c
.RI "uint \fBNext32\fP ()"
.br
.RI "Generates the next random 32-bit number in the sequence\&. "
.ti -1c
.RI "ulong \fBNext64\fP ()"
.br
.RI "Generates the next random 64-bit number in the sequence\&. "
.ti -1c
.RI "byte \fBNextByte\fP ()"
.br
.RI "Generates the next random byte in the sequence\&. "
.ti -1c
.RI "void \fBNextBytes\fP (byte[] buffer)"
.br
.RI "Generates the next random number in the specified range\&. "
.ti -1c
.RI "char \fBNextChar\fP ()"
.br
.RI "Generates the next random character in the sequence\&. "
.ti -1c
.RI "uint \fBNextHashSeed32\fP ()"
.br
.RI "Generates the next random hash seed in the sequence\&. "
.ti -1c
.RI "ulong \fBNextHashSeed64\fP ()"
.br
.RI "Generates the next random hash seed in the sequence\&. "
.ti -1c
.RI "string \fBNextString\fP (int length)"
.br
.RI "Generates the next random string in the sequence\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIRandomEngine\fP \fBDefaultEngine\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides a simple interface for generating random numbers using varibale Engines algorithm\&. 
.PP
\fBType Constraints\fP
.TP
\fITEngine\fP : \fIIRandomEngine\fP
.PP
Definition at line \fB27\fP of file \fBGenericRand\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "SystemEx\&.Rand\&.GenericRand< TEngine >\&.GenericRand (TEngine engine)"

.PP
Definition at line \fB32\fP of file \fBGenericRand\&.cs\fP\&.
.SS "uint SystemEx\&.Rand\&.GenericRand< TEngine >\&.Next (uint min, uint max)"

.PP
Generates the next random number in the specified range\&. 
.PP
\fBParameters\fP
.RS 4
\fImin\fP The minimum value\&.
.br
\fImax\fP The maximum value\&.
.RE
.PP
\fBReturns\fP
.RS 4
The next random number\&.
.RE
.PP

.PP
Definition at line \fB73\fP of file \fBGenericRand\&.cs\fP\&.
.SS "ulong SystemEx\&.Rand\&.GenericRand< TEngine >\&.Next (ulong min, ulong max)"

.PP
Generates the next random number in the specified range\&. 
.PP
\fBParameters\fP
.RS 4
\fImin\fP The minimum value\&.
.br
\fImax\fP The maximum value\&.
.RE
.PP
\fBReturns\fP
.RS 4
The next random number\&.
.RE
.PP

.PP
Definition at line \fB83\fP of file \fBGenericRand\&.cs\fP\&.
.SS "uint SystemEx\&.Rand\&.GenericRand< TEngine >\&.Next32 ()"

.PP
Generates the next random 32-bit number in the sequence\&. 
.PP
\fBReturns\fP
.RS 4
The next random 32-bit number\&.
.RE
.PP

.PP
Definition at line \fB39\fP of file \fBGenericRand\&.cs\fP\&.
.PP
Referenced by \fBNext()\fP, \fBNextChar()\fP, and \fBNextHashSeed32()\fP\&.
.SS "ulong SystemEx\&.Rand\&.GenericRand< TEngine >\&.Next64 ()"

.PP
Generates the next random 64-bit number in the sequence\&. 
.PP
\fBReturns\fP
.RS 4
The next random 64-bit number\&.
.RE
.PP

.PP
Definition at line \fB46\fP of file \fBGenericRand\&.cs\fP\&.
.PP
Referenced by \fBNext()\fP, and \fBNextHashSeed64()\fP\&.
.SS "byte SystemEx\&.Rand\&.GenericRand< TEngine >\&.NextByte ()"

.PP
Generates the next random byte in the sequence\&. 
.PP
\fBReturns\fP
.RS 4
The next random byte\&.
.RE
.PP

.PP
Definition at line \fB56\fP of file \fBGenericRand\&.cs\fP\&.
.PP
Referenced by \fBNextBytes()\fP\&.
.SS "void SystemEx\&.Rand\&.GenericRand< TEngine >\&.NextBytes (byte[] buffer)"

.PP
Generates the next random number in the specified range\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP The buffer to fill with random bytes\&.
.RE
.PP

.PP
Definition at line \fB63\fP of file \fBGenericRand\&.cs\fP\&.
.SS "char SystemEx\&.Rand\&.GenericRand< TEngine >\&.NextChar ()"

.PP
Generates the next random character in the sequence\&. 
.PP
\fBReturns\fP
.RS 4
The next random character\&.
.RE
.PP

.PP
Definition at line \fB91\fP of file \fBGenericRand\&.cs\fP\&.
.PP
Referenced by \fBNextString()\fP\&.
.SS "uint SystemEx\&.Rand\&.GenericRand< TEngine >\&.NextHashSeed32 ()"

.PP
Generates the next random hash seed in the sequence\&. 
.PP
\fBReturns\fP
.RS 4
The next random hash seed\&.
.RE
.PP

.PP
Definition at line \fB109\fP of file \fBGenericRand\&.cs\fP\&.
.SS "ulong SystemEx\&.Rand\&.GenericRand< TEngine >\&.NextHashSeed64 ()"

.PP
Generates the next random hash seed in the sequence\&. 
.PP
\fBReturns\fP
.RS 4
The next random hash seed\&.
.RE
.PP

.PP
Definition at line \fB116\fP of file \fBGenericRand\&.cs\fP\&.
.SS "string SystemEx\&.Rand\&.GenericRand< TEngine >\&.NextString (int length)"

.PP
Generates the next random string in the sequence\&. 
.PP
\fBParameters\fP
.RS 4
\fIlength\fP The length of the string to generate\&.
.RE
.PP
\fBReturns\fP
.RS 4
The next random string\&.
.RE
.PP

.PP
Definition at line \fB99\fP of file \fBGenericRand\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIRandomEngine\fP SystemEx\&.Rand\&.GenericRand< TEngine >\&.DefaultEngine\fR [get]\fP"

.PP
Definition at line \fB30\fP of file \fBGenericRand\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
