.TH "SystemEx.AI.Backend" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.AI.Backend
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWebAIBackend< T >\fP"
.br
.RI "backend implementation for \fBAI\fP models that communicate with remote Web‑API services using HTTP POST requests\&. "
.ti -1c
.RI "struct \fBWebAIBackendPayload< T >\fP"
.br
.RI "Represents the payload sent to a remote Web‑API based \fBAI\fP backend\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
