.TH "SystemEx.Drawing.ColorHSL" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Drawing.ColorHSL \- Represents a color in the HSL (Hue–Saturation–Lightness) color space using floating‑point components\&. 
.br
 Provides hue‑aware interpolation, component manipulation, arithmetic operations, and normalization utilities\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IEquatable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorHSL\fP (float h, float s, float l)"
.br
.RI "Initializes a new HSL color with the specified component values\&. "
.ti -1c
.RI "\fBColorHSL\fP (float[] x)"
.br
.RI "Initializes a new HSL color from an array of three floating‑point values\&. "
.ti -1c
.RI "bool \fBEquals\fP (\fBColorHSL\fP? other)"
.br
.ti -1c
.RI "override bool \fBEquals\fP (object? obj)"
.br
.RI "Determines whether this instance is equal to another object\&. "
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a string representation of the YUV color\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual float \fBH\fP\fR [get]\fP"
.br
.RI "Gets the hue component\&. "
.ti -1c
.RI "virtual float \fBL\fP\fR [get]\fP"
.br
.RI "Gets the Lightness component\&. "
.ti -1c
.RI "virtual float \fBS\fP\fR [get]\fP"
.br
.RI "Gets the saturation component\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a color in the HSL (Hue–Saturation–Lightness) color space using floating‑point components\&. 
.br
 Provides hue‑aware interpolation, component manipulation, arithmetic operations, and normalization utilities\&. 
.PP
Definition at line \fB25\fP of file \fBColorHSL\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Drawing\&.ColorHSL\&.ColorHSL (float[] x)"

.PP
Initializes a new HSL color from an array of three floating‑point values\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP An array containing H, S, and L in that order\&.
.RE
.PP

.PP
Definition at line \fB51\fP of file \fBColorHSL\&.cs\fP\&.
.PP
Referenced by \fBEquals()\fP, and \fBEquals()\fP\&.
.SS "SystemEx\&.Drawing\&.ColorHSL\&.ColorHSL (float h, float s, float l)"

.PP
Initializes a new HSL color with the specified component values\&. 
.PP
Definition at line \fB59\fP of file \fBColorHSL\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SystemEx\&.Drawing\&.ColorHSL\&.Equals (\fBColorHSL\fP? other)"
<summarH> Determines whether this instance is equal to another HSL color\&. </summarH> 
.PP
\fBParameters\fP
.RS 4
\fIother\fP The color to compare with\&.
.RE
.PP
\fBReturns\fP
.RS 4
\fRtrue\fP if the components match; otherwise \fRfalse\fP\&. 
.RE
.PP

.PP
Definition at line \fB71\fP of file \fBColorHSL\&.cs\fP\&.
.PP
Referenced by \fBEquals()\fP\&.
.SS "override bool SystemEx\&.Drawing\&.ColorHSL\&.Equals (object? obj)"

.PP
Determines whether this instance is equal to another object\&. 
.PP
Definition at line \fB86\fP of file \fBColorHSL\&.cs\fP\&.
.SS "override int SystemEx\&.Drawing\&.ColorHSL\&.GetHashCode ()"
<summarH> Returns a hash code based on the H, S, and L components\&. </summarH> 
.PP
Definition at line \fB80\fP of file \fBColorHSL\&.cs\fP\&.
.SS "override string SystemEx\&.Drawing\&.ColorHSL\&.ToString ()"

.PP
Returns a string representation of the YUV color\&. 
.PP
Definition at line \fB94\fP of file \fBColorHSL\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "virtual float SystemEx\&.Drawing\&.ColorHSL\&.H\fR [get]\fP"

.PP
Gets the hue component\&. 
.PP
Definition at line \fB34\fP of file \fBColorHSL\&.cs\fP\&.
.SS "virtual float SystemEx\&.Drawing\&.ColorHSL\&.L\fR [get]\fP"

.PP
Gets the Lightness component\&. 
.PP
Definition at line \fB44\fP of file \fBColorHSL\&.cs\fP\&.
.SS "virtual float SystemEx\&.Drawing\&.ColorHSL\&.S\fR [get]\fP"

.PP
Gets the saturation component\&. 
.PP
Definition at line \fB39\fP of file \fBColorHSL\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
