.TH "SystemEx.Rand.Engine.Isaac32EngineSeed" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Rand.Engine.Isaac32EngineSeed \- Represents the seed container used by the \fBIsaac32Engine\fP\&. Stores the three 32-bit seed values required for initializing the ISAAC random number generator\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemEx\&.Rand\&.ISeed\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint[] \fBGetSeed\fP ()"
.br
.RI "Returns the underlying array of seed values\&. "
.ti -1c
.RI "\fBIsaac32EngineSeed\fP (uint a=0, uint b=0, uint c=0)"
.br
.RI "Initializes a new instance of the \fBIsaac32EngineSeed\fP struct using the specified 32-bit seed values\&. If fewer than three values are provided, the remaining values default to zero\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBLength\fP\fR [get]\fP"
.br
.RI "Gets the number of seed values stored in this seed container\&. "
.ti -1c
.RI "uint \fBthis[int i]\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the seed value at the specified index\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents the seed container used by the \fBIsaac32Engine\fP\&. Stores the three 32-bit seed values required for initializing the ISAAC random number generator\&. 
.PP
Definition at line \fB25\fP of file \fBIsaac32Engine\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Rand\&.Engine\&.Isaac32EngineSeed\&.Isaac32EngineSeed (uint a = \fR0\fP, uint b = \fR0\fP, uint c = \fR0\fP)"

.PP
Initializes a new instance of the \fBIsaac32EngineSeed\fP struct using the specified 32-bit seed values\&. If fewer than three values are provided, the remaining values default to zero\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP The first seed value\&.
.br
\fIb\fP The second seed value\&.
.br
\fIc\fP The third seed value\&.
.RE
.PP

.PP
Definition at line \fB56\fP of file \fBIsaac32Engine\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "uint[] SystemEx\&.Rand\&.Engine\&.Isaac32EngineSeed\&.GetSeed ()"

.PP
Returns the underlying array of seed values\&. 
.PP
\fBReturns\fP
.RS 4
An array containing all seed values\&.
.RE
.PP

.PP
Implements \fBSystemEx\&.Rand\&.ISeed\fP\&.
.PP
Definition at line \fB44\fP of file \fBIsaac32Engine\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int SystemEx\&.Rand\&.Engine\&.Isaac32EngineSeed\&.Length\fR [get]\fP"

.PP
Gets the number of seed values stored in this seed container\&. 
.PP
Implements \fBSystemEx\&.Rand\&.ISeed\fP\&.
.PP
Definition at line \fB38\fP of file \fBIsaac32Engine\&.cs\fP\&.
.SS "uint SystemEx\&.Rand\&.Engine\&.Isaac32EngineSeed\&.this[int i]\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the seed value at the specified index\&. 
.PP
\fBParameters\fP
.RS 4
\fIi\fP The index of the seed value\&.
.RE
.PP
\fBReturns\fP
.RS 4
The seed value at the specified index\&.
.RE
.PP

.PP
Implements \fBSystemEx\&.Rand\&.ISeed\fP\&.
.PP
Definition at line \fB33\fP of file \fBIsaac32Engine\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
