.TH "SystemEx.Hash.WeinbergHash" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Hash.WeinbergHash \- Implements the Weinberg hash algorithm\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemEx\&.Hash\&.IHash\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHash32\fP \fBCompute\fP (FixedVector< byte > input, uint seed)"
.br
.RI "Computes the Weinberg hash of the given input\&. "
.ti -1c
.RI "\fBHash64\fP \fBComputeLong\fP (FixedVector< byte > input, ulong seed)"
.br
.RI "Computes the Weinberg hash of the given input\&. "
.ti -1c
.RI "\fBWeinbergHash\fP (\fBEndian\fP endian)"
.br
.RI "Craate a new instance\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implements the Weinberg hash algorithm\&. 
.PP
Definition at line \fB29\fP of file \fBWeinbergHash\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Hash\&.WeinbergHash\&.WeinbergHash (\fBEndian\fP endian)"

.PP
Craate a new instance\&. 
.PP
\fBParameters\fP
.RS 4
\fIendian\fP The suing endian for creating a hash
.RE
.PP

.PP
Definition at line \fB36\fP of file \fBWeinbergHash\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBHash32\fP SystemEx\&.Hash\&.WeinbergHash\&.Compute (FixedVector< byte > input, uint seed)"

.PP
Computes the Weinberg hash of the given input\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP The input data to hash\&.
.br
\fIseed\fP The seed value for the hash computation\&.
.RE
.PP
\fBReturns\fP
.RS 4
The computed Weinberg hash as a 32-bit value\&.
.RE
.PP

.PP
Implements \fBSystemEx\&.Hash\&.IHash\fP\&.
.PP
Definition at line \fB46\fP of file \fBWeinbergHash\&.cs\fP\&.
.SS "\fBHash64\fP SystemEx\&.Hash\&.WeinbergHash\&.ComputeLong (FixedVector< byte > input, ulong seed)"

.PP
Computes the Weinberg hash of the given input\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP The input data to hash\&.
.br
\fIseed\fP The seed value for the hash computation\&.
.RE
.PP
\fBReturns\fP
.RS 4
The computed Weinberg hash as a 64-bit value\&.
.RE
.PP

.PP
Implements \fBSystemEx\&.Hash\&.IHash\fP\&.
.PP
Definition at line \fB67\fP of file \fBWeinbergHash\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
