.TH "SystemEx.IO.Provider" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.IO.Provider
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBByteSeriablizeProvider\fP"
.br
.RI "Provides a base implementation for serializing objects to and from byte arrays\&. "
.ti -1c
.RI "interface \fBIByteFormatSchema\fP"
.br
.RI "A schema defines total size, header size, endianness and fixed field offsets\&. Implementations must be deterministic and contain no dynamic or computed layout\&. "
.ti -1c
.RI "interface \fBIByteSerialize< T, TSchema >\fP"
.br
.RI "Provides deterministic binary serialization and deserialization for a type \fIT\fP  using a schema \fITSchema\fP \&. "
.ti -1c
.RI "interface \fBIIsByteSeriablize\fP"
.br
.RI "Represents a type that can be serialized to and from byte arrays\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
