.TH "SystemEx.Runtime.Backend.Loader.IPreloaderBackend" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Runtime.Backend.Loader.IPreloaderBackend
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBDownLoadModule\fP (ref string destionation, Platform platform, \fBArchitecture\fP arch)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBCanUpdate\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBIPreloaderBackendConfig\fP \fBConfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBDestination\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBUseSignatureCheak\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBUseTempFS\fP\fR [get]\fP"
.br
.ti -1c
.RI "Version \fBVersion\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB25\fP of file \fBIPreloaderBackend\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool SystemEx\&.Runtime\&.Backend\&.Loader\&.IPreloaderBackend\&.CanUpdate\fR [get]\fP"

.PP
Definition at line \fB36\fP of file \fBIPreloaderBackend\&.cs\fP\&.
.SS "\fBIPreloaderBackendConfig\fP SystemEx\&.Runtime\&.Backend\&.Loader\&.IPreloaderBackend\&.Config\fR [get]\fP"

.PP
Definition at line \fB38\fP of file \fBIPreloaderBackend\&.cs\fP\&.
.SS "string SystemEx\&.Runtime\&.Backend\&.Loader\&.IPreloaderBackend\&.Destination\fR [get]\fP"

.PP
Definition at line \fB32\fP of file \fBIPreloaderBackend\&.cs\fP\&.
.SS "string SystemEx\&.Runtime\&.Backend\&.Loader\&.IPreloaderBackend\&.Name\fR [get]\fP"

.PP
Definition at line \fB27\fP of file \fBIPreloaderBackend\&.cs\fP\&.
.SS "bool SystemEx\&.Runtime\&.Backend\&.Loader\&.IPreloaderBackend\&.UseSignatureCheak\fR [get]\fP"

.PP
Definition at line \fB30\fP of file \fBIPreloaderBackend\&.cs\fP\&.
.SS "bool SystemEx\&.Runtime\&.Backend\&.Loader\&.IPreloaderBackend\&.UseTempFS\fR [get]\fP"

.PP
Definition at line \fB34\fP of file \fBIPreloaderBackend\&.cs\fP\&.
.SS "Version SystemEx\&.Runtime\&.Backend\&.Loader\&.IPreloaderBackend\&.Version\fR [get]\fP"

.PP
Definition at line \fB28\fP of file \fBIPreloaderBackend\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
