.TH "SystemEx.Collections.Generic.Iterrator< T >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Collections.Generic.Iterrator< T > \- Represents a generic iterator over a collection\&. Provides access to the current element and supports advancing the iterator\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystemEx\&.Collections\&.Generic\&.BidirectionalIterator< T, TCollection >\fP, \fBSystemEx\&.Collections\&.Generic\&.CluserIterrator< TElemet >\fP, \fBSystemEx\&.Collections\&.Generic\&.ForwardIterrator< T, TCollection >\fP, \fBSystemEx\&.Collections\&.Generic\&.ListIterator< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.RandomAccessIterator< T, TCollection >\fP, and \fBSystemEx\&.NumberRangeIterator< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBForward\fP ()"
.br
.RI "Advances the iterator by one position\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Optional< T > \fBCurrent\fP\fR [get]\fP"
.br
.RI "Gets the element at the current iterator position\&. Returns an \fBOptional<T>\fP that may be empty if the iterator is out of range\&. "
.ti -1c
.RI "long \fBIndex\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the current index of the iterator\&. "
.ti -1c
.RI "bool \fBIsEnd\fP\fR [get]\fP"
.br
.RI "Gets a value indicating whether the iterator has reached the end of the sequence\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a generic iterator over a collection\&. Provides access to the current element and supports advancing the iterator\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The element type\&.
.RE
.PP

.PP
Definition at line \fB30\fP of file \fBIterrator\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SystemEx\&.Collections\&.Generic\&.Iterrator< T >\&.Forward ()"

.PP
Advances the iterator by one position\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.BidirectionalIterator< T, TCollection >\fP, \fBSystemEx\&.Collections\&.Generic\&.CluserIterrator< TElemet >\fP, \fBSystemEx\&.Collections\&.Generic\&.ForwardIterrator< T, TCollection >\fP, \fBSystemEx\&.Collections\&.Generic\&.ListIterator< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.RandomAccessIterator< T, TCollection >\fP, and \fBSystemEx\&.NumberRangeIterator< T >\fP\&.
.PP
Referenced by \fBSystemEx\&.Collections\&.Generic\&.IteratorUtils\&.Distance< T >()\fP, \fBSystemEx\&.Collections\&.Generic\&.IteratorUtils\&.Find< T >()\fP, and \fBSystemEx\&.Collections\&.Generic\&.IteratorUtils\&.ForEach< T >()\fP\&.
.SH "Property Documentation"
.PP 
.SS "Optional<T> SystemEx\&.Collections\&.Generic\&.Iterrator< T >\&.Current\fR [get]\fP"

.PP
Gets the element at the current iterator position\&. Returns an \fBOptional<T>\fP that may be empty if the iterator is out of range\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.BidirectionalIterator< T, TCollection >\fP, \fBSystemEx\&.Collections\&.Generic\&.CluserIterrator< TElemet >\fP, \fBSystemEx\&.Collections\&.Generic\&.ForwardIterrator< T, TCollection >\fP, \fBSystemEx\&.Collections\&.Generic\&.ListIterator< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.ListIterator< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.RandomAccessIterator< T, TCollection >\fP, and \fBSystemEx\&.NumberRangeIterator< T >\fP\&.
.PP
Definition at line \fB51\fP of file \fBIterrator\&.cs\fP\&.
.PP
Referenced by \fBSystemEx\&.Collections\&.Generic\&.IteratorUtils\&.Find< T >()\fP, and \fBSystemEx\&.Collections\&.Generic\&.IteratorUtils\&.ForEach< T >()\fP\&.
.SS "long SystemEx\&.Collections\&.Generic\&.Iterrator< T >\&.Index\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the current index of the iterator\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.BidirectionalIterator< T, TCollection >\fP, \fBSystemEx\&.Collections\&.Generic\&.CluserIterrator< TElemet >\fP, \fBSystemEx\&.Collections\&.Generic\&.ForwardIterrator< T, TCollection >\fP, \fBSystemEx\&.Collections\&.Generic\&.ListIterator< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.RandomAccessIterator< T, TCollection >\fP, and \fBSystemEx\&.NumberRangeIterator< T >\fP\&.
.PP
Definition at line \fB40\fP of file \fBIterrator\&.cs\fP\&.
.PP
Referenced by \fBSystemEx\&.Collections\&.Generic\&.IteratorUtils\&.Distance< T >()\fP, and \fBSystemEx\&.Collections\&.Generic\&.IteratorUtils\&.Find< T >()\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.Iterrator< T >\&.IsEnd\fR [get]\fP"

.PP
Gets a value indicating whether the iterator has reached the end of the sequence\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.BidirectionalIterator< T, TCollection >\fP, \fBSystemEx\&.Collections\&.Generic\&.CluserIterrator< TElemet >\fP, \fBSystemEx\&.Collections\&.Generic\&.ForwardIterrator< T, TCollection >\fP, \fBSystemEx\&.Collections\&.Generic\&.ListIterator< T >\fP, \fBSystemEx\&.Collections\&.Generic\&.RandomAccessIterator< T, TCollection >\fP, and \fBSystemEx\&.NumberRangeIterator< T >\fP\&.
.PP
Definition at line \fB35\fP of file \fBIterrator\&.cs\fP\&.
.PP
Referenced by \fBSystemEx\&.Collections\&.Generic\&.IteratorUtils\&.Find< T >()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
