.TH "SystemEx.Collections.Generic.ForwardIterrator< T, TCollection >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Collections.Generic.ForwardIterrator< T, TCollection > \- A forward-only iterator over a container\&. Supports sequential access starting at a specified index\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemEx\&.Collections\&.Generic\&.Iterrator< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBForward\fP ()"
.br
.RI "Advances the iterator by one position\&. "
.ti -1c
.RI "void \fBForward\fP (long i)"
.br
.RI "Advances the iterator by \fIi\fP  positions\&. Stops early if the end of the container is reached\&. "
.ti -1c
.RI "\fBForwardIterrator\fP (TCollection collection, long index)"
.br
.RI "Initializes a new instance of the \fBForwardIterrator<T, TCollection>\fP struct\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Optional< T > \fBCurrent\fP\fR [get]\fP"
.br
.RI "Gets the element at the current iterator position\&. Returns an \fBOptional<T>\fP that may be empty if the iterator is out of range\&. "
.ti -1c
.RI "long \fBIndex\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the current index of the iterator\&. "
.ti -1c
.RI "bool \fBIsEnd\fP\fR [get]\fP"
.br
.RI "Gets a value indicating whether the iterator has reached the end of the container\&. "
.ti -1c
.RI "bool \fBIsNext\fP\fR [get]\fP"
.br
.RI "Gets a value indicating whether another element is available\&. "
.in -1c
.SH "Detailed Description"
.PP 
A forward-only iterator over a container\&. Supports sequential access starting at a specified index\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The element type\&.
.br
\fITCollection\fP The underlying container type\&.
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fITCollection\fP : \fIIContainer<T>\fP
.PP
Definition at line \fB60\fP of file \fBIterrator\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SystemEx\&.Collections\&.Generic\&.ForwardIterrator< T, TCollection >\&.Forward ()"

.PP
Advances the iterator by one position\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.Iterrator< T >\fP\&.
.PP
Definition at line \fB95\fP of file \fBIterrator\&.cs\fP\&.
.SS "void SystemEx\&.Collections\&.Generic\&.ForwardIterrator< T, TCollection >\&.Forward (long i)"

.PP
Advances the iterator by \fIi\fP  positions\&. Stops early if the end of the container is reached\&. 
.PP
\fBParameters\fP
.RS 4
\fIi\fP The number of positions to advance\&.
.RE
.PP

.PP
Definition at line \fB105\fP of file \fBIterrator\&.cs\fP\&.
.SS "SystemEx\&.Collections\&.Generic\&.ForwardIterrator< T, TCollection >\&.ForwardIterrator (TCollection collection, long index)"

.PP
Initializes a new instance of the \fBForwardIterrator<T, TCollection>\fP struct\&. 
.PP
\fBParameters\fP
.RS 4
\fIcollection\fP The container to iterate over\&.
.br
\fIindex\fP The starting index\&.
.RE
.PP

.PP
Definition at line \fB89\fP of file \fBIterrator\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Optional<T> SystemEx\&.Collections\&.Generic\&.ForwardIterrator< T, TCollection >\&.Current\fR [get]\fP"

.PP
Gets the element at the current iterator position\&. Returns an \fBOptional<T>\fP that may be empty if the iterator is out of range\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.Iterrator< T >\fP\&.
.PP
Definition at line \fB82\fP of file \fBIterrator\&.cs\fP\&.
.SS "long SystemEx\&.Collections\&.Generic\&.ForwardIterrator< T, TCollection >\&.Index\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the current index of the iterator\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.Iterrator< T >\fP\&.
.PP
Definition at line \fB77\fP of file \fBIterrator\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.ForwardIterrator< T, TCollection >\&.IsEnd\fR [get]\fP"

.PP
Gets a value indicating whether the iterator has reached the end of the container\&. 
.PP
Implements \fBSystemEx\&.Collections\&.Generic\&.Iterrator< T >\fP\&.
.PP
Definition at line \fB69\fP of file \fBIterrator\&.cs\fP\&.
.PP
Referenced by \fBForward()\fP, and \fBForward()\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.ForwardIterrator< T, TCollection >\&.IsNext\fR [get]\fP"

.PP
Gets a value indicating whether another element is available\&. 
.PP
Definition at line \fB74\fP of file \fBIterrator\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
