.TH "SystemEx.Collections.Generic.CacheStack< T >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Collections.Generic.CacheStack< T > \- A fixed‑size, backward‑growing stack implementation that operates on a shared cache buffer\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCacheStack\fP (ref \fBCache\fP cache)"
.br
.RI "Initializes a fixed‑size, backward‑growing stack implementation that operates on a shared cache buffer\&. "
.ti -1c
.RI "\fBCacheStack\fP (ref \fBCache\fP cache, uint start, uint end=0)"
.br
.RI "Initializes a fixed‑size, backward‑growing stack implementation that operates on a shared cache buffer\&. "
.ti -1c
.RI "long \fBPeek\fP (byte[] buffer)"
.br
.ti -1c
.RI "bool \fBPeek\fP (ref byte item)"
.br
.RI "Retrieves the top element of the stack without removing it\&. "
.ti -1c
.RI "long \fBPop\fP (byte[] buffer)"
.br
.ti -1c
.RI "bool \fBPop\fP (out byte item)"
.br
.RI "Pops an element from the stack\&. "
.ti -1c
.RI "bool \fBPush\fP (byte element)"
.br
.RI "Pushes an element onto the stack\&. "
.ti -1c
.RI "long \fBPush\fP (byte[] bytes)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsEmpty\fP\fR [get]\fP"
.br
.RI "Indicates whether the main stack is empty\&. "
.ti -1c
.RI "bool \fBIsFull\fP\fR [get]\fP"
.br
.RI "Indicates whether the main stack is full\&. "
.ti -1c
.RI "long \fBSize\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A fixed‑size, backward‑growing stack implementation that operates on a shared cache buffer\&. 
.PP
Definition at line \fB23\fP of file \fBCacheStack\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "SystemEx\&.Collections\&.Generic\&.CacheStack< T >\&.CacheStack (ref \fBCache\fP cache)"

.PP
Initializes a fixed‑size, backward‑growing stack implementation that operates on a shared cache buffer\&. 
.PP
Definition at line \fB59\fP of file \fBCacheStack\&.cs\fP\&.
.SS "SystemEx\&.Collections\&.Generic\&.CacheStack< T >\&.CacheStack (ref \fBCache\fP cache, uint start, uint end = \fR0\fP)"

.PP
Initializes a fixed‑size, backward‑growing stack implementation that operates on a shared cache buffer\&. 
.PP
Definition at line \fB70\fP of file \fBCacheStack\&.cs\fP\&.
.SS "long SystemEx\&.Collections\&.Generic\&.CacheStack< T >\&.Peek (byte[] buffer)"

.PP
Definition at line \fB144\fP of file \fBCacheStack\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.CacheStack< T >\&.Peek (ref byte item)"

.PP
Retrieves the top element of the stack without removing it\&. 
.PP
Definition at line \fB138\fP of file \fBCacheStack\&.cs\fP\&.
.SS "long SystemEx\&.Collections\&.Generic\&.CacheStack< T >\&.Pop (byte[] buffer)"

.PP
Definition at line \fB122\fP of file \fBCacheStack\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.CacheStack< T >\&.Pop (out byte item)"

.PP
Pops an element from the stack\&. 
.PP
Definition at line \fB115\fP of file \fBCacheStack\&.cs\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.CacheStack< T >\&.Push (byte element)"

.PP
Pushes an element onto the stack\&. 
.PP
Definition at line \fB93\fP of file \fBCacheStack\&.cs\fP\&.
.SS "long SystemEx\&.Collections\&.Generic\&.CacheStack< T >\&.Push (byte[] bytes)"

.PP
Definition at line \fB99\fP of file \fBCacheStack\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool SystemEx\&.Collections\&.Generic\&.CacheStack< T >\&.IsEmpty\fR [get]\fP"

.PP
Indicates whether the main stack is empty\&. 
.PP
Definition at line \fB50\fP of file \fBCacheStack\&.cs\fP\&.
.PP
Referenced by \fBPeek()\fP, and \fBPop()\fP\&.
.SS "bool SystemEx\&.Collections\&.Generic\&.CacheStack< T >\&.IsFull\fR [get]\fP"

.PP
Indicates whether the main stack is full\&. 
.PP
Definition at line \fB45\fP of file \fBCacheStack\&.cs\fP\&.
.PP
Referenced by \fBPush()\fP\&.
.SS "long SystemEx\&.Collections\&.Generic\&.CacheStack< T >\&.Size\fR [get]\fP"

.PP
Definition at line \fB52\fP of file \fBCacheStack\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
