.TH "SystemEx.Collections.Generic.IPair< T, TU >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Collections.Generic.IPair< T, TU > \- Represents a two‑element tuple consisting of a key and a value\&. Extends ITuple with strongly typed accessors and comparison helpers for the first and second elements\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemEx\&.Collections\&.Generic\&.ITuple< TKey >\fP\&.
.PP
Inherited by \fBSystemEx\&.Collections\&.Generic\&.Pair< T, TU >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBEqualSecond\fP (TU other)"
.br
.RI "Determines whether the second element equals the specified value\&. "
.in -1c

Public Member Functions inherited from \fBSystemEx\&.Collections\&.Generic\&.ITuple< TKey >\fP
.in +1c
.ti -1c
.RI "bool \fBEqualFirst\fP (TKey key)"
.br
.RI "Determines whether the first element of the tuple is equal to the specified key\&. "
.ti -1c
.RI "Optional< object > \fBGet\fP (int index)"
.br
.RI "Retrieves the vaue at the specified index, not key\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TU \fBSecond\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the second element of the pair\&. "
.in -1c

Properties inherited from \fBSystemEx\&.Collections\&.Generic\&.ITuple< TKey >\fP
.in +1c
.ti -1c
.RI "int \fBCount\fP\fR [get]\fP"
.br
.RI "Gets the number of elements stored in the tuple\&. "
.ti -1c
.RI "TKey \fBFirst\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the first element of the pair\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a two‑element tuple consisting of a key and a value\&. Extends ITuple with strongly typed accessors and comparison helpers for the first and second elements\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The type of the first element (key)\&.
.br
\fITU\fP The type of the second element (value)\&.
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fInotnull\fP
.PP
Definition at line \fB28\fP of file \fBIPair\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SystemEx\&.Collections\&.Generic\&.IPair< T, TU >\&.EqualSecond (TU other)"

.PP
Determines whether the second element equals the specified value\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP The value to compare against the second element\&.
.RE
.PP
\fBReturns\fP
.RS 4
\fRtrue\fP if the second element equals \fIother\fP ; otherwise \fRfalse\fP\&. 
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.Pair< T, TU >\fP\&.
.SH "Property Documentation"
.PP 
.SS "TU SystemEx\&.Collections\&.Generic\&.IPair< T, TU >\&.Second\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the second element of the pair\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.Pair< T, TU >\fP\&.
.PP
Definition at line \fB34\fP of file \fBIPair\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
