.TH "SystemEx.Drawing.ColorGray" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Drawing.ColorGray \- The \fBColorGray\fP class represents a grayscale color using a single floating-point component\&. Only V Drom HSV is used to represent the gray value, where 0 represents black and 1 represents white\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorGray\fP (\fBColorHSV\fP hsv)"
.br
.RI "Creates a new \fBColorGray\fP instance from a \fBColorHSV\fP instance, using the value (V) component of the HSV color\&. "
.ti -1c
.RI "\fBColorGray\fP (float v)"
.br
.RI "Initializes a new instance of the \fBColorGray\fP class with the specified grayscale value\&. "
.ti -1c
.RI "\fBColorGray\fP (float[] x)"
.br
.RI "Initializes a new instance of the \fBColorGray\fP class with the specified grayscale value array\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBGray\fP\fR [get]\fP"
.br
.RI "Gets the grayscale value\&. "
.in -1c
.SH "Detailed Description"
.PP 
The \fBColorGray\fP class represents a grayscale color using a single floating-point component\&. Only V Drom HSV is used to represent the gray value, where 0 represents black and 1 represents white\&. 
.PP
Definition at line \fB24\fP of file \fBColorGray\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Drawing\&.ColorGray\&.ColorGray (float v)"

.PP
Initializes a new instance of the \fBColorGray\fP class with the specified grayscale value\&. 
.PP
\fBParameters\fP
.RS 4
\fIv\fP The grayscale value (0–1)\&.
.RE
.PP

.PP
Definition at line \fB34\fP of file \fBColorGray\&.cs\fP\&.
.SS "SystemEx\&.Drawing\&.ColorGray\&.ColorGray (float[] x)"

.PP
Initializes a new instance of the \fBColorGray\fP class with the specified grayscale value array\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP The grayscale value array (0–1)\&. 
.RE
.PP

.PP
Definition at line \fB39\fP of file \fBColorGray\&.cs\fP\&.
.SS "SystemEx\&.Drawing\&.ColorGray\&.ColorGray (\fBColorHSV\fP hsv)"

.PP
Creates a new \fBColorGray\fP instance from a \fBColorHSV\fP instance, using the value (V) component of the HSV color\&. 
.PP
\fBParameters\fP
.RS 4
\fIhsv\fP 
.RE
.PP

.PP
Definition at line \fB44\fP of file \fBColorGray\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "float SystemEx\&.Drawing\&.ColorGray\&.Gray\fR [get]\fP"

.PP
Gets the grayscale value\&. 
.PP
Definition at line \fB29\fP of file \fBColorGray\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
