.TH "SystemEx.Drawing.IColor< T >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Drawing.IColor< T > \- Represents a color in a specific color space and provides methods for color manipulation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystemEx\&.Drawing\&.ColorHDR\fP, \fBSystemEx\&.Drawing\&.ColorHSV\fP, \fBSystemEx\&.Drawing\&.ColorR16G16B16\fP, and \fBSystemEx\&.Drawing\&.ColorR8G8B8\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "T \fBAddition\fP (float a, float b, float c)"
.br
.RI "Performs component-wise addition of three colors\&. "
.ti -1c
.RI "T \fBAddition\fP (T value)"
.br
.RI "Adds the specified color to this color\&. "
.ti -1c
.RI "T \fBBrightness\fP (float delta)"
.br
.RI "Adjusts the brightness of the color\&. "
.ti -1c
.RI "T \fBDivision\fP (float a, float b, float c)"
.br
.RI "Performs component-wise division of three colors\&. "
.ti -1c
.RI "T \fBDivision\fP (T value)"
.br
.RI "Divides this color by the specified color\&. "
.ti -1c
.RI "T \fBLerp\fP (T value, float amount)"
.br
.RI "Performs linear interpolation between this color and another color\&. "
.ti -1c
.RI "T \fBMultiplication\fP (float a, float b, float c)"
.br
.RI "Performs component-wise multiplication of three colors\&. "
.ti -1c
.RI "T \fBMultiplication\fP (T value)"
.br
.RI "Multiplies this color with the specified color\&. "
.ti -1c
.RI "T \fBSaturation\fP (float delta)"
.br
.RI "Adjusts the saturation of the color\&. "
.ti -1c
.RI "T \fBSubtraction\fP (float a, float b, float c)"
.br
.RI "Performs component-wise subtraction of three colors\&. "
.ti -1c
.RI "T \fBSubtraction\fP (T value)"
.br
.RI "Subtracts the specified color from this color\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a color in a specific color space and provides methods for color manipulation\&. 
.PP
Definition at line \fB25\fP of file \fBIColor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "T SystemEx\&.Drawing\&.IColor< T >\&.Addition (float a, float b, float c)"

.PP
Performs component-wise addition of three colors\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP The first component value\&.
.br
\fIb\fP The second component value\&.
.br
\fIc\fP The third component value\&.
.RE
.PP
\fBReturns\fP
.RS 4
The resulting color\&.
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Drawing\&.ColorHDR\fP, \fBSystemEx\&.Drawing\&.ColorHSV\fP, \fBSystemEx\&.Drawing\&.ColorR16G16B16\fP, and \fBSystemEx\&.Drawing\&.ColorR8G8B8\fP\&.
.SS "T SystemEx\&.Drawing\&.IColor< T >\&.Addition (T value)"

.PP
Adds the specified color to this color\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The color to add\&.
.RE
.PP
\fBReturns\fP
.RS 4
The resulting color\&.
.RE
.PP

.SS "T SystemEx\&.Drawing\&.IColor< T >\&.Brightness (float delta)"

.PP
Adjusts the brightness of the color\&. 
.PP
\fBParameters\fP
.RS 4
\fIdelta\fP The amount to adjust the brightness\&.
.RE
.PP
\fBReturns\fP
.RS 4
The adjusted color\&.
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Drawing\&.ColorHDR\fP, \fBSystemEx\&.Drawing\&.ColorHSV\fP, \fBSystemEx\&.Drawing\&.ColorR16G16B16\fP, and \fBSystemEx\&.Drawing\&.ColorR8G8B8\fP\&.
.SS "T SystemEx\&.Drawing\&.IColor< T >\&.Division (float a, float b, float c)"

.PP
Performs component-wise division of three colors\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP The first component value\&.
.br
\fIb\fP The second component value\&.
.br
\fIc\fP The third component value\&.
.RE
.PP
\fBReturns\fP
.RS 4
The resulting color\&.
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Drawing\&.ColorHDR\fP, \fBSystemEx\&.Drawing\&.ColorHSV\fP, \fBSystemEx\&.Drawing\&.ColorR16G16B16\fP, and \fBSystemEx\&.Drawing\&.ColorR8G8B8\fP\&.
.SS "T SystemEx\&.Drawing\&.IColor< T >\&.Division (T value)"

.PP
Divides this color by the specified color\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The color to divide by\&.
.RE
.PP
\fBReturns\fP
.RS 4
The resulting color\&.
.RE
.PP

.SS "T SystemEx\&.Drawing\&.IColor< T >\&.Lerp (T value, float amount)"

.PP
Performs linear interpolation between this color and another color\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Ziel Value
.br
\fIamount\fP Interpolationsfaktor
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "T SystemEx\&.Drawing\&.IColor< T >\&.Multiplication (float a, float b, float c)"

.PP
Performs component-wise multiplication of three colors\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP The first component value\&.
.br
\fIb\fP The second component value\&.
.br
\fIc\fP The third component value\&.
.RE
.PP
\fBReturns\fP
.RS 4
The resulting color\&.
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Drawing\&.ColorHDR\fP, \fBSystemEx\&.Drawing\&.ColorHSV\fP, \fBSystemEx\&.Drawing\&.ColorR16G16B16\fP, and \fBSystemEx\&.Drawing\&.ColorR8G8B8\fP\&.
.SS "T SystemEx\&.Drawing\&.IColor< T >\&.Multiplication (T value)"

.PP
Multiplies this color with the specified color\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The color to multiply with\&.
.RE
.PP
\fBReturns\fP
.RS 4
The resulting color\&.
.RE
.PP

.SS "T SystemEx\&.Drawing\&.IColor< T >\&.Saturation (float delta)"

.PP
Adjusts the saturation of the color\&. 
.PP
\fBParameters\fP
.RS 4
\fIdelta\fP The amount to adjust the saturation\&.
.RE
.PP
\fBReturns\fP
.RS 4
The adjusted color\&.
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Drawing\&.ColorHDR\fP, \fBSystemEx\&.Drawing\&.ColorHSV\fP, \fBSystemEx\&.Drawing\&.ColorR16G16B16\fP, and \fBSystemEx\&.Drawing\&.ColorR8G8B8\fP\&.
.SS "T SystemEx\&.Drawing\&.IColor< T >\&.Subtraction (float a, float b, float c)"

.PP
Performs component-wise subtraction of three colors\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP The first component value\&.
.br
\fIb\fP The second component value\&.
.br
\fIc\fP The third component value\&.
.RE
.PP
\fBReturns\fP
.RS 4
The resulting color\&.
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Drawing\&.ColorHDR\fP, \fBSystemEx\&.Drawing\&.ColorHSV\fP, \fBSystemEx\&.Drawing\&.ColorR16G16B16\fP, and \fBSystemEx\&.Drawing\&.ColorR8G8B8\fP\&.
.SS "T SystemEx\&.Drawing\&.IColor< T >\&.Subtraction (T value)"

.PP
Subtracts the specified color from this color\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The color to subtract\&.
.RE
.PP
\fBReturns\fP
.RS 4
The resulting color\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
