.TH "SystemEx.Runtime.InteropServices" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Runtime.InteropServices
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNativeHost\fP"
.br
.RI "Provides a high‑level management layer for native modules and their exported functions\&. 
.br
 NativeHost maintains an internal cache of loaded modules to avoid redundant loading operations and to ensure that multiple components referencing the same library share a single module instance\&. 
.br
 It also provides helper methods for resolving native function pointers and converting them into managed delegates\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
