.TH "SystemEx.Runtime.ModuleInfo" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Runtime.ModuleInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits IEquatable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBEquals\fP (\fBModuleInfo\fP other)"
.br
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBoperator!=\fP (\fBModuleInfo\fP a, \fBModuleInfo\fP b)"
.br
.ti -1c
.RI "static bool \fBoperator==\fP (\fBModuleInfo\fP a, \fBModuleInfo\fP b)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBHash\fP\fR [get]\fP"
.br
.ti -1c
.RI "HashType \fBHashType\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBHumanName\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBRealName\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBVersion\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBModuleInfo\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SystemEx\&.Runtime\&.ModuleInfo\&.Equals (\fBModuleInfo\fP other)"

.PP
Definition at line \fB43\fP of file \fBModuleInfo\&.cs\fP\&.
.SS "override bool SystemEx\&.Runtime\&.ModuleInfo\&.Equals (object obj)"

.PP
Definition at line \fB52\fP of file \fBModuleInfo\&.cs\fP\&.
.SS "override int SystemEx\&.Runtime\&.ModuleInfo\&.GetHashCode ()"

.PP
Definition at line \fB58\fP of file \fBModuleInfo\&.cs\fP\&.
.SS "bool SystemEx\&.Runtime\&.ModuleInfo\&.operator!= (\fBModuleInfo\fP a, \fBModuleInfo\fP b)\fR [static]\fP"

.PP
Definition at line \fB60\fP of file \fBModuleInfo\&.cs\fP\&.
.SS "bool SystemEx\&.Runtime\&.ModuleInfo\&.operator== (\fBModuleInfo\fP a, \fBModuleInfo\fP b)\fR [static]\fP"

.PP
Definition at line \fB59\fP of file \fBModuleInfo\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string SystemEx\&.Runtime\&.ModuleInfo\&.Hash\fR [get]\fP"

.PP
Definition at line \fB37\fP of file \fBModuleInfo\&.cs\fP\&.
.SS "HashType SystemEx\&.Runtime\&.ModuleInfo\&.HashType\fR [get]\fP"

.PP
Definition at line \fB39\fP of file \fBModuleInfo\&.cs\fP\&.
.SS "string SystemEx\&.Runtime\&.ModuleInfo\&.HumanName\fR [get]\fP"

.PP
Definition at line \fB35\fP of file \fBModuleInfo\&.cs\fP\&.
.SS "string SystemEx\&.Runtime\&.ModuleInfo\&.RealName\fR [get]\fP"

.PP
Definition at line \fB34\fP of file \fBModuleInfo\&.cs\fP\&.
.SS "string SystemEx\&.Runtime\&.ModuleInfo\&.Version\fR [get]\fP"

.PP
Definition at line \fB41\fP of file \fBModuleInfo\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
