.TH "SystemEx.AI.Tools" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.AI.Tools
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCalculatorTool\fP"
.br
.RI "A basic arithmetic calculator tool\&. "
.ti -1c
.RI "class \fBDateDifferenceTool\fP"
.br
.RI "A tool that calculates the difference between two dates\&. "
.ti -1c
.RI "class \fBDateTimeTool\fP"
.br
.RI "A simple tool that returns the current date and time\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
