.TH "SystemEx.Utils.BitULongSpan.Enumerator" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Utils.BitULongSpan.Enumerator
.SH SYNOPSIS
.br
.PP
.PP
Inherits IEnumerator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void IDisposable\&. \fBDispose\fP ()"
.br
.RI "No resources to dispose\&. "
.ti -1c
.RI "bool \fBMoveNext\fP ()"
.br
.RI "Moves to the next element in the span\&. "
.ti -1c
.RI "void IEnumerator\&. \fBReset\fP ()"
.br
.RI "Resets the enumerator to the initial position\&. Ring mode resets to index 0; other modes reset to -1\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "object IEnumerator\&. \fBCurrent\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool IEnumerator< bool >\&. \fBCurrent\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBCurrent\fP\fR [get, set]\fP"
.br
.RI "Gets the element at the current enumerator position\&. "
.ti -1c
.RI "bool \fBHasNext\fP\fR [get]\fP"
.br
.RI "Indicates whether another element can be produced\&. Ring mode always returns true (infinite iteration)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB60\fP of file \fBBitULongSpan\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void IDisposable\&. SystemEx\&.Utils\&.BitULongSpan\&.Enumerator\&.Dispose ()"

.PP
No resources to dispose\&. 
.PP
Definition at line \fB135\fP of file \fBBitULongSpan\&.cs\fP\&.
.SS "bool SystemEx\&.Utils\&.BitULongSpan\&.Enumerator\&.MoveNext ()"

.PP
Moves to the next element in the span\&. 
.PP
Definition at line \fB101\fP of file \fBBitULongSpan\&.cs\fP\&.
.SS "void IEnumerator\&. SystemEx\&.Utils\&.BitULongSpan\&.Enumerator\&.Reset ()"

.PP
Resets the enumerator to the initial position\&. Ring mode resets to index 0; other modes reset to -1\&. 
.PP
Definition at line \fB130\fP of file \fBBitULongSpan\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "object IEnumerator\&. SystemEx\&.Utils\&.BitULongSpan\&.Enumerator\&.Current\fR [get]\fP"

.PP

.PP
Definition at line \fB124\fP of file \fBBitULongSpan\&.cs\fP\&.
.SS "bool IEnumerator<bool>\&. SystemEx\&.Utils\&.BitULongSpan\&.Enumerator\&.Current\fR [get]\fP"

.PP

.PP
Definition at line \fB121\fP of file \fBBitULongSpan\&.cs\fP\&.
.SS "bool SystemEx\&.Utils\&.BitULongSpan\&.Enumerator\&.Current\fR [get]\fP, \fR [set]\fP"

.PP
Gets the element at the current enumerator position\&. 
.PP
Definition at line \fB115\fP of file \fBBitULongSpan\&.cs\fP\&.
.SS "bool SystemEx\&.Utils\&.BitULongSpan\&.Enumerator\&.HasNext\fR [get]\fP"

.PP
Indicates whether another element can be produced\&. Ring mode always returns true (infinite iteration)\&. 
.PP
Definition at line \fB75\fP of file \fBBitULongSpan\&.cs\fP\&.
.PP
Referenced by \fBMoveNext()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
