.TH "SystemEx.Algorithms.Compute.IThreshold" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Algorithms.Compute.IThreshold \- Represents a threshold evaluator that maps a floating‑point value to a \fBTriple\fP decision based on configured limits\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystemEx\&.Algorithms\&.Compute\&.ThresholdClassifier\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTriple\fP \fBEvaluate\fP (float value)"
.br
.RI "Evaluates the given value and returns a threshold‑based decision\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a threshold evaluator that maps a floating‑point value to a \fBTriple\fP decision based on configured limits\&. 
.PP
Definition at line \fB60\fP of file \fBIClassifier\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTriple\fP SystemEx\&.Algorithms\&.Compute\&.IThreshold\&.Evaluate (float value)"

.PP
Evaluates the given value and returns a threshold‑based decision\&. 
.PP
Implemented in \fBSystemEx\&.Algorithms\&.Compute\&.ThresholdClassifier\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
