.TH "SystemEx.Collections.Generic.ITuple< TKey >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Collections.Generic.ITuple< TKey > \- A lightweight interface for serializable N‑element tuple consisting of strongly typed\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystemEx\&.Collections\&.Generic\&.IPair< T, TU >\fP, \fBSystemEx\&.Collections\&.Generic\&.Quad< TT, TU, TW, TJ >\fP, \fBSystemEx\&.Collections\&.Generic\&.Triple< TT, TU, TW >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Tuple< TKey >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBEqualFirst\fP (TKey key)"
.br
.RI "Determines whether the first element of the tuple is equal to the specified key\&. "
.ti -1c
.RI "Optional< object > \fBGet\fP (int index)"
.br
.RI "Retrieves the vaue at the specified index, not key\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCount\fP\fR [get]\fP"
.br
.RI "Gets the number of elements stored in the tuple\&. "
.ti -1c
.RI "TKey \fBFirst\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the first element of the pair\&. "
.in -1c
.SH "Detailed Description"
.PP 
A lightweight interface for serializable N‑element tuple consisting of strongly typed\&. 
.PP
\fBType Constraints\fP
.TP
\fITKey\fP : \fInotnull\fP
.PP
Definition at line \fB25\fP of file \fBITuple\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SystemEx\&.Collections\&.Generic\&.ITuple< TKey >\&.EqualFirst (TKey key)"

.PP
Determines whether the first element of the tuple is equal to the specified key\&. 
.PP
\fBParameters\fP
.RS 4
\fIkey\fP The value to compare against the first element\&.
.RE
.PP
\fBReturns\fP
.RS 4
\fRtrue\fP if the first element equals \fIkey\fP ; otherwise \fRfalse\fP\&. 
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.Tuple< TKey >\fP\&.
.SS "Optional< object > SystemEx\&.Collections\&.Generic\&.ITuple< TKey >\&.Get (int index)"

.PP
Retrieves the vaue at the specified index, not key\&. 
.PP
\fBParameters\fP
.RS 4
\fIindex\fP The zero-based index of the element\&.
.RE
.PP
\fBReturns\fP
.RS 4
The element at the given index, or \fRnull\fP if the index is out of range\&. 
.RE
.PP

.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.Pair< T, TU >\fP, \fBSystemEx\&.Collections\&.Generic\&.Quad< TT, TU, TW, TJ >\fP, \fBSystemEx\&.Collections\&.Generic\&.Quad< TT, TU, TW, TJ >\fP, \fBSystemEx\&.Collections\&.Generic\&.Triple< TT, TU, TW >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Tuple< TKey >\fP\&.
.SH "Property Documentation"
.PP 
.SS "int SystemEx\&.Collections\&.Generic\&.ITuple< TKey >\&.Count\fR [get]\fP"

.PP
Gets the number of elements stored in the tuple\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.Pair< T, TU >\fP, \fBSystemEx\&.Collections\&.Generic\&.Quad< TT, TU, TW, TJ >\fP, \fBSystemEx\&.Collections\&.Generic\&.Triple< TT, TU, TW >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Tuple< TKey >\fP\&.
.PP
Definition at line \fB34\fP of file \fBITuple\&.cs\fP\&.
.SS "TKey SystemEx\&.Collections\&.Generic\&.ITuple< TKey >\&.First\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the first element of the pair\&. 
.PP
Implemented in \fBSystemEx\&.Collections\&.Generic\&.Pair< T, TU >\fP, \fBSystemEx\&.Collections\&.Generic\&.Quad< TT, TU, TW, TJ >\fP, \fBSystemEx\&.Collections\&.Generic\&.Triple< TT, TU, TW >\fP, and \fBSystemEx\&.Collections\&.Generic\&.Tuple< TKey >\fP\&.
.PP
Definition at line \fB29\fP of file \fBITuple\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
