.TH "SystemEx.Threading.LightSaveQueueEntry< T >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Threading.LightSaveQueueEntry< T > \- Represents a single slot inside a lock‑free LightQueue\&. Each entry stores a sequence number used for producer/consumer coordination, and an optional value of type \fIT\fP \&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBNumber\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the sequence number associated with this slot\&. Volatile operations ensure correct visibility across threads\&. "
.ti -1c
.RI "T? \fBValue\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the value stored in this queue entry\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a single slot inside a lock‑free LightQueue\&. Each entry stores a sequence number used for producer/consumer coordination, and an optional value of type \fIT\fP \&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The type of the value stored in the queue entry\&. 
.RE
.PP

.PP
Definition at line \fB27\fP of file \fBLightSaveQueueEntry\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "long SystemEx\&.Threading\&.LightSaveQueueEntry< T >\&.Number\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the sequence number associated with this slot\&. Volatile operations ensure correct visibility across threads\&. 
.PP
Definition at line \fB46\fP of file \fBLightSaveQueueEntry\&.cs\fP\&.
.SS "T? SystemEx\&.Threading\&.LightSaveQueueEntry< T >\&.Value\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the value stored in this queue entry\&. 
.PP
Definition at line \fB57\fP of file \fBLightSaveQueueEntry\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
