.TH "SystemEx.Runtime.Backend.Loader.IPreloaderBackendConfig" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Runtime.Backend.Loader.IPreloaderBackendConfig
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetPath\fP (Platform platform, \fBArchitecture\fP arch)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IReadOnlyList< \fBModuleInfo\fP > \fBLibarys\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "Version \fBVersion\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB24\fP of file \fBIPreloaderBackendConfig\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "IReadOnlyList<\fBModuleInfo\fP> SystemEx\&.Runtime\&.Backend\&.Loader\&.IPreloaderBackendConfig\&.Libarys\fR [get]\fP"

.PP
Definition at line \fB30\fP of file \fBIPreloaderBackendConfig\&.cs\fP\&.
.SS "string SystemEx\&.Runtime\&.Backend\&.Loader\&.IPreloaderBackendConfig\&.Name\fR [get]\fP"

.PP
Definition at line \fB26\fP of file \fBIPreloaderBackendConfig\&.cs\fP\&.
.SS "Version SystemEx\&.Runtime\&.Backend\&.Loader\&.IPreloaderBackendConfig\&.Version\fR [get]\fP"

.PP
Definition at line \fB28\fP of file \fBIPreloaderBackendConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
