.TH "SystemEx.Collections.Generic.ITraverse< T >" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Collections.Generic.ITraverse< T > \- Defines a traversal operation over a range of elements using a specified direction and index boundaries\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSystemEx\&.Collections\&.Generic\&.Sparsed< T >\fP, and \fBSystemEx\&.Collections\&.Generic\&.TupleMap< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTraverse\fP (\fBTraversMode\fP mode, long startIndex, long endIndex, Action< T > func)"
.br
.RI "Traverses a range of elements using the specified traversal mode\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines a traversal operation over a range of elements using a specified direction and index boundaries\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The type of elements being traversed\&.
.RE
.PP

.PP
Definition at line \fB46\fP of file \fBITraverse\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SystemEx\&.Collections\&.Generic\&.ITraverse< T >\&.Traverse (\fBTraversMode\fP mode, long startIndex, long endIndex, Action< T > func)"

.PP
Traverses a range of elements using the specified traversal mode\&. 
.PP
\fBParameters\fP
.RS 4
\fImode\fP The traversal direction\&.
.br
\fIstartIndex\fP The starting index (inclusive)\&.
.br
\fIendIndex\fP The ending index (exclusive)\&.
.br
\fIfunc\fP The action to apply to each visited element\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
