.TH "SystemEx.Numeric.Vec2r" 3 "Version 0.95.6023-rc4 Lacking" "SystemEX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemEx.Numeric.Vec2r \- Represents a 2‑component \fBRatio\fP vector\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IComparable, \fBSystemEx\&.IComparableEx< T >\fP, IComparable, IEquatable, and \fBSystemEx\&.Hash\&.IHashable< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBCompareTo\fP (object? obj)"
.br
.RI "Compares this vector to another object\&. "
.ti -1c
.RI "\fBCompareResult\fP \fBCompareTo\fP (\fBVec2r\fP a)"
.br
.RI "Compares two vectors lexicographically\&. "
.ti -1c
.RI "int IComparable< \fBVec2r\fP >\&. \fBCompareTo\fP (\fBVec2r\fP other)"
.br
.ti -1c
.RI "override bool \fBEquals\fP (object? obj)"
.br
.RI "Determines whether this instance is equal to another object\&. "
.ti -1c
.RI "bool \fBEquals\fP (\fBVec2r\fP other)"
.br
.RI "Determines whether this instance is equal to another \fBVec2r\fP value, using the same semantics as the \fBoperator ==(Vec2r,Vec2r)\fP\&. "
.ti -1c
.RI "\fBRatio\fP \fBGet\fP (int index)"
.br
.RI "Gets the component at the specified index\&. "
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.RI "Computes a hash code for this object\&. "
.ti -1c
.RI "FixedVector< byte > \fBToBytes\fP ()"
.br
.RI "Convert To Byte\&. "
.ti -1c
.RI "\fBVec2r\fP ()"
.br
.RI "Initializes a new vector with both components set to One\&. "
.ti -1c
.RI "\fBVec2r\fP (\fBRatio\fP _f)"
.br
.RI "Initializes a new vector with both components set to the same scalar value\&. "
.ti -1c
.RI "\fBVec2r\fP (\fBRatio\fP _x, \fBRatio\fP _y)"
.br
.RI "Initializes a new vector with the specified X and Y components\&. "
.ti -1c
.RI "\fBVec2r\fP (\fBRatio\fP[] lpvec)"
.br
.RI "Initializes a new vector from an \fBRatio\fP array of length 2\&. "
.ti -1c
.RI "\fBVec2r\fP (Vec2r vec)"
.br
.RI "Initializes a new vector by copying the components of another vector\&. "
.in -1c

Public Member Functions inherited from \fBSystemEx\&.IComparableEx< T >\fP
.in +1c
.ti -1c
.RI "\fBCompareResult\fP \fBCompareTo\fP (T a)"
.br
.RI "Compares this instance with the specified value and returns a \fBCompareResult\fP describing the relationship between them\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRatio\fP \fBDot\fP (\fBVec2r\fP v1, \fBVec2r\fP v2)"
.br
.RI "Computes the dot product of two vectors\&. "
.ti -1c
.RI "static \fBVec2r\fP \fBInterpolateCoords\fP (\fBVec2r\fP v1, \fBVec2r\fP v2, int p)"
.br
.RI "Linearly interpolates between two vectors using the parameter \fIp\fP \&. "
.ti -1c
.RI "static \fBVec2r\fP \fBInterpolateCoords\fP (\fBVec2r\fP v1, \fBVec2r\fP v2, \fBRatio\fP p)"
.br
.RI "Linearly interpolates between two vectors using the parameter \fIp\fP \&. "
.ti -1c
.RI "static \fBRatio\fP \fBLenght\fP (\fBVec2r\fP v)"
.br
.RI "Computes the squared length of the vector (x² + y²)\&. "
.ti -1c
.RI "static bool \fBNearEqual\fP (\fBVec2r\fP v1, \fBVec2r\fP v2, \fBRatio\fP epsilon)"
.br
.RI "Checks whether two vectors are approximately equal\&. "
.ti -1c
.RI "static bool \fBoperator!=\fP (\fBRatio\fP a, \fBVec2r\fP b)"
.br
.RI "Determines whether a scalar differs from any component of the vector\&. "
.ti -1c
.RI "static bool \fBoperator!=\fP (\fBVec2r\fP a, \fBRatio\fP b)"
.br
.RI "Determines whether any vector component differs from the scalar\&. "
.ti -1c
.RI "static bool \fBoperator!=\fP (\fBVec2r\fP a, \fBVec2r\fP b)"
.br
.RI "Determines whether two vectors differ in any component\&. "
.ti -1c
.RI "static \fBVec2r\fP \fBoperator*\fP (\fBRatio\fP a, \fBVec2r\fP b)"
.br
.RI "Multiplies a scalar with each component of the vector\&. "
.ti -1c
.RI "static \fBVec2r\fP \fBoperator*\fP (\fBVec2r\fP a, \fBRatio\fP b)"
.br
.RI "Multiplies both components of the vector by a scalar\&. "
.ti -1c
.RI "static \fBVec2r\fP \fBoperator*\fP (\fBVec2r\fP a, \fBVec2r\fP b)"
.br
.RI "Multiplies two vectors component‑wise\&. "
.ti -1c
.RI "static \fBVec2r\fP \fBoperator+\fP (\fBRatio\fP a, \fBVec2r\fP b)"
.br
.RI "Adds a scalar to each component of the vector\&. "
.ti -1c
.RI "static \fBVec2r\fP \fBoperator+\fP (\fBVec2r\fP a, \fBRatio\fP b)"
.br
.RI "Adds a scalar to both components of the vector\&. "
.ti -1c
.RI "static \fBVec2r\fP \fBoperator+\fP (\fBVec2r\fP a, \fBVec2r\fP b)"
.br
.RI "Adds two vectors component‑wise\&. "
.ti -1c
.RI "static \fBVec2r\fP \fBoperator\-\fP (\fBRatio\fP a, \fBVec2r\fP b)"
.br
.RI "Subtracts each component of the vector from a scalar\&. "
.ti -1c
.RI "static \fBVec2r\fP \fBoperator\-\fP (\fBVec2r\fP a, \fBRatio\fP b)"
.br
.RI "Subtracts a scalar from both components of the vector\&. "
.ti -1c
.RI "static \fBVec2r\fP \fBoperator\-\fP (\fBVec2r\fP a, \fBVec2r\fP b)"
.br
.RI "Subtracts two vectors component‑wise\&. "
.ti -1c
.RI "static \fBVec2r\fP \fBoperator/\fP (\fBRatio\fP a, \fBVec2r\fP b)"
.br
.RI "Divides a scalar by each component of the vector\&. "
.ti -1c
.RI "static \fBVec2r\fP \fBoperator/\fP (\fBVec2r\fP a, \fBRatio\fP b)"
.br
.RI "Divides both components of the vector by a scalar\&. "
.ti -1c
.RI "static \fBVec2r\fP \fBoperator/\fP (\fBVec2r\fP a, \fBVec2r\fP b)"
.br
.RI "Divides two vectors component‑wise\&. "
.ti -1c
.RI "static bool \fBoperator<\fP (\fBRatio\fP a, \fBVec2r\fP b)"
.br
.RI "Determines whether a scalar is strictly less than both vector components\&. "
.ti -1c
.RI "static bool \fBoperator<\fP (\fBVec2r\fP a, \fBRatio\fP b)"
.br
.RI "Determines whether both vector components are strictly less than the scalar\&. "
.ti -1c
.RI "static bool \fBoperator<\fP (\fBVec2r\fP a, \fBVec2r\fP b)"
.br
.RI "Determines whether all components of \fIa\fP  are strictly less than those of \fIb\fP \&. "
.ti -1c
.RI "static bool \fBoperator<=\fP (\fBRatio\fP a, \fBVec2r\fP b)"
.br
.RI "Determines whether a scalar is less than or equal to both vector components\&. "
.ti -1c
.RI "static bool \fBoperator<=\fP (\fBVec2r\fP a, \fBRatio\fP b)"
.br
.RI "Determines whether both vector components are less than or equal to the scalar\&. "
.ti -1c
.RI "static bool \fBoperator<=\fP (\fBVec2r\fP a, \fBVec2r\fP b)"
.br
.RI "Determines whether all components of \fIa\fP  are less than or equal to those of \fIb\fP \&. "
.ti -1c
.RI "static bool \fBoperator==\fP (\fBRatio\fP a, \fBVec2r\fP b)"
.br
.RI "Determines whether a scalar equals both components of the vector\&. "
.ti -1c
.RI "static bool \fBoperator==\fP (\fBVec2r\fP a, \fBRatio\fP b)"
.br
.RI "Determines whether both vector components equal the scalar\&. "
.ti -1c
.RI "static bool \fBoperator==\fP (\fBVec2r\fP a, \fBVec2r\fP b)"
.br
.RI "Determines whether two vectors are equal component‑wise\&. "
.ti -1c
.RI "static bool \fBoperator>\fP (\fBRatio\fP a, \fBVec2r\fP b)"
.br
.RI "Determines whether a scalar is strictly greater than both vector components\&. "
.ti -1c
.RI "static bool \fBoperator>\fP (\fBVec2r\fP a, \fBRatio\fP b)"
.br
.RI "Determines whether both vector components are strictly greater than the scalar\&. "
.ti -1c
.RI "static bool \fBoperator>\fP (\fBVec2r\fP a, \fBVec2r\fP b)"
.br
.RI "Determines whether all components of \fIa\fP  are strictly greater than those of \fIb\fP \&. "
.ti -1c
.RI "static bool \fBoperator>=\fP (\fBRatio\fP a, \fBVec2r\fP b)"
.br
.RI "Determines whether a scalar is greater than or equal to both vector components\&. "
.ti -1c
.RI "static bool \fBoperator>=\fP (\fBVec2r\fP a, \fBRatio\fP b)"
.br
.RI "Determines whether both vector components are greater than or equal to the scalar\&. "
.ti -1c
.RI "static bool \fBoperator>=\fP (\fBVec2r\fP a, \fBVec2r\fP b)"
.br
.RI "Determines whether all components of \fIa\fP  are greater than or equal to those of \fIb\fP \&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBVec2r\fP \fBMax\fP = new \fBVec2r\fP(\fBRatio\&.MaxValue\fP)"
.br
.RI "A vector with both components set to \fBRatio\&.MaxValue\fP\&. "
.ti -1c
.RI "static readonly \fBVec2r\fP \fBMin\fP = new \fBVec2r\fP(\fBRatio\&.MinValue\fP)"
.br
.RI "A vector with both components set to \fBRatio\&.MinValue\fP\&. "
.ti -1c
.RI "static readonly \fBVec2r\fP \fBNegativeOne\fP = new \fBVec2r\fP(\-\fBRatio\&.One\fP)"
.br
.RI "A vector with both components set to negative one (-Ratio\&.One, -Ratio\&.One)\&. "
.ti -1c
.RI "static readonly \fBVec2r\fP \fBOne\fP = new \fBVec2r\fP(\fBRatio\&.One\fP)"
.br
.RI "A vector with both components set to one (\fBRatio\&.One\fP, \fBRatio\&.One\fP)\&. "
.ti -1c
.RI "static readonly \fBVec2r\fP \fBZero\fP = new \fBVec2r\fP(\fBRatio\&.Zero\fP)"
.br
.RI "A vector with both components set to zero (\fBRatio\&.Zero\fP, \fBRatio\&.Zero\fP)\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCount\fP\fR [get]\fP"
.br
.RI "Gets the number of components in this vector (always 2)\&. "
.ti -1c
.RI "\fBRatio\fP \fBX\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the X component of the vector\&. "
.ti -1c
.RI "\fBRatio\fP \fBY\fP\fR [get, set]\fP"
.br
.RI "Gets or sets the Y component of the vector\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a 2‑component \fBRatio\fP vector\&. 

\fBVec2r\fP is a lightweight numeric type used throughout \fBSystemEx\fP for geometry, math utilities, device operations, and compute kernels\&. It stores two \fBRatio\fP values (\fRX\fP and \fRY\fP)\&. 

.PP
The struct is annotated with \fBHashAlgorithmAttribute\fP to enable attribute‑driven hashing via HashFactory\&. 
.br
 \fBBernsteinHash\fP is used because it is fast, byte‑linear, and ideal for small fixed‑size numeric types such as vectors\&. 

.PP
\fBVec2r\fP implements multiple comparison and hashing interfaces: 
.PD 0
.IP "\(bu" 2
IComparable and IComparable<T> for ordering 
.IP "\(bu" 2
IEquatable<T> for equality checks 
.IP "\(bu" 2
\fBIHashable<T>\fP for deterministic byte‑level hashing 
.PP
This makes the type suitable for use in dictionaries, sorting, spatial hashing\&. 
.PP
Definition at line \fB60\fP of file \fBvec2r\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SystemEx\&.Numeric\&.Vec2r\&.Vec2r ()"

.PP
Initializes a new vector with both components set to One\&. 
.PP
Definition at line \fB107\fP of file \fBvec2r\&.cs\fP\&.
.PP
Referenced by \fBCompareTo()\fP, \fBCompareTo()\fP, \fBDot()\fP, \fBEquals()\fP, \fBEquals()\fP, \fBInterpolateCoords()\fP, \fBInterpolateCoords()\fP, \fBLenght()\fP, \fBNearEqual()\fP, \fBoperator!=()\fP, \fBoperator!=()\fP, \fBoperator!=()\fP, \fBoperator*()\fP, \fBoperator*()\fP, \fBoperator*()\fP, \fBoperator+()\fP, \fBoperator+()\fP, \fBoperator+()\fP, \fBoperator\-()\fP, \fBoperator\-()\fP, \fBoperator\-()\fP, \fBoperator/()\fP, \fBoperator/()\fP, \fBoperator/()\fP, \fBoperator<()\fP, \fBoperator<()\fP, \fBoperator<()\fP, \fBoperator<=()\fP, \fBoperator<=()\fP, \fBoperator<=()\fP, \fBoperator==()\fP, \fBoperator==()\fP, \fBoperator==()\fP, \fBoperator>()\fP, \fBoperator>()\fP, \fBoperator>()\fP, \fBoperator>=()\fP, \fBoperator>=()\fP, \fBoperator>=()\fP, and \fBVec2r()\fP\&.
.SS "SystemEx\&.Numeric\&.Vec2r\&.Vec2r (\fBRatio\fP _x, \fBRatio\fP _y)"

.PP
Initializes a new vector with the specified X and Y components\&. 
.PP
\fBParameters\fP
.RS 4
\fI_x\fP The X component\&.
.br
\fI_y\fP The Y component\&.
.RE
.PP

.PP
Definition at line \fB115\fP of file \fBvec2r\&.cs\fP\&.
.SS "SystemEx\&.Numeric\&.Vec2r\&.Vec2r (\fBRatio\fP _f)"

.PP
Initializes a new vector with both components set to the same scalar value\&. 
.PP
\fBParameters\fP
.RS 4
\fI_f\fP The scalar value assigned to both components\&.
.RE
.PP

.PP
Definition at line \fB124\fP of file \fBvec2r\&.cs\fP\&.
.SS "SystemEx\&.Numeric\&.Vec2r\&.Vec2r (Vec2r vec)"

.PP
Initializes a new vector by copying the components of another vector\&. 
.PP
\fBParameters\fP
.RS 4
\fIvec\fP The vector to copy\&.
.RE
.PP

.PP
Definition at line \fB132\fP of file \fBvec2r\&.cs\fP\&.
.SS "SystemEx\&.Numeric\&.Vec2r\&.Vec2r (\fBRatio\fP[] lpvec)"

.PP
Initializes a new vector from an \fBRatio\fP array of length 2\&. 
.PP
\fBParameters\fP
.RS 4
\fIlpvec\fP An array containing two \fBRatio\fP values\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIIndexOutOfRangeException\fP Thrown if the array does not contain at least two elements\&. 
.RE
.PP

.PP
Definition at line \fB144\fP of file \fBvec2r\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int SystemEx\&.Numeric\&.Vec2r\&.CompareTo (object? obj)"

.PP
Compares this vector to another object\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP The object to compare with\&.
.RE
.PP
\fBReturns\fP
.RS 4
A signed integer indicating the comparison result\&. 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentException\fP Thrown if \fIobj\fP  is not a \fBVec2r\fP\&. 
.RE
.PP

.PP
Definition at line \fB215\fP of file \fBvec2r\&.cs\fP\&.
.PP
Referenced by \fBCompareTo()\fP\&.
.SS "\fBCompareResult\fP SystemEx\&.Numeric\&.Vec2r\&.CompareTo (\fBVec2r\fP a)"

.PP
Compares two vectors lexicographically\&. 
.PP
Definition at line \fB224\fP of file \fBvec2r\&.cs\fP\&.
.SS "int IComparable< \fBVec2r\fP >\&. SystemEx\&.Numeric\&.Vec2r\&.CompareTo (\fBVec2r\fP other)"

.PP
Definition at line \fB263\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBRatio\fP SystemEx\&.Numeric\&.Vec2r\&.Dot (\fBVec2r\fP v1, \fBVec2r\fP v2)\fR [static]\fP"

.PP
Computes the dot product of two vectors\&. 
.PP
\fBParameters\fP
.RS 4
\fIv1\fP The first vector\&.
.br
\fIv2\fP The second vector\&.
.RE
.PP
\fBReturns\fP
.RS 4
The dot product as a \fBRatio\fP\&.
.RE
.PP

.PP
Definition at line \fB175\fP of file \fBvec2r\&.cs\fP\&.
.SS "override bool SystemEx\&.Numeric\&.Vec2r\&.Equals (object? obj)"

.PP
Determines whether this instance is equal to another object\&. The object is considered equal if it is a \fBVec2r\fP and compares equal using \fBEquals(Vec2r)\fP\&.

.PP
\fBParameters\fP
.RS 4
\fIobj\fP The object to compare with\&.
.RE
.PP
\fBReturns\fP
.RS 4
\fRtrue\fP if \fIobj\fP  is a \fBVec2r\fP and equal to this instance; otherwise \fRfalse\fP\&. 
.RE
.PP

.PP
Definition at line \fB258\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.Equals (\fBVec2r\fP other)"

.PP
Determines whether this instance is equal to another \fBVec2r\fP value, using the same semantics as the \fBoperator ==(Vec2r,Vec2r)\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP The value to compare with\&.
.RE
.PP
\fBReturns\fP
.RS 4
\fRtrue\fP if the values are equal; otherwise \fRfalse\fP\&. 
.RE
.PP

.PP
Definition at line \fB243\fP of file \fBvec2r\&.cs\fP\&.
.PP
Referenced by \fBEquals()\fP\&.
.SS "\fBRatio\fP SystemEx\&.Numeric\&.Vec2r\&.Get (int index)"

.PP
Gets the component at the specified index\&. 
.PP
\fBParameters\fP
.RS 4
\fIindex\fP The component index (0 for X, 1 for Y)\&.
.RE
.PP
\fBReturns\fP
.RS 4
The requested component\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fIArgumentOutOfRangeException\fP Thrown if the index is outside the valid range\&. 
.RE
.PP

.PP
Definition at line \fB157\fP of file \fBvec2r\&.cs\fP\&.
.SS "override int SystemEx\&.Numeric\&.Vec2r\&.GetHashCode ()"

.PP
Computes a hash code for this object\&. The primary hash is generated using HashFactory and the \fBHashAlgorithmAttribute\fP applied to this struct\&. 
.br
 If hashing fails (rare), a fallback XOR‑based hash is used\&. 
.PP
Definition at line \fB487\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.InterpolateCoords (\fBVec2r\fP v1, \fBVec2r\fP v2, int p)\fR [static]\fP"

.PP
Linearly interpolates between two vectors using the parameter \fIp\fP \&. 
.PP
\fBParameters\fP
.RS 4
\fIv1\fP The start vector\&.
.br
\fIv2\fP The end vector\&.
.br
\fIp\fP The interpolation factor Values between 0 and 1 (values outside this range perform extrapolation) 
.RE
.PP
\fBReturns\fP
.RS 4
The interpolated vector\&.
.RE
.PP

.PP
Definition at line \fB188\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.InterpolateCoords (\fBVec2r\fP v1, \fBVec2r\fP v2, \fBRatio\fP p)\fR [static]\fP"

.PP
Linearly interpolates between two vectors using the parameter \fIp\fP \&. 
.PP
\fBParameters\fP
.RS 4
\fIv1\fP The start vector\&.
.br
\fIv2\fP The end vector\&.
.br
\fIp\fP The interpolation factor Values between 0 and 1 (values outside this range perform extrapolation) 
.RE
.PP
\fBReturns\fP
.RS 4
The interpolated vector\&.
.RE
.PP

.PP
Definition at line \fB201\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBRatio\fP SystemEx\&.Numeric\&.Vec2r\&.Lenght (\fBVec2r\fP v)\fR [static]\fP"

.PP
Computes the squared length of the vector (x² + y²)\&. 
.PP
\fBParameters\fP
.RS 4
\fIv\fP The vector whose length is computed\&.
.RE
.PP
\fBReturns\fP
.RS 4
The squared length as a \fBRatio\fP\&.
.RE
.PP

.PP
Definition at line \fB167\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.NearEqual (\fBVec2r\fP v1, \fBVec2r\fP v2, \fBRatio\fP epsilon)\fR [static]\fP"

.PP
Checks whether two vectors are approximately equal\&. 
.PP
Definition at line \fB270\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator!= (\fBRatio\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Determines whether a scalar differs from any component of the vector\&. 
.PP
Definition at line \fB405\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator!= (\fBVec2r\fP a, \fBRatio\fP b)\fR [static]\fP"

.PP
Determines whether any vector component differs from the scalar\&. 
.PP
Definition at line \fB447\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator!= (\fBVec2r\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Determines whether two vectors differ in any component\&. 
.PP
Definition at line \fB367\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.operator* (\fBRatio\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Multiplies a scalar with each component of the vector\&. 
.PP
Definition at line \fB349\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.operator* (\fBVec2r\fP a, \fBRatio\fP b)\fR [static]\fP"

.PP
Multiplies both components of the vector by a scalar\&. 
.PP
Definition at line \fB331\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.operator* (\fBVec2r\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Multiplies two vectors component‑wise\&. 
.PP
Definition at line \fB307\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.operator+ (\fBRatio\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Adds a scalar to each component of the vector\&. 
.PP
Definition at line \fB355\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.operator+ (\fBVec2r\fP a, \fBRatio\fP b)\fR [static]\fP"

.PP
Adds a scalar to both components of the vector\&. 
.PP
Definition at line \fB313\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.operator+ (\fBVec2r\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Adds two vectors component‑wise\&. 
.PP
Definition at line \fB289\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.operator\- (\fBRatio\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Subtracts each component of the vector from a scalar\&. 
.PP
Definition at line \fB337\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.operator\- (\fBVec2r\fP a, \fBRatio\fP b)\fR [static]\fP"

.PP
Subtracts a scalar from both components of the vector\&. 
.PP
Definition at line \fB319\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.operator\- (\fBVec2r\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Subtracts two vectors component‑wise\&. 
.PP
Definition at line \fB295\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.operator/ (\fBRatio\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Divides a scalar by each component of the vector\&. 
.PP
Definition at line \fB343\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.operator/ (\fBVec2r\fP a, \fBRatio\fP b)\fR [static]\fP"

.PP
Divides both components of the vector by a scalar\&. 
.PP
Definition at line \fB325\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.operator/ (\fBVec2r\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Divides two vectors component‑wise\&. 
.PP
Definition at line \fB301\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator< (\fBRatio\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Determines whether a scalar is strictly less than both vector components\&. 
.PP
Definition at line \fB426\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator< (\fBVec2r\fP a, \fBRatio\fP b)\fR [static]\fP"

.PP
Determines whether both vector components are strictly less than the scalar\&. 
.PP
Definition at line \fB468\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator< (\fBVec2r\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Determines whether all components of \fIa\fP  are strictly less than those of \fIb\fP \&. 
.PP
Definition at line \fB385\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator<= (\fBRatio\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Determines whether a scalar is less than or equal to both vector components\&. 
.PP
Definition at line \fB412\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator<= (\fBVec2r\fP a, \fBRatio\fP b)\fR [static]\fP"

.PP
Determines whether both vector components are less than or equal to the scalar\&. 
.PP
Definition at line \fB454\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator<= (\fBVec2r\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Determines whether all components of \fIa\fP  are less than or equal to those of \fIb\fP \&. 
.PP
Definition at line \fB373\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator== (\fBRatio\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Determines whether a scalar equals both components of the vector\&. 
.PP
Definition at line \fB398\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator== (\fBVec2r\fP a, \fBRatio\fP b)\fR [static]\fP"

.PP
Determines whether both vector components equal the scalar\&. 
.PP
Definition at line \fB440\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator== (\fBVec2r\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Determines whether two vectors are equal component‑wise\&. 
.PP
Definition at line \fB361\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator> (\fBRatio\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Determines whether a scalar is strictly greater than both vector components\&. 
.PP
Definition at line \fB433\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator> (\fBVec2r\fP a, \fBRatio\fP b)\fR [static]\fP"

.PP
Determines whether both vector components are strictly greater than the scalar\&. 
.PP
Definition at line \fB475\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator> (\fBVec2r\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Determines whether all components of \fIa\fP  are strictly greater than those of \fIb\fP \&. 
.PP
Definition at line \fB391\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator>= (\fBRatio\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Determines whether a scalar is greater than or equal to both vector components\&. 
.PP
Definition at line \fB419\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator>= (\fBVec2r\fP a, \fBRatio\fP b)\fR [static]\fP"

.PP
Determines whether both vector components are greater than or equal to the scalar\&. 
.PP
Definition at line \fB461\fP of file \fBvec2r\&.cs\fP\&.
.SS "bool SystemEx\&.Numeric\&.Vec2r\&.operator>= (\fBVec2r\fP a, \fBVec2r\fP b)\fR [static]\fP"

.PP
Determines whether all components of \fIa\fP  are greater than or equal to those of \fIb\fP \&. 
.PP
Definition at line \fB379\fP of file \fBvec2r\&.cs\fP\&.
.SS "FixedVector< byte > SystemEx\&.Numeric\&.Vec2r\&.ToBytes ()"

.PP
Convert To Byte\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Implements \fBSystemEx\&.Hash\&.IHashable< T >\fP\&.
.PP
Definition at line \fB278\fP of file \fBvec2r\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.Max = new \fBVec2r\fP(\fBRatio\&.MaxValue\fP)\fR [static]\fP"

.PP
A vector with both components set to \fBRatio\&.MaxValue\fP\&. 
.PP
Definition at line \fB92\fP of file \fBvec2r\&.cs\fP\&.
.SS "readonly \fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.Min = new \fBVec2r\fP(\fBRatio\&.MinValue\fP)\fR [static]\fP"

.PP
A vector with both components set to \fBRatio\&.MinValue\fP\&. 
.PP
Definition at line \fB87\fP of file \fBvec2r\&.cs\fP\&.
.SS "readonly \fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.NegativeOne = new \fBVec2r\fP(\-\fBRatio\&.One\fP)\fR [static]\fP"

.PP
A vector with both components set to negative one (-Ratio\&.One, -Ratio\&.One)\&. 
.PP
Definition at line \fB82\fP of file \fBvec2r\&.cs\fP\&.
.SS "readonly \fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.One = new \fBVec2r\fP(\fBRatio\&.One\fP)\fR [static]\fP"

.PP
A vector with both components set to one (\fBRatio\&.One\fP, \fBRatio\&.One\fP)\&. 
.PP
Definition at line \fB77\fP of file \fBvec2r\&.cs\fP\&.
.SS "readonly \fBVec2r\fP SystemEx\&.Numeric\&.Vec2r\&.Zero = new \fBVec2r\fP(\fBRatio\&.Zero\fP)\fR [static]\fP"

.PP
A vector with both components set to zero (\fBRatio\&.Zero\fP, \fBRatio\&.Zero\fP)\&. 
.PP
Definition at line \fB72\fP of file \fBvec2r\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int SystemEx\&.Numeric\&.Vec2r\&.Count\fR [get]\fP"

.PP
Gets the number of components in this vector (always 2)\&. 
.PP
Definition at line \fB67\fP of file \fBvec2r\&.cs\fP\&.
.PP
Referenced by \fBGet()\fP\&.
.SS "\fBRatio\fP SystemEx\&.Numeric\&.Vec2r\&.X\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the X component of the vector\&. 
.PP
Definition at line \fB97\fP of file \fBvec2r\&.cs\fP\&.
.SS "\fBRatio\fP SystemEx\&.Numeric\&.Vec2r\&.Y\fR [get]\fP, \fR [set]\fP"

.PP
Gets or sets the Y component of the vector\&. 
.PP
Definition at line \fB102\fP of file \fBvec2r\&.cs\fP\&.
.PP
Referenced by \fBEquals()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SystemEX from the source code\&.
