var searchData=
[
  ['scalar_20types_0',['Scalar Types',['../index.html#scalar-types',1,'']]],
  ['scheduled_20for_20removal_20in_20version_200_2060_1',['Deprecated – Hashable (scheduled for removal in version 0.60)',['../df/d71/a02247.html#deprecated--hashable-scheduled-for-removal-in-version-060',1,'']]],
  ['so_20many_20numeric_20types_2',['Why are there so many numeric types?',['../d4/d48/a02250.html#why-are-there-so-many-numeric-types',1,'']]],
  ['split_20into_20multiple_20classes_20instead_20of_20one_20big_20list_3',['Why are the colors split into multiple classes instead of one big list?',['../d4/d48/a02250.html#why-are-the-colors-split-into-multiple-classes-instead-of-one-big-list',1,'']]],
  ['status_4',['🚧 Status',['../index.html#autotoc_md-status',1,'']]],
  ['structures_5',['Why does SystemEx contain duplicated structures?',['../d4/d48/a02250.html#why-does-systemex-contain-duplicated-structures',1,'']]],
  ['subsystem_6',['Why does SystemEx include an interop subsystem?',['../d4/d48/a02250.html#why-does-systemex-include-an-interop-subsystem',1,'']]],
  ['subsystem_20custom_7',['Why is the random subsystem custom?',['../d4/d48/a02250.html#why-is-the-random-subsystem-custom',1,'']]],
  ['systemex_8',['Who maintains SystemEx?',['../d4/d48/a02250.html#who-maintains-systemex',1,'']]],
  ['systemex_20ai_9',['Added – SystemEx.AI',['../df/d71/a02247.html#added--systemexai',1,'']]],
  ['systemex_20algorithms_10',['SystemEx Algorithms',['../index.html#autotoc_md-systemexalgorithms',1,'🧮 SystemEx.Algorithms'],['../da/d14/a02245.html#systemexalgorithms',1,'SystemEx.Algorithms']]],
  ['systemex_20architecture_20overview_11',['🏛️ SystemEx Architecture Overview',['../da/d14/a02245.html',1,'']]],
  ['systemex_20authors_12',['👤 SystemEx Authors',['../de/db2/a02246.html',1,'']]],
  ['systemex_20avoid_20net_20task_20and_20threadpool_13',['Why does SystemEx avoid .NET Task and ThreadPool?',['../d4/d48/a02250.html#why-does-systemex-avoid-net-task-and-threadpool',1,'']]],
  ['systemex_20base_20layer_14',['SystemEx Base Layer',['../index.html#autotoc_md-systemex-base-layer',1,'🧱 SystemEx (Base Layer)'],['../da/d14/a02245.html#systemex-base-layer',1,'SystemEx (Base Layer)']]],
  ['systemex_20changelog_15',['📝 SystemEx Changelog',['../df/d71/a02247.html',1,'']]],
  ['systemex_20code_20of_20conduct_16',['📜 SystemEx Code of Conduct',['../dc/de2/a02248.html',1,'']]],
  ['systemex_20collections_20generic_17',['SystemEx Collections Generic',['../index.html#autotoc_md-systemexcollectionsgeneric',1,'📚 SystemEx.Collections.Generic'],['../da/d14/a02245.html#systemexcollectionsgeneric',1,'SystemEx.Collections.Generic']]],
  ['systemex_20collections_20model_18',['SystemEx Collections Model',['../index.html#autotoc_md-systemexcollectionsmodel',1,'🧬 SystemEx.Collections.Model'],['../da/d14/a02245.html#systemexcollectionsmodel',1,'SystemEx.Collections.Model']]],
  ['systemex_20contain_20duplicated_20structures_19',['Why does SystemEx contain duplicated structures?',['../d4/d48/a02250.html#why-does-systemex-contain-duplicated-structures',1,'']]],
  ['systemex_20contributing_20',['🤝 SystemEx Contributing',['../dd/dc3/a02249.html',1,'']]],
  ['systemex_20drawing_21',['SystemEx Drawing',['../index.html#autotoc_md-systemexdrawing',1,'🎨 SystemEx.Drawing'],['../da/d14/a02245.html#systemexdrawing',1,'SystemEx.Drawing']]],
  ['systemex_20framework_22',['📘 SystemEx Framework',['../index.html',1,'']]],
  ['systemex_20hash_23',['SystemEx Hash',['../index.html#autotoc_md-systemexhash',1,'🔐 SystemEx.Hash'],['../da/d14/a02245.html#systemexhash',1,'SystemEx.Hash']]],
  ['systemex_20include_20an_20interop_20subsystem_24',['Why does SystemEx include an interop subsystem?',['../d4/d48/a02250.html#why-does-systemex-include-an-interop-subsystem',1,'']]],
  ['systemex_20include_20eventgroup‑based_20lighttask_25',['Why does SystemEx include EventGroup‑based LightTask?',['../d4/d48/a02250.html#why-does-systemex-include-eventgroupbased-lighttask',1,'']]],
  ['systemex_20include_20eventgroup_26',['Why does SystemEx include EventGroup?',['../d4/d48/a02250.html#why-does-systemex-include-eventgroup',1,'']]],
  ['systemex_20include_20lightconditionvariable_27',['Why does SystemEx include LightConditionVariable?',['../d4/d48/a02250.html#why-does-systemex-include-lightconditionvariable',1,'']]],
  ['systemex_20include_20lightcountingspinlock_28',['Why does SystemEx include LightCountingSpinlock?',['../d4/d48/a02250.html#why-does-systemex-include-lightcountingspinlock',1,'']]],
  ['systemex_20include_20lightlock_29',['Why does SystemEx include LightLock?',['../d4/d48/a02250.html#why-does-systemex-include-lightlock',1,'']]],
  ['systemex_20include_20lightthread_30',['Why does SystemEx include LightThread?',['../d4/d48/a02250.html#why-does-systemex-include-lightthread',1,'']]],
  ['systemex_20include_20threadex_31',['Why does SystemEx include ThreadEx?',['../d4/d48/a02250.html#why-does-systemex-include-threadex',1,'']]],
  ['systemex_20io_32',['SystemEx IO',['../index.html#autotoc_md-systemexio',1,'📁 SystemEx.IO'],['../da/d14/a02245.html#systemexio',1,'SystemEx.IO']]],
  ['systemex_20license_33',['⚖️ SystemEx License',['../d1/d0c/a02251.html',1,'']]],
  ['systemex_20numeric_34',['SystemEx Numeric',['../index.html#autotoc_md-systemexnumeric',1,'🔢 SystemEx.Numeric'],['../da/d14/a02245.html#systemexnumeric',1,'SystemEx.Numeric']]],
  ['systemex_20random_35',['SystemEx Random',['../index.html#autotoc_md-systemexrandom',1,'🎲 SystemEx.Random'],['../da/d14/a02245.html#systemexrandom',1,'SystemEx.Random']]],
  ['systemex_20runtime_36',['SystemEx Runtime',['../index.html#️-systemexruntime',1,'⚙️ SystemEx.Runtime'],['../da/d14/a02245.html#systemexruntime',1,'SystemEx.Runtime']]],
  ['systemex_20threading_37',['SystemEx Threading',['../index.html#autotoc_md-systemexthreading',1,'🧵 SystemEx.Threading'],['../da/d14/a02245.html#systemexthreading',1,'SystemEx.Threading']]],
  ['systemex_20use_20if_20use_5fdevbuild_5funstable_20blocks_38',['Why does SystemEx use &lt;span class=&quot;tt&quot;&gt;#if USE_DEVBUILD_UNSTABLE&lt;/span&gt; blocks?',['../d4/d48/a02250.html#why-does-systemex-use-if-use_devbuild_unstable-blocks',1,'']]],
  ['systemex_20utils_39',['🧰 SystemEx.Utils',['../index.html#autotoc_md-systemexutils',1,'']]],
  ['systemex_20utils_20bits_40',['🧰 SystemEx.Utils.Bits',['../index.html#autotoc_md-systemexutilsbits',1,'']]],
  ['systemex_20utils_20utils_20bits_41',['SystemEx.Utils / Utils.Bits',['../da/d14/a02245.html#systemexutils--utilsbits',1,'']]]
];
