var searchData=
[
  ['scalar_20types_0',['Scalar Types',['../index.html#scalar-types',1,'']]],
  ['scheduled_20for_20removal_20in_20version_200_2060_1',['Deprecated – Hashable (scheduled for removal in version 0.60)',['../d1/d5d/a02503.html#deprecated--hashable-scheduled-for-removal-in-version-060',1,'']]],
  ['setup_2',['2. API Key Setup',['../d0/dff/a02506.html#autotoc_md2-api-key-setup',1,'']]],
  ['so_20many_20numeric_20types_3',['Why are there so many numeric types?',['../d9/de2/a02508.html#why-are-there-so-many-numeric-types',1,'']]],
  ['split_20into_20multiple_20classes_20instead_20of_20one_20big_20list_4',['Why are the colors split into multiple classes instead of one big list?',['../d9/de2/a02508.html#why-are-the-colors-split-into-multiple-classes-instead-of-one-big-list',1,'']]],
  ['status_5',['🚧 Status',['../index.html#autotoc_md-status',1,'']]],
  ['structures_6',['Why does SystemEx contain duplicated structures?',['../d9/de2/a02508.html#why-does-systemex-contain-duplicated-structures',1,'']]],
  ['subsystem_7',['Why does SystemEx include an interop subsystem?',['../d9/de2/a02508.html#why-does-systemex-include-an-interop-subsystem',1,'']]],
  ['subsystem_20custom_8',['Why is the random subsystem custom?',['../d9/de2/a02508.html#why-is-the-random-subsystem-custom',1,'']]],
  ['systemex_9',['Who maintains SystemEx?',['../d9/de2/a02508.html#who-maintains-systemex',1,'']]],
  ['systemex_20ai_10',['Added – SystemEx.AI',['../d1/d5d/a02503.html#added--systemexai',1,'']]],
  ['systemex_20algorithms_11',['SystemEx Algorithms',['../index.html#autotoc_md-systemexalgorithms',1,'🧮 SystemEx.Algorithms'],['../d4/dad/a02500.html#systemexalgorithms',1,'SystemEx.Algorithms']]],
  ['systemex_20architecture_20overview_12',['🏛️ SystemEx Architecture Overview',['../d4/dad/a02500.html',1,'']]],
  ['systemex_20authors_13',['👤 SystemEx Authors',['../d1/df7/a02501.html',1,'']]],
  ['systemex_20avoid_20net_20task_20and_20threadpool_14',['Why does SystemEx avoid .NET Task and ThreadPool?',['../d9/de2/a02508.html#why-does-systemex-avoid-net-task-and-threadpool',1,'']]],
  ['systemex_20base_20layer_15',['SystemEx Base Layer',['../index.html#autotoc_md-systemex-base-layer',1,'🧱 SystemEx (Base Layer)'],['../d4/dad/a02500.html#systemex-base-layer',1,'SystemEx (Base Layer)']]],
  ['systemex_20changelog_16',['📝 SystemEx Changelog',['../d1/d5d/a02503.html',1,'']]],
  ['systemex_20code_20of_20conduct_17',['📜 SystemEx Code of Conduct',['../d3/df4/a02504.html',1,'']]],
  ['systemex_20collections_20generic_18',['SystemEx Collections Generic',['../index.html#autotoc_md-systemexcollectionsgeneric',1,'📚 SystemEx.Collections.Generic'],['../d4/dad/a02500.html#systemexcollectionsgeneric',1,'SystemEx.Collections.Generic']]],
  ['systemex_20collections_20model_19',['SystemEx Collections Model',['../index.html#autotoc_md-systemexcollectionsmodel',1,'🧬 SystemEx.Collections.Model'],['../d4/dad/a02500.html#systemexcollectionsmodel',1,'SystemEx.Collections.Model']]],
  ['systemex_20contain_20duplicated_20structures_20',['Why does SystemEx contain duplicated structures?',['../d9/de2/a02508.html#why-does-systemex-contain-duplicated-structures',1,'']]],
  ['systemex_20contributing_21',['🤝 SystemEx Contributing',['../d1/d94/a02505.html',1,'']]],
  ['systemex_20drawing_22',['SystemEx Drawing',['../index.html#autotoc_md-systemexdrawing',1,'🎨 SystemEx.Drawing'],['../d4/dad/a02500.html#systemexdrawing',1,'SystemEx.Drawing']]],
  ['systemex_20framework_23',['📘 SystemEx Framework',['../index.html',1,'']]],
  ['systemex_20hash_24',['SystemEx Hash',['../index.html#autotoc_md-systemexhash',1,'🔐 SystemEx.Hash'],['../d4/dad/a02500.html#systemexhash',1,'SystemEx.Hash']]],
  ['systemex_20include_20an_20interop_20subsystem_25',['Why does SystemEx include an interop subsystem?',['../d9/de2/a02508.html#why-does-systemex-include-an-interop-subsystem',1,'']]],
  ['systemex_20include_20eventgroup‑based_20lighttask_26',['Why does SystemEx include EventGroup‑based LightTask?',['../d9/de2/a02508.html#why-does-systemex-include-eventgroupbased-lighttask',1,'']]],
  ['systemex_20include_20eventgroup_27',['Why does SystemEx include EventGroup?',['../d9/de2/a02508.html#why-does-systemex-include-eventgroup',1,'']]],
  ['systemex_20include_20lightconditionvariable_28',['Why does SystemEx include LightConditionVariable?',['../d9/de2/a02508.html#why-does-systemex-include-lightconditionvariable',1,'']]],
  ['systemex_20include_20lightcountingspinlock_29',['Why does SystemEx include LightCountingSpinlock?',['../d9/de2/a02508.html#why-does-systemex-include-lightcountingspinlock',1,'']]],
  ['systemex_20include_20lightlock_30',['Why does SystemEx include LightLock?',['../d9/de2/a02508.html#why-does-systemex-include-lightlock',1,'']]],
  ['systemex_20include_20lightthread_31',['Why does SystemEx include LightThread?',['../d9/de2/a02508.html#why-does-systemex-include-lightthread',1,'']]],
  ['systemex_20include_20threadex_32',['Why does SystemEx include ThreadEx?',['../d9/de2/a02508.html#why-does-systemex-include-threadex',1,'']]],
  ['systemex_20io_33',['SystemEx IO',['../index.html#autotoc_md-systemexio',1,'📁 SystemEx.IO'],['../d4/dad/a02500.html#systemexio',1,'SystemEx.IO']]],
  ['systemex_20license_34',['⚖️ SystemEx License',['../de/dbd/a02507.html',1,'']]],
  ['systemex_20numeric_35',['SystemEx Numeric',['../index.html#autotoc_md-systemexnumeric',1,'🔢 SystemEx.Numeric'],['../d4/dad/a02500.html#systemexnumeric',1,'SystemEx.Numeric']]],
  ['systemex_20random_36',['SystemEx Random',['../index.html#autotoc_md-systemexrandom',1,'🎲 SystemEx.Random'],['../d4/dad/a02500.html#systemexrandom',1,'SystemEx.Random']]],
  ['systemex_20runtime_37',['SystemEx Runtime',['../index.html#️-systemexruntime',1,'⚙️ SystemEx.Runtime'],['../d4/dad/a02500.html#systemexruntime',1,'SystemEx.Runtime']]],
  ['systemex_20threading_38',['SystemEx Threading',['../index.html#autotoc_md-systemexthreading',1,'🧵 SystemEx.Threading'],['../d4/dad/a02500.html#systemexthreading',1,'SystemEx.Threading']]],
  ['systemex_20use_20if_20use_5fdevbuild_5funstable_20blocks_39',['Why does SystemEx use &lt;span class=&quot;tt&quot;&gt;#if USE_DEVBUILD_UNSTABLE&lt;/span&gt; blocks?',['../d9/de2/a02508.html#why-does-systemex-use-if-use_devbuild_unstable-blocks',1,'']]],
  ['systemex_20utils_40',['🧰 SystemEx.Utils',['../index.html#autotoc_md-systemexutils',1,'']]],
  ['systemex_20utils_20bits_41',['🧰 SystemEx.Utils.Bits',['../index.html#autotoc_md-systemexutilsbits',1,'']]],
  ['systemex_20utils_20utils_20bits_42',['SystemEx.Utils / Utils.Bits',['../d4/dad/a02500.html#systemexutils--utilsbits',1,'']]]
];
