var searchData=
[
  ['search_20your_20codebase_20for_20the_20old_20namespace_20tokens_20missings_20intertropt_20system_20memory_20missings_20and_20replace_20with_20the_20new_20targets_0',['- Search your codebase for the old namespace tokens (&lt;span class=&quot;tt&quot;&gt;Missings&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;Intertropt&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;System.Memory.Missings&lt;/span&gt;) and replace with the new targets.',['../d1/d5b/md__c_h_a_n_g_e_l_o_g.html#autotoc_md23',1,'']]],
  ['status_1',['🚧 Status',['../index.html#autotoc_md72',1,'']]],
  ['structure_2',['📁 Project Structure',['../index.html#autotoc_md69',1,'']]],
  ['subsystem_20future_20release_3',['🧱 Cache &amp;amp; RAID Subsystem (Future Release)',['../index.html#autotoc_md65',1,'']]],
  ['sysrtemex_20and_20sysrtemex_20utils_20is_20ready_4',['- The Doku in &lt;span class=&quot;tt&quot;&gt;SystemEx.Collections.Generic&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;SystemEx.IO&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;SysrtemEx&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;SysrtemEx.Utils&lt;/span&gt; is ready',['../d1/d5b/md__c_h_a_n_g_e_l_o_g.html#autotoc_md15',1,'']]],
  ['sysrtemex_20utils_20is_20ready_5',['- The Doku in &lt;span class=&quot;tt&quot;&gt;SystemEx.Collections.Generic&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;SystemEx.IO&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;SysrtemEx&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;SysrtemEx.Utils&lt;/span&gt; is ready',['../d1/d5b/md__c_h_a_n_g_e_l_o_g.html#autotoc_md15',1,'']]],
  ['system_6',['System',['../index.html#autotoc_md58',1,'🧩 Iterator System'],['../index.html#autotoc_md62',1,'Map System']]],
  ['system_20memory_20missings_20and_20replace_20with_20the_20new_20targets_7',['- Search your codebase for the old namespace tokens (&lt;span class=&quot;tt&quot;&gt;Missings&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;Intertropt&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;System.Memory.Missings&lt;/span&gt;) and replace with the new targets.',['../d1/d5b/md__c_h_a_n_g_e_l_o_g.html#autotoc_md23',1,'']]],
  ['systemex_20collections_20generic_8',['📘 SystemEx.Collections.Generic',['../index.html',1,'']]],
  ['systemex_20collections_20generic_20systemex_20io_20sysrtemex_20and_20sysrtemex_20utils_20is_20ready_9',['- The Doku in &lt;span class=&quot;tt&quot;&gt;SystemEx.Collections.Generic&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;SystemEx.IO&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;SysrtemEx&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;SysrtemEx.Utils&lt;/span&gt; is ready',['../d1/d5b/md__c_h_a_n_g_e_l_o_g.html#autotoc_md15',1,'']]],
  ['systemex_20docs_10',['SystemEx.Docs',['../dir_ad70d2e1990c162efcbebfe7d7c3d827.html#autotoc_md52',1,'']]],
  ['systemex_20io_20sysrtemex_20and_20sysrtemex_20utils_20is_20ready_11',['- The Doku in &lt;span class=&quot;tt&quot;&gt;SystemEx.Collections.Generic&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;SystemEx.IO&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;SysrtemEx&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;SysrtemEx.Utils&lt;/span&gt; is ready',['../d1/d5b/md__c_h_a_n_g_e_l_o_g.html#autotoc_md15',1,'']]]
];
