var searchData=
[
  ['scalar_20types_0',['Scalar Types',['../index.html#scalar-types',1,'']]],
  ['scheduled_20for_20removal_20in_20version_200_2060_1',['Deprecated – Hashable (scheduled for removal in version 0.60)',['../de/dbd/a02507.html#deprecated--hashable-scheduled-for-removal-in-version-060',1,'']]],
  ['scope_2',['Scope',['../d0/dff/a02506.html#scope',1,'']]],
  ['security_20policy_3',['🚨 Security Policy',['../d0/dff/a02506.html',1,'']]],
  ['setup_4',['2. API Key Setup',['../dd/df4/a02510.html#autotoc_md2-api-key-setup',1,'']]],
  ['so_20many_20numeric_20types_5',['Why are there so many numeric types?',['../db/da2/a02512.html#why-are-there-so-many-numeric-types',1,'']]],
  ['split_20into_20multiple_20classes_20instead_20of_20one_20big_20list_6',['Why are the colors split into multiple classes instead of one big list?',['../db/da2/a02512.html#why-are-the-colors-split-into-multiple-classes-instead-of-one-big-list',1,'']]],
  ['status_7',['🚧 Status',['../index.html#autotoc_md-status',1,'']]],
  ['structures_8',['Why does SystemEx contain duplicated structures?',['../db/da2/a02512.html#why-does-systemex-contain-duplicated-structures',1,'']]],
  ['subsystem_9',['Why does SystemEx include an interop subsystem?',['../db/da2/a02512.html#why-does-systemex-include-an-interop-subsystem',1,'']]],
  ['subsystem_20custom_10',['Why is the random subsystem custom?',['../db/da2/a02512.html#why-is-the-random-subsystem-custom',1,'']]],
  ['supported_20versions_11',['Supported Versions',['../d0/dff/a02506.html#supported-versions',1,'']]],
  ['systemex_12',['Who maintains SystemEx?',['../db/da2/a02512.html#who-maintains-systemex',1,'']]],
  ['systemex_20ai_13',['Added – SystemEx.AI',['../de/dbd/a02507.html#added--systemexai',1,'']]],
  ['systemex_20algorithms_14',['SystemEx Algorithms',['../index.html#autotoc_md-systemexalgorithms',1,'🧮 SystemEx.Algorithms'],['../d1/d5d/a02503.html#systemexalgorithms',1,'SystemEx.Algorithms']]],
  ['systemex_20architecture_20overview_15',['🏛️ SystemEx Architecture Overview',['../d1/d5d/a02503.html',1,'']]],
  ['systemex_20authors_16',['👤 SystemEx Authors',['../d3/df4/a02504.html',1,'']]],
  ['systemex_20avoid_20net_20task_20and_20threadpool_17',['Why does SystemEx avoid .NET Task and ThreadPool?',['../db/da2/a02512.html#why-does-systemex-avoid-net-task-and-threadpool',1,'']]],
  ['systemex_20base_20layer_18',['SystemEx Base Layer',['../index.html#autotoc_md-systemex-base-layer',1,'🧱 SystemEx (Base Layer)'],['../d1/d5d/a02503.html#systemex-base-layer',1,'SystemEx (Base Layer)']]],
  ['systemex_20changelog_19',['📝 SystemEx Changelog',['../de/dbd/a02507.html',1,'']]],
  ['systemex_20code_20of_20conduct_20',['📜 SystemEx Code of Conduct',['../d9/de2/a02508.html',1,'']]],
  ['systemex_20collections_20generic_21',['SystemEx Collections Generic',['../index.html#autotoc_md-systemexcollectionsgeneric',1,'📚 SystemEx.Collections.Generic'],['../d1/d5d/a02503.html#systemexcollectionsgeneric',1,'SystemEx.Collections.Generic']]],
  ['systemex_20collections_20model_22',['SystemEx Collections Model',['../index.html#autotoc_md-systemexcollectionsmodel',1,'🧬 SystemEx.Collections.Model'],['../d1/d5d/a02503.html#systemexcollectionsmodel',1,'SystemEx.Collections.Model']]],
  ['systemex_20contain_20duplicated_20structures_23',['Why does SystemEx contain duplicated structures?',['../db/da2/a02512.html#why-does-systemex-contain-duplicated-structures',1,'']]],
  ['systemex_20contributing_24',['🤝 SystemEx Contributing',['../d6/d28/a02509.html',1,'']]],
  ['systemex_20drawing_25',['SystemEx Drawing',['../index.html#autotoc_md-systemexdrawing',1,'🎨 SystemEx.Drawing'],['../d1/d5d/a02503.html#systemexdrawing',1,'SystemEx.Drawing']]],
  ['systemex_20framework_26',['📘 SystemEx Framework',['../index.html',1,'']]],
  ['systemex_20hash_27',['SystemEx Hash',['../index.html#autotoc_md-systemexhash',1,'🔐 SystemEx.Hash'],['../d1/d5d/a02503.html#systemexhash',1,'SystemEx.Hash']]],
  ['systemex_20include_20an_20interop_20subsystem_28',['Why does SystemEx include an interop subsystem?',['../db/da2/a02512.html#why-does-systemex-include-an-interop-subsystem',1,'']]],
  ['systemex_20include_20eventgroup‑based_20lighttask_29',['Why does SystemEx include EventGroup‑based LightTask?',['../db/da2/a02512.html#why-does-systemex-include-eventgroupbased-lighttask',1,'']]],
  ['systemex_20include_20eventgroup_30',['Why does SystemEx include EventGroup?',['../db/da2/a02512.html#why-does-systemex-include-eventgroup',1,'']]],
  ['systemex_20include_20lightconditionvariable_31',['Why does SystemEx include LightConditionVariable?',['../db/da2/a02512.html#why-does-systemex-include-lightconditionvariable',1,'']]],
  ['systemex_20include_20lightcountingspinlock_32',['Why does SystemEx include LightCountingSpinlock?',['../db/da2/a02512.html#why-does-systemex-include-lightcountingspinlock',1,'']]],
  ['systemex_20include_20lightlock_33',['Why does SystemEx include LightLock?',['../db/da2/a02512.html#why-does-systemex-include-lightlock',1,'']]],
  ['systemex_20include_20lightthread_34',['Why does SystemEx include LightThread?',['../db/da2/a02512.html#why-does-systemex-include-lightthread',1,'']]],
  ['systemex_20include_20threadex_35',['Why does SystemEx include ThreadEx?',['../db/da2/a02512.html#why-does-systemex-include-threadex',1,'']]],
  ['systemex_20io_36',['SystemEx IO',['../index.html#autotoc_md-systemexio',1,'📁 SystemEx.IO'],['../d1/d5d/a02503.html#systemexio',1,'SystemEx.IO']]],
  ['systemex_20license_37',['⚖️ SystemEx License',['../d0/d01/a02511.html',1,'']]],
  ['systemex_20numeric_38',['SystemEx Numeric',['../index.html#autotoc_md-systemexnumeric',1,'🔢 SystemEx.Numeric'],['../d1/d5d/a02503.html#systemexnumeric',1,'SystemEx.Numeric']]],
  ['systemex_20random_39',['SystemEx Random',['../index.html#autotoc_md-systemexrandom',1,'🎲 SystemEx.Random'],['../d1/d5d/a02503.html#systemexrandom',1,'SystemEx.Random']]],
  ['systemex_20runtime_40',['SystemEx Runtime',['../index.html#️-systemexruntime',1,'⚙️ SystemEx.Runtime'],['../d1/d5d/a02503.html#systemexruntime',1,'SystemEx.Runtime']]],
  ['systemex_20threading_41',['SystemEx Threading',['../index.html#autotoc_md-systemexthreading',1,'🧵 SystemEx.Threading'],['../d1/d5d/a02503.html#systemexthreading',1,'SystemEx.Threading']]],
  ['systemex_20use_20if_20use_5fdevbuild_5funstable_20blocks_42',['Why does SystemEx use &lt;span class=&quot;tt&quot;&gt;#if USE_DEVBUILD_UNSTABLE&lt;/span&gt; blocks?',['../db/da2/a02512.html#why-does-systemex-use-if-use_devbuild_unstable-blocks',1,'']]],
  ['systemex_20utils_43',['🧰 SystemEx.Utils',['../index.html#autotoc_md-systemexutils',1,'']]],
  ['systemex_20utils_20bits_44',['🧰 SystemEx.Utils.Bits',['../index.html#autotoc_md-systemexutilsbits',1,'']]],
  ['systemex_20utils_20utils_20bits_45',['SystemEx.Utils / Utils.Bits',['../d1/d5d/a02503.html#systemexutils--utilsbits',1,'']]]
];
