var searchData=
[
  ['dangerous_20when_20used_20incorrectly_0',['Why is BitView dangerous when used incorrectly?',['../d9/de2/a02508.html#why-is-bitview-dangerous-when-used-incorrectly',1,'']]],
  ['delayed_1',['Why might responses be delayed?',['../d9/de2/a02508.html#why-might-responses-be-delayed',1,'']]],
  ['deprecated_2',['Deprecated',['../d1/d5d/a02503.html#deprecated',1,'']]],
  ['deprecated_20–_20hashable_20scheduled_20for_20removal_20in_20version_200_2060_3',['Deprecated – Hashable (scheduled for removal in version 0.60)',['../d1/d5d/a02503.html#deprecated--hashable-scheduled-for-removal-in-version-060',1,'']]],
  ['design_4',['3.2 Respect modular design',['../d3/df4/a02504.html#autotoc_md32-respect-modular-design',1,'']]],
  ['design_20choice_3a_20controlled_20duplication_5',['🧱 Design Choice: Controlled Duplication',['../d4/dad/a02500.html#autotoc_md-design-choice-controlled-duplication',1,'']]],
  ['development_20channels_6',['Build Flags and Development Channels',['../d4/dad/a02500.html#build-flags-and-development-channels',1,'']]],
  ['development_20flags_7',['Experimental Features and Development Flags',['../d1/d94/a02505.html#experimental-features-and-development-flags',1,'']]],
  ['discuss_20major_20changes_20first_8',['3.3 Discuss major changes first',['../d3/df4/a02504.html#autotoc_md33-discuss-major-changes-first',1,'']]],
  ['docu_9',['Docu',['../d1/d5d/a02503.html#docu',1,'']]],
  ['documentation_20milestone_10',['Major Documentation Milestone',['../d1/d5d/a02503.html#major-documentation-milestone',1,'']]],
  ['does_20systemex_20avoid_20net_20task_20and_20threadpool_11',['Why does SystemEx avoid .NET Task and ThreadPool?',['../d9/de2/a02508.html#why-does-systemex-avoid-net-task-and-threadpool',1,'']]],
  ['does_20systemex_20contain_20duplicated_20structures_12',['Why does SystemEx contain duplicated structures?',['../d9/de2/a02508.html#why-does-systemex-contain-duplicated-structures',1,'']]],
  ['does_20systemex_20include_20an_20interop_20subsystem_13',['Why does SystemEx include an interop subsystem?',['../d9/de2/a02508.html#why-does-systemex-include-an-interop-subsystem',1,'']]],
  ['does_20systemex_20include_20eventgroup‑based_20lighttask_14',['Why does SystemEx include EventGroup‑based LightTask?',['../d9/de2/a02508.html#why-does-systemex-include-eventgroupbased-lighttask',1,'']]],
  ['does_20systemex_20include_20eventgroup_15',['Why does SystemEx include EventGroup?',['../d9/de2/a02508.html#why-does-systemex-include-eventgroup',1,'']]],
  ['does_20systemex_20include_20lightconditionvariable_16',['Why does SystemEx include LightConditionVariable?',['../d9/de2/a02508.html#why-does-systemex-include-lightconditionvariable',1,'']]],
  ['does_20systemex_20include_20lightcountingspinlock_17',['Why does SystemEx include LightCountingSpinlock?',['../d9/de2/a02508.html#why-does-systemex-include-lightcountingspinlock',1,'']]],
  ['does_20systemex_20include_20lightlock_18',['Why does SystemEx include LightLock?',['../d9/de2/a02508.html#why-does-systemex-include-lightlock',1,'']]],
  ['does_20systemex_20include_20lightthread_19',['Why does SystemEx include LightThread?',['../d9/de2/a02508.html#why-does-systemex-include-lightthread',1,'']]],
  ['does_20systemex_20include_20threadex_20',['Why does SystemEx include ThreadEx?',['../d9/de2/a02508.html#why-does-systemex-include-threadex',1,'']]],
  ['does_20systemex_20use_20if_20use_5fdevbuild_5funstable_20blocks_21',['Why does SystemEx use &lt;span class=&quot;tt&quot;&gt;#if USE_DEVBUILD_UNSTABLE&lt;/span&gt; blocks?',['../d9/de2/a02508.html#why-does-systemex-use-if-use_devbuild_unstable-blocks',1,'']]],
  ['drawing_22',['Drawing',['../index.html#autotoc_md-systemexdrawing',1,'🎨 SystemEx.Drawing'],['../d4/dad/a02500.html#systemexdrawing',1,'SystemEx.Drawing']]],
  ['duplicated_20structures_23',['Why does SystemEx contain duplicated structures?',['../d9/de2/a02508.html#why-does-systemex-contain-duplicated-structures',1,'']]],
  ['duplication_24',['🧱 Design Choice: Controlled Duplication',['../d4/dad/a02500.html#autotoc_md-design-choice-controlled-duplication',1,'']]]
];
