var searchData=
[
  ['can_20i_20contribute_0',['How can I contribute?',['../db/da2/a02512.html#how-can-i-contribute',1,'']]],
  ['can_20i_20find_20a_20list_20of_20predefined_20colors_1',['Where can I find a list of predefined colors?',['../db/da2/a02512.html#where-can-i-find-a-list-of-predefined-colors',1,'']]],
  ['caution_20very_20important_2',['CAUTION Very Important',['../de/dbd/a02507.html#caution-very-important',1,'']]],
  ['changed_3',['Changed',['../de/dbd/a02507.html#changed',1,'Changed'],['../de/dbd/a02507.html#changed-1',1,'Changed'],['../de/dbd/a02507.html#changed-2',1,'Changed'],['../de/dbd/a02507.html#changed-3',1,'Changed'],['../de/dbd/a02507.html#changed-4',1,'Changed'],['../de/dbd/a02507.html#changed-5',1,'Changed'],['../de/dbd/a02507.html#changed-6',1,'Changed'],['../de/dbd/a02507.html#changed-7',1,'Changed'],['../de/dbd/a02507.html#changed-8',1,'Changed'],['../de/dbd/a02507.html#changed-9',1,'Changed'],['../de/dbd/a02507.html#changed-10',1,'Changed'],['../de/dbd/a02507.html#changed-11',1,'Changed'],['../de/dbd/a02507.html#changed-12',1,'Changed'],['../de/dbd/a02507.html#changed-13',1,'Changed'],['../de/dbd/a02507.html#changed-14',1,'Changed']]],
  ['changelog_4',['📝 SystemEx Changelog',['../de/dbd/a02507.html',1,'']]],
  ['changes_5',['2. Proposing Changes',['../d6/d28/a02509.html#autotoc_md2-proposing-changes',1,'']]],
  ['changes_20first_6',['3.3 Discuss major changes first',['../d9/de2/a02508.html#autotoc_md33-discuss-major-changes-first',1,'']]],
  ['channels_7',['Build Flags and Development Channels',['../d1/d5d/a02503.html#build-flags-and-development-channels',1,'']]],
  ['checklist_8',['1. Pre-Publish Checklist',['../dd/df4/a02510.html#autotoc_md1-pre-publish-checklist',1,'']]],
  ['choice_3a_20controlled_20duplication_9',['🧱 Design Choice: Controlled Duplication',['../d1/d5d/a02503.html#autotoc_md-design-choice-controlled-duplication',1,'']]],
  ['classes_20instead_20of_20one_20big_20list_10',['Why are the colors split into multiple classes instead of one big list?',['../db/da2/a02512.html#why-are-the-colors-split-into-multiple-classes-instead-of-one-big-list',1,'']]],
  ['code_20of_20conduct_11',['📜 SystemEx Code of Conduct',['../d9/de2/a02508.html',1,'']]],
  ['codename_20update_3a_20ignoring_20→_20lacking_12',['Codename Update: Ignoring → Lacking',['../de/dbd/a02507.html#codename-update-ignoring--lacking',1,'']]],
  ['collaboration_20guidelines_13',['3. Technical Collaboration Guidelines',['../d9/de2/a02508.html#autotoc_md3-technical-collaboration-guidelines',1,'']]],
  ['collections_20generic_14',['Collections Generic',['../index.html#autotoc_md-systemexcollectionsgeneric',1,'📚 SystemEx.Collections.Generic'],['../d1/d5d/a02503.html#systemexcollectionsgeneric',1,'SystemEx.Collections.Generic']]],
  ['collections_20model_15',['Collections Model',['../index.html#autotoc_md-systemexcollectionsmodel',1,'🧬 SystemEx.Collections.Model'],['../d1/d5d/a02503.html#systemexcollectionsmodel',1,'SystemEx.Collections.Model']]],
  ['colors_16',['Where can I find a list of predefined colors?',['../db/da2/a02512.html#where-can-i-find-a-list-of-predefined-colors',1,'']]],
  ['colors_20split_20into_20multiple_20classes_20instead_20of_20one_20big_20list_17',['Why are the colors split into multiple classes instead of one big list?',['../db/da2/a02512.html#why-are-the-colors-split-into-multiple-classes-instead-of-one-big-list',1,'']]],
  ['conduct_18',['📜 SystemEx Code of Conduct',['../d9/de2/a02508.html',1,'']]],
  ['contain_20duplicated_20structures_19',['Why does SystemEx contain duplicated structures?',['../db/da2/a02512.html#why-does-systemex-contain-duplicated-structures',1,'']]],
  ['contribute_20',['How to Contribute',['../d6/d28/a02509.html#how-to-contribute',1,'']]],
  ['contribute_21',['How can I contribute?',['../db/da2/a02512.html#how-can-i-contribute',1,'']]],
  ['contributing_22',['🤝 SystemEx Contributing',['../d6/d28/a02509.html',1,'']]],
  ['controlled_20duplication_23',['🧱 Design Choice: Controlled Duplication',['../d1/d5d/a02503.html#autotoc_md-design-choice-controlled-duplication',1,'']]],
  ['core_20philosophy_24',['✨ Core Philosophy',['../index.html#autotoc_md-core-philosophy',1,'']]],
  ['core_20principles_25',['🧱 Core Principles',['../d1/d5d/a02503.html#autotoc_md-core-principles',1,'']]],
  ['correcture_26',['Correcture',['../de/dbd/a02507.html#correcture',1,'']]],
  ['coution_27',['Update Coution',['../de/dbd/a02507.html#update-coution',1,'']]],
  ['custom_28',['Why is the random subsystem custom?',['../db/da2/a02512.html#why-is-the-random-subsystem-custom',1,'']]]
];
