var searchData=
[
  ['dangerous_20when_20used_20incorrectly_0',['Why is BitView dangerous when used incorrectly?',['../d4/d48/a02250.html#why-is-bitview-dangerous-when-used-incorrectly',1,'']]],
  ['delayed_1',['Why might responses be delayed?',['../d4/d48/a02250.html#why-might-responses-be-delayed',1,'']]],
  ['deprecated_2',['Deprecated',['../df/d71/a02247.html#deprecated',1,'']]],
  ['deprecated_20–_20hashable_20scheduled_20for_20removal_20in_20version_200_2060_3',['Deprecated – Hashable (scheduled for removal in version 0.60)',['../df/d71/a02247.html#deprecated--hashable-scheduled-for-removal-in-version-060',1,'']]],
  ['deprecated_20list_4',['Deprecated List',['../dd/d7e/a00809.html',1,'']]],
  ['design_5',['3.2 Respect modular design',['../dc/de2/a02248.html#autotoc_md32-respect-modular-design',1,'']]],
  ['design_20choice_3a_20controlled_20duplication_6',['🧱 Design Choice: Controlled Duplication',['../da/d14/a02245.html#autotoc_md-design-choice-controlled-duplication',1,'']]],
  ['development_20channels_7',['Build Flags and Development Channels',['../da/d14/a02245.html#build-flags-and-development-channels',1,'']]],
  ['development_20flags_8',['Experimental Features and Development Flags',['../dd/dc3/a02249.html#experimental-features-and-development-flags',1,'']]],
  ['discuss_20major_20changes_20first_9',['3.3 Discuss major changes first',['../dc/de2/a02248.html#autotoc_md33-discuss-major-changes-first',1,'']]],
  ['docu_10',['Docu',['../df/d71/a02247.html#docu',1,'']]],
  ['documentation_20milestone_11',['Major Documentation Milestone',['../df/d71/a02247.html#major-documentation-milestone',1,'']]],
  ['does_20systemex_20avoid_20net_20task_20and_20threadpool_12',['Why does SystemEx avoid .NET Task and ThreadPool?',['../d4/d48/a02250.html#why-does-systemex-avoid-net-task-and-threadpool',1,'']]],
  ['does_20systemex_20contain_20duplicated_20structures_13',['Why does SystemEx contain duplicated structures?',['../d4/d48/a02250.html#why-does-systemex-contain-duplicated-structures',1,'']]],
  ['does_20systemex_20include_20an_20interop_20subsystem_14',['Why does SystemEx include an interop subsystem?',['../d4/d48/a02250.html#why-does-systemex-include-an-interop-subsystem',1,'']]],
  ['does_20systemex_20include_20eventgroup‑based_20lighttask_15',['Why does SystemEx include EventGroup‑based LightTask?',['../d4/d48/a02250.html#why-does-systemex-include-eventgroupbased-lighttask',1,'']]],
  ['does_20systemex_20include_20eventgroup_16',['Why does SystemEx include EventGroup?',['../d4/d48/a02250.html#why-does-systemex-include-eventgroup',1,'']]],
  ['does_20systemex_20include_20lightconditionvariable_17',['Why does SystemEx include LightConditionVariable?',['../d4/d48/a02250.html#why-does-systemex-include-lightconditionvariable',1,'']]],
  ['does_20systemex_20include_20lightcountingspinlock_18',['Why does SystemEx include LightCountingSpinlock?',['../d4/d48/a02250.html#why-does-systemex-include-lightcountingspinlock',1,'']]],
  ['does_20systemex_20include_20lightlock_19',['Why does SystemEx include LightLock?',['../d4/d48/a02250.html#why-does-systemex-include-lightlock',1,'']]],
  ['does_20systemex_20include_20lightthread_20',['Why does SystemEx include LightThread?',['../d4/d48/a02250.html#why-does-systemex-include-lightthread',1,'']]],
  ['does_20systemex_20include_20threadex_21',['Why does SystemEx include ThreadEx?',['../d4/d48/a02250.html#why-does-systemex-include-threadex',1,'']]],
  ['does_20systemex_20use_20if_20use_5fdevbuild_5funstable_20blocks_22',['Why does SystemEx use &lt;span class=&quot;tt&quot;&gt;#if USE_DEVBUILD_UNSTABLE&lt;/span&gt; blocks?',['../d4/d48/a02250.html#why-does-systemex-use-if-use_devbuild_unstable-blocks',1,'']]],
  ['drawing_23',['Drawing',['../index.html#autotoc_md-systemexdrawing',1,'🎨 SystemEx.Drawing'],['../da/d14/a02245.html#systemexdrawing',1,'SystemEx.Drawing']]],
  ['duplicated_20structures_24',['Why does SystemEx contain duplicated structures?',['../d4/d48/a02250.html#why-does-systemex-contain-duplicated-structures',1,'']]],
  ['duplication_25',['🧱 Design Choice: Controlled Duplication',['../da/d14/a02245.html#autotoc_md-design-choice-controlled-duplication',1,'']]]
];
