var NAVTREEINDEX9 =
{
"index.html#autotoc_md-installation":[0,1],
"index.html#autotoc_md-iterator-system":[0,2],
"index.html#autotoc_md-license":[0,8],
"index.html#autotoc_md-overview":[0,0],
"index.html#autotoc_md-project-structure":[0,7],
"index.html#autotoc_md-status":[0,9],
"index.html#autotoc_md-utilities":[0,6],
"index.html#core-types":[0,4,0],
"index.html#manual":[0,1,1],
"index.html#map-system":[0,4,1],
"index.html#nuget":[0,1,0],
"index.html#tuple--pair-types":[0,4,2],
"namespacemembers.html":[5,1,0],
"namespacemembers_enum.html":[5,1,2],
"namespacemembers_func.html":[5,1,1],
"namespaces.html":[5,0],
"pages.html":[],
"topics.html":[4]
};
